import { cpSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { VeskConfig } from '@vesk/native';
import { collectDeviceApiUsage, iosUsageStrings } from './usage.js';

const pbxUuid = (() => {
  let n = 0;
  return (): string => {
    const hex = (n++).toString(16).padStart(6, '0');
    return `VESK0000000000000000${hex}`.slice(-24).toUpperCase();
  };
})();

// Canonical KMP framework embed/sign build phase, byte-for-byte the shell
// script JetBrains ships in the current KMP wizard (Kotlin/kmp-wizard,
// iosApp.xcodeproj "Compile Kotlin Framework") and documents for embedding a
// KMP framework. The pbxproj \n / \" escapes reproduce exactly what Xcode
// writes; $SRCROOT / $OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED expand at build
// time. The task runs from the gradle project root ($SRCROOT/..), builds the
// :shared framework and embeds + signs it into the app bundle.
const kotlinEmbedShellScript =
  'if [ \\"YES\\" = \\"$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED\\" ]; then\\n' +
  '  echo \\"Skipping Gradle build task invocation due to OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED environment variable set to \\\\\\"YES\\\\\\"\\"\\n' +
  '  exit 0\\n' +
  'fi\\n' +
  'cd \\"$SRCROOT/..\\"\\n' +
  './gradlew :shared:embedAndSignAppleFrameworkForXcode\\n';

// ---------------------------------------------------------------------------
// iOS project generation (Xcode 26 / iOS 26 SDK era, verified against the
// 2026 Apple release requirements). Everything an Xcode build needs is
// generated here — the user never writes .pbxproj/Info.plist/entitlements by
// hand. Signing values come from veskconfig.signing.ios; secrets reference
// `env:NAME` and are never written into generated files.
//
// The generated app is a Compose Multiplatform client (see CMP-PLAN.md): the
// :shared KMP module builds a `Shared` framework via
// embedAndSignAppleFrameworkForXcode, and ContentView.swift embeds the CMP
// entry point (MainViewController, exposed by the Shared framework) behind a
// UIViewControllerRepresentable. The iosMain actuals behind that entry point
// (Runtime.ios.kt, MainViewController.kt, Router.ios.kt) are generated by
// generators.ts; privacy usage strings in Info.plist are derived from the
// app's device-API usage, never emitted "just in case".
// ---------------------------------------------------------------------------

export function generateIosProject(target: string, config: VeskConfig): void {
  const iosDir = join(target, 'ios');
  const appDir = join(iosDir, 'VeskApp');
  const teamId = config.signing?.ios?.teamId ?? 'XXXXXXXXXX';
  const signingStyle = config.signing?.ios?.style ?? 'automatic';
  const deploymentTarget = '17.0';

  mkdirSync(join(iosDir, 'VeskApp.xcodeproj'), { recursive: true });
  mkdirSync(appDir, { recursive: true });

  // Assets.xcassets for app icon + accent color
  const assetsDir = join(appDir, 'Assets.xcassets');
  const iconDir = join(assetsDir, 'AppIcon.appiconset');
  const colorDir = join(assetsDir, 'AccentColor.colorset');
  mkdirSync(iconDir, { recursive: true });
  mkdirSync(colorDir, { recursive: true });

  // Root asset catalog manifest
  writeFileSync(join(assetsDir, 'Contents.json'), '{\n  "info" : { "version" : 1, "author" : "xcode" }\n}\n');

  // App icon set — auto-detect assets/icon.png or use config.icon.foreground
  const iconSource = config.icon?.foreground ?? (existsSync(join(target, 'assets', 'icon.png')) ? 'assets/icon.png' : undefined);
  if (iconSource) {
    const srcPath = resolve(target, iconSource);
    if (existsSync(srcPath)) {
      cpSync(srcPath, join(iconDir, 'icon.png'));
      writeFileSync(join(iconDir, 'Contents.json'),
        '{\n  "images" : [\n    { "idiom" : "universal", "platform" : "ios", "size" : "1024x1024", "filename" : "icon.png" }\n  ],\n  "info" : { "version" : 1, "author" : "xcode" }\n}\n'
      );
    }
  } else {
    // Empty icon set — user drags in Xcode
    writeFileSync(join(iconDir, 'Contents.json'),
      '{\n  "images" : [\n    { "idiom" : "universal", "platform" : "ios", "size" : "1024x1024" }\n  ],\n  "info" : { "version" : 1, "author" : "xcode" }\n}\n'
    );
  }

  // Accent color from config
  const primaryColor = config.colors.primary.replace('#', '');
  writeFileSync(join(colorDir, 'Contents.json'),
    `{\n  "colors" : [{ "idiom" : "universal", "color" : {\n    "color-space" : "srgb",\n    "components" : {\n      "red" : "0x${primaryColor.slice(0, 2)}", "green" : "0x${primaryColor.slice(2, 4)}", "blue" : "0x${primaryColor.slice(4, 6)}", "alpha" : "1.000"\n    }\n  }}],\n  "info" : { "version" : 1, "author" : "xcode" }\n}\n`
  );

  // Auto-detect splash.png for LaunchScreen
  const hasSplashImage = existsSync(join(target, 'assets', 'splash.png'));
  const hasSplashVsk = existsSync(join(target, 'app', 'splash.vsk'));
  const splashEnabled = config.splash?.enabled ?? (hasSplashImage || hasSplashVsk);

  if (splashEnabled) {
    const splashBg = config.splash?.backgroundColor ?? config.colors.background;
    // Copy splash.png to asset catalog if present
    let splashImageName = 'AppIcon';
    if (hasSplashImage) {
      cpSync(join(target, 'assets', 'splash.png'), join(assetsDir, 'splash.png'));
      splashImageName = 'splash';
      // Update asset catalog to include splash image
      const splashImgDir = join(assetsDir, 'splash.imageset');
      mkdirSync(splashImgDir, { recursive: true });
      cpSync(join(target, 'assets', 'splash.png'), join(splashImgDir, 'splash.png'));
      writeFileSync(join(splashImgDir, 'Contents.json'),
        '{\n  "images" : [\n    { "idiom" : "universal", "filename" : "splash.png", "scale" : "1x" },\n    { "idiom" : "universal", "scale" : "2x" },\n    { "idiom" : "universal", "scale" : "3x" }\n  ],\n  "info" : { "version" : 1, "author" : "xcode" }\n}\n'
      );
    }

    writeFileSync(join(appDir, 'LaunchScreen.storyboard'),
      `<?xml version="1.0" encoding="UTF-8"?>\n<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="21701" targetRuntime="AppleSDK" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" useTraitCollections="YES" useSafeAreas="YES" colorMatched="YES" initialViewController="01J-lp-oVM">\n    <scenes>\n        <scene sceneID="EHf-IW-A2E">\n            <objects>\n                <viewController id="01J-lp-oVM" sceneMemberID="viewController">\n                    <view key="view" contentMode="scaleToFill" id="Ze5-6b-2t3">\n                        <rect key="frame" x="0.0" y="0.0" width="393" height="852"/>\n                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>\n                        <subviews>\n                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" image="${splashImageName}" translatesAutoresizingMaskIntoConstraints="NO" id="YRO-k0-Aw4">\n                                <rect key="frame" x="156.5" y="346" width="80" height="80"/>\n                                <constraints>\n                                    <constraint firstAttribute="width" constant="80" id="w1"/>\n                                    <constraint firstAttribute="height" constant="80" id="h1"/>\n                                </constraints>\n                            </imageView>\n                        </subviews>\n                        <color key="backgroundColor" red="${parseInt(splashBg.slice(1, 3), 16) / 255}" green="${parseInt(splashBg.slice(3, 5), 16) / 255}" blue="${parseInt(splashBg.slice(5, 7), 16) / 255}" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>\n                        <constraints>\n                            <constraint firstItem="YRO-k0-Aw4" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" id="cx"/>\n                            <constraint firstItem="YRO-k0-Aw4" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" id="cy"/>\n                        </constraints>\n                    </view>\n                </viewController>\n                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>\n            </objects>\n            <point key="canvasLocation" x="53" y="375"/>\n        </scene>\n    </scenes>\n</document>\n`
    );
  }

  if (config.signing?.ios?.style === 'manual') {
    mkdirSync(join(iosDir, 'profiles'), { recursive: true });
  }

  writeFileSync(join(appDir, 'Info.plist'), iosInfoPlist(config, iosUsageStrings(collectDeviceApiUsage(join(target, 'app'))), target));
  writeFileSync(join(appDir, 'VeskApp.entitlements'), iosEntitlements());
  writeFileSync(join(appDir, 'VeskApp.swift'), iosAppSwift());
  writeFileSync(join(appDir, 'ContentView.swift'), iosContentView());
  writeFileSync(join(iosDir, 'VeskApp.xcodeproj', 'project.pbxproj'), iosPbxproj(config, teamId, signingStyle, deploymentTarget));
}

function iosInfoPlist(config: VeskConfig, usageStrings: Map<string, string> = new Map(), target?: string): string {
  // Usage-derived privacy strings: only keys the app's device-API calls need
  // (capture/scan -> camera, record -> microphone, ...), verified against
  // Apple's Info.plist keys. Never emitted "just in case".
  const usageBlock = [...usageStrings.entries()]
    .map(([key, purpose]) => `	<key>${key}</key>
	<string>${purpose}</string>`)
    .join('\n');
  const usageSection = usageBlock ? `\n${usageBlock}\n` : '';

  // Detect splash screen auto-detection
  const hasSplashVsk = target ? existsSync(join(target, 'app', 'splash.vsk')) : false;
  const hasSplashImage = target ? existsSync(join(target, 'assets', 'splash.png')) : false;
  const splashEnabled = config.splash?.enabled ?? (hasSplashVsk || hasSplashImage);

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>${config.appName}</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
	<key>CFBundleShortVersionString</key>
	<string>${config.versionName}</string>
	<key>CFBundleVersion</key>
	<string>${config.versionCode}</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIApplicationSceneManifest</key>
	<dict>
		<key>UIApplicationSupportsMultipleScenes</key>
		<false/>
	</dict>
	<key>${splashEnabled ? 'UILaunchStoryboardName' : 'UILaunchScreen'}</key>
	${splashEnabled ? '<string>LaunchScreen</string>' : '<dict/>'}
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>${usageSection}</dict>
</plist>
`;
}

function iosEntitlements(): string {
  // App Sandbox + push are opt-in capabilities; nothing is declared "just in
  // case". The profile must cover whatever is listed here.
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
</plist>
`;
}

function iosAppSwift(): string {
  return `import SwiftUI

// vesk-native iOS shell. ContentView embeds the Shared Kotlin Multiplatform
// (Compose Multiplatform) framework; the iosMain actuals land in Phase 5.
@main
struct VeskApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
`;
}

function iosContentView(): string {
  return `import UIKit
import SwiftUI
import Shared

// ContentView embeds the Compose Multiplatform UI rendered by the Shared
// (Kotlin Multiplatform) framework. MainViewControllerKt is the ObjC/Swift
// export of the iosMain top-level fun MainViewController() from
// MainViewController.kt (the iosMain actuals are Phase 5); the
// Kt-qualified name is the canonical form the JetBrains KMP wizard ships.
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard) // Compose has its own keyboard handling
    }
}

#Preview {
    ContentView()
}
`;
}

function iosPbxproj(config: VeskConfig, teamId: string, signingStyle: string, deploymentTarget: string): string {
  // One native target. The Shared.framework built by the :shared KMP module is
  // linked via FRAMEWORK_SEARCH_PATHS + OTHER_LDFLAGS and embedded by the
  // "Compile Kotlin Framework" phase — the exact mechanism JetBrains ships in
  // compose-multiplatform-template / the KMP wizard. objectVersion 56 is
  // accepted by Xcode 14+ through Xcode 26.
  const appSwift = pbxUuid();
  const contentSwift = pbxUuid();
  const shellScriptPhase = pbxUuid();
  const sourcesBuildPhase = pbxUuid();
  const resourcesBuildPhase = pbxUuid();
  const frameworksBuildPhase = pbxUuid();
  const fileRefApp = pbxUuid();
  const fileRefContent = pbxUuid();
  const fileRefInfo = pbxUuid();
  const fileRefEntitlements = pbxUuid();
  const fileRefProduct = pbxUuid();
  const groupVeskApp = pbxUuid();
  const groupMain = pbxUuid();
  const groupProducts = pbxUuid();
  const target = pbxUuid();
  const project = pbxUuid();
  const buildConfigListTarget = pbxUuid();
  const buildConfigListProject = pbxUuid();
  const buildConfigDebugTarget = pbxUuid();
  const buildConfigReleaseTarget = pbxUuid();
  const buildConfigDebugProject = pbxUuid();
  const buildConfigReleaseProject = pbxUuid();
  const assetsBuildFile = pbxUuid();
  const assetsFileRef = pbxUuid();

  const codeSignStyle = signingStyle === 'manual' ? '"Manual"' : '"Automatic"';
  const team = teamId !== 'XXXXXXXXXX' ? `\t\t\t\tDEVELOPMENT_TEAM = ${teamId};\n` : '';

  return `// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 56;
	objects = {

/* Begin PBXBuildFile section */
		${appSwift} /* VeskApp.swift in Sources */ = {isa = PBXBuildFile; fileRef = ${fileRefApp} /* VeskApp.swift */; };
		${contentSwift} /* ContentView.swift in Sources */ = {isa = PBXBuildFile; fileRef = ${fileRefContent} /* ContentView.swift */; };
		${assetsBuildFile} /* Assets.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = ${assetsFileRef} /* Assets.xcassets */; };
/* End PBXBuildFile section */

/* Begin PBXFileReference section */
		${fileRefApp} /* VeskApp.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = VeskApp.swift; sourceTree = "<group>"; };
		${fileRefContent} /* ContentView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = ContentView.swift; sourceTree = "<group>"; };
		${fileRefInfo} /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
		${fileRefEntitlements} /* VeskApp.entitlements */ = {isa = PBXFileReference; lastKnownFileType = text.plist.entitlements; path = VeskApp.entitlements; sourceTree = "<group>"; };
		${fileRefProduct} /* VeskApp.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = VeskApp.app; sourceTree = BUILT_PRODUCTS_DIR; };
		${assetsFileRef} /* Assets.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = Assets.xcassets; sourceTree = "<group>"; };
/* End PBXFileReference section */

/* Begin PBXFrameworksBuildPhase section */
		${frameworksBuildPhase} /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
		${groupMain} = {
			isa = PBXGroup;
			children = (
				${groupVeskApp} /* VeskApp */,
				${groupProducts} /* Products */,
			);
			sourceTree = "<group>";
		};
		${groupVeskApp} /* VeskApp */ = {
			isa = PBXGroup;
			children = (
				${fileRefApp} /* VeskApp.swift */,
				${fileRefContent} /* ContentView.swift */,
				${fileRefInfo} /* Info.plist */,
				${fileRefEntitlements} /* VeskApp.entitlements */,
				${assetsFileRef} /* Assets.xcassets */,
			);
			path = VeskApp;
			sourceTree = "<group>";
		};
		${groupProducts} /* Products */ = {
			isa = PBXGroup;
			children = (
				${fileRefProduct} /* VeskApp.app */,
			);
			name = Products;
			sourceTree = "<group>";
		};
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
		${target} /* VeskApp */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = ${buildConfigListTarget} /* Build configuration list for PBXNativeTarget "VeskApp" */;
			buildPhases = (
				${shellScriptPhase} /* Compile Kotlin Framework */,
				${sourcesBuildPhase} /* Sources */,
				${frameworksBuildPhase} /* Frameworks */,
				${resourcesBuildPhase} /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = VeskApp;
			productName = VeskApp;
			productReference = ${fileRefProduct} /* VeskApp.app */;
			productType = "com.apple.product-type.application";
		};
/* End PBXNativeTarget section */

/* Begin PBXProject section */
		${project} /* Project object */ = {
			isa = PBXProject;
			attributes = {
				BuildIndependentTargetsInParallel = 1;
				LastSwiftUpdateCheck = 1600;
				LastUpgradeCheck = 1600;
				TargetAttributes = {
					${target} = {
						CreatedOnToolsVersion = 16.0;
					};
				};
			};
			buildConfigurationList = ${buildConfigListProject} /* Build configuration list for PBXProject "VeskApp" */;
			compatibilityVersion = "Xcode 14.0";
			developmentRegion = en;
			hasScannedForEncodings = 0;
			knownRegions = (
				en,
				Base,
			);
			mainGroup = ${groupMain};
			productRefGroup = ${groupProducts} /* Products */;
			projectDirPath = "";
			projectRoot = "";
			targets = (
				${target} /* VeskApp */,
			);
		};
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
		${resourcesBuildPhase} /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				${assetsBuildFile} /* Assets.xcassets in Resources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXResourcesBuildPhase section */

/* Begin PBXShellScriptBuildPhase section */
		${shellScriptPhase} /* Compile Kotlin Framework */ = {
			isa = PBXShellScriptBuildPhase;
			alwaysOutOfDate = 1;
			buildActionMask = 2147483647;
			files = (
			);
			inputFileListPaths = (
			);
			inputPaths = (
			);
			name = "Compile Kotlin Framework";
			outputFileListPaths = (
			);
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "${kotlinEmbedShellScript}";
		};
/* End PBXShellScriptBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
		${sourcesBuildPhase} /* Sources */ = {
			isa = PBXSourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				${appSwift} /* VeskApp.swift in Sources */,
				${contentSwift} /* ContentView.swift in Sources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXSourcesBuildPhase section */

/* Begin XCBuildConfiguration section */
		${buildConfigDebugProject} /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				COPY_PHASE_STRIP = NO;
				DEBUG_INFORMATION_FORMAT = dwarf;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				ENABLE_TESTABILITY = YES;
				ENABLE_USER_SCRIPT_SANDBOXING = NO;
				GCC_C_LANGUAGE_STANDARD = gnu17;
				GCC_DYNAMIC_NO_PIC = NO;
				GCC_NO_COMMON_BLOCKS = YES;
				GCC_OPTIMIZATION_LEVEL = 0;
				GCC_PREPROCESSOR_DEFINITIONS = (
					"DEBUG=1",
					"$(inherited)",
				);
				IPHONEOS_DEPLOYMENT_TARGET = ${deploymentTarget};
				MTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE;
				MTL_FAST_MATH = YES;
				ONLY_ACTIVE_ARCH = YES;
				SDKROOT = iphoneos;
				SWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;
				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
			};
			name = Debug;
		};
		${buildConfigReleaseProject} /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				COPY_PHASE_STRIP = NO;
				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
				ENABLE_NS_ASSERTIONS = NO;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				ENABLE_USER_SCRIPT_SANDBOXING = NO;
				GCC_C_LANGUAGE_STANDARD = gnu17;
				GCC_NO_COMMON_BLOCKS = YES;
				IPHONEOS_DEPLOYMENT_TARGET = ${deploymentTarget};
				MTL_ENABLE_DEBUG_INFO = NO;
				MTL_FAST_MATH = YES;
				SDKROOT = iphoneos;
				SWIFT_COMPILATION_MODE = wholemodule;
				SWIFT_OPTIMIZATION_LEVEL = "-O";
				VALIDATE_PRODUCT = YES;
			};
			name = Release;
		};
		${buildConfigDebugTarget} /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				CODE_SIGN_ENTITLEMENTS = VeskApp/VeskApp.entitlements;
				CODE_SIGN_STYLE = ${codeSignStyle};
${team}				CURRENT_PROJECT_VERSION = ${config.versionCode};
				FRAMEWORK_SEARCH_PATHS = (
					"$(inherited)",
					"$(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)",
				);
				GENERATE_INFOPLIST_FILE = NO;
				INFOPLIST_FILE = VeskApp/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = (
					"$(inherited)",
					"@executable_path/Frameworks",
				);
				MARKETING_VERSION = ${config.versionName};
				OTHER_LDFLAGS = (
					"$(inherited)",
					"-framework",
					Shared,
				);
				PRODUCT_BUNDLE_IDENTIFIER = ${config.appId};
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_EMIT_LOC_STRINGS = YES;
				SWIFT_VERSION = 5.0;
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Debug;
		};
		${buildConfigReleaseTarget} /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				CODE_SIGN_ENTITLEMENTS = VeskApp/VeskApp.entitlements;
				CODE_SIGN_STYLE = ${codeSignStyle};
${team}				CURRENT_PROJECT_VERSION = ${config.versionCode};
				FRAMEWORK_SEARCH_PATHS = (
					"$(inherited)",
					"$(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)",
				);
				GENERATE_INFOPLIST_FILE = NO;
				INFOPLIST_FILE = VeskApp/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = (
					"$(inherited)",
					"@executable_path/Frameworks",
				);
				MARKETING_VERSION = ${config.versionName};
				OTHER_LDFLAGS = (
					"$(inherited)",
					"-framework",
					Shared,
				);
				PRODUCT_BUNDLE_IDENTIFIER = ${config.appId};
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_EMIT_LOC_STRINGS = YES;
				SWIFT_VERSION = 5.0;
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Release;
		};
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
		${buildConfigListProject} /* Build configuration list for PBXProject "VeskApp" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				${buildConfigDebugProject} /* Debug */,
				${buildConfigReleaseProject} /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
		${buildConfigListTarget} /* Build configuration list for PBXNativeTarget "VeskApp" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				${buildConfigDebugTarget} /* Debug */,
				${buildConfigReleaseTarget} /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
/* End XCConfigurationList section */
	};
	rootObject = ${project} /* Project object */;
}
`;
}

// ExportOptions.plist rendered at bundle time from veskconfig (2026 key set:
// method uses the current 'app-store-connect' name; bitcode keys are dead
// since Xcode 14 and intentionally absent).
export function iosExportOptions(config: VeskConfig, provisioningProfileUuid?: string): string {
  const ios = config.signing?.ios;
  const bundle = config.bundle?.ios;
  const method = bundle?.method ?? 'app-store-connect';
  const destination = bundle?.destination ?? 'export';
  const teamId = ios?.teamId ?? 'XXXXXXXXXX';
  const signingStyle = ios?.style ?? 'automatic';
  const uploadSymbols = bundle?.uploadSymbols ?? true;
  const profileMap = provisioningProfileUuid
    ? `\t<key>provisioningProfiles</key>
\t<dict>
\t\t<key>${config.appId}</key>
\t\t<string>${provisioningProfileUuid}</string>
\t</dict>
`
    : ios?.style === 'manual' && ios.provisioningProfile
      ? `\t<key>provisioningProfiles</key>
\t<dict>
\t\t<key>${config.appId}</key>
\t\t<string>${ios.provisioningProfile}</string>
\t</dict>
`
      : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>${method}</string>
	<key>destination</key>
	<string>${destination}</string>
	<key>teamID</key>
	<string>${teamId}</string>
	<key>signingStyle</key>
	<string>${signingStyle}</string>
${profileMap}	<key>uploadSymbols</key>
	<${uploadSymbols}/>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>manageAppVersionAndBuildNumber</key>
	<false/>
</dict>
</plist>
`;
}

// The generated iOS build dir (archive + exports) lives under the app's build
// directory so `vesk bundle` output is reproducible and greppable.
export function iosBuildDir(target: string): string {
  return join(target, 'build', 'ios');
}

export function requireIosSigning(config: VeskConfig): void {
  const ios = config.signing?.ios;
  if (!ios) {
    throw new Error('vesk bundle (iOS) needs veskconfig.signing.ios (teamId at minimum) — see packages/native/src/config.ts');
  }
  if (!/^[A-Z0-9]{10}$/.test(ios.teamId)) {
    throw new Error(`vesk bundle (iOS): teamId must be the 10-character Apple Developer team id, got "${ios.teamId}"`);
  }
  if (ios.style === 'manual' && !ios.certificatePath) {
    throw new Error('vesk bundle (iOS): manual signing needs veskconfig.signing.ios.certificatePath (.p12) and provisioningProfile');
  }
  if (ios.style === 'automatic' && !existsSync(resolve(process.env.HOME ?? '/', 'Library', 'MobileDevice'))) {
    // Not fatal: automatic signing resolves profiles via -allowProvisioningUpdates.
  }
}