import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { LibExportSig, VskLibTag } from '@compiler-native/elements';
import { loadRegistry, writeVsklibRecordFile } from '@cli-native/vsklib-registry';

// Installed Kotlin libraries are tracked in the app's root `libraries.json` —
// the single source of truth, committed to git like package.json, and written
// only by the CLI (`vesk add/remove/update`, plus the build/bundle flows that
// read it). Users never hand-edit it and never touch gradle files or the
// manifest. `.vsklib/` is a gitignored, disposable scratch directory that
// holds the per-library `.vsklib` record files (metadata + exports + typed
// signatures) regenerated by add/remove/update/install; the committed catalog
// of known libraries ships as `.vsklib` data files under registry/ and is
// loaded by the CLI when resolving `vesk add/update <pkg>` — never source.

export interface VskLibRecord {
  id: string;
  name: string;
  description: string;
  group: string;
  artifact: string;
  version: string;
  // "group:artifact:version" coordinates emitted as implementation(...) deps.
  gradle: string[];
  // Whether the artifact publishes Kotlin Multiplatform common metadata
  // (the `metadataApiElements` variant in its real Gradle module metadata —
  // `org.jetbrains.kotlin.platform.type: common`). True means commonMain can
  // depend on the same coordinate, so a page importing this library can be
  // emitted into src/commonMain; false (or absent) keeps the page in
  // androidMain. Derived by binding-gen from the real published `.module`
  // metadata and verified by the registry conformance gate — never guessed.
  multiplatform?: boolean;
  // Minimum Android API level this library compiles/links against (ycharts
  // needs 26, most libs are 21–24). The generated app minSdk is raised to the
  // max across installed libraries — never an overrideLibrary workaround.
  minSdk?: number;
  // Manifest <uses-permission> entries this library requires. Only the ones
  // actually needed on device (e.g. INTERNET for network clients) — a library
  // that works without a permission must not declare it "just in case".
  permissions: string[];
  // JS-visible surface the binding will expose (exports + .vsk element tags).
  // Printed by `vesk add`; consumed by the binding compiler (Phase 9f).
  exports: string[];
  // Typed signatures for the JS-visible exports (constructors, enums, typed
  // functions). Present on auto-generated bindings (Phase 9g); registry entries
  // without signatures degrade to the plain `exports` name list.
  signatures?: Record<string, LibExportSig>;
  // .vsk element tag bindings: tag name -> composable mapping emitted by the
  // compiler (attrs map .vsk props to composable parameters; imports are the
  // page-file Kotlin imports the callable needs).
  tags: Record<string, VskLibTag>;
  // How the library is consumed from `.vsk`. A `component` library exposes
  // markup tags — a composable usable directly as an element (e.g. <GlideImage>
  // or <YLineChart>) — while a `utility` library is used through its JS-visible
  // function/value exports (e.g. Gson(), OkHttpClient()). Derived from whether
  // the record carries markup `tags`; never hand-authored from memory.
  libType: 'utility' | 'component';
  // The first-curated tier of the catalog: the libraries almost every app
  // needs (images, HTTP, JSON, persistence, work). Always resolvable offline,
  // surfaced first in `vesk registry` and in `vesk add` help. It is a data
  // flag — everything else about an essential library is still registry data,
  // not framework source code.
  essential?: boolean;
  // Hand-authored catalog entry: the record is trusted as-is, so `vesk add`
  // skips the auto-generated metadata fallback that would otherwise run for
  // records without signatures. Auto-generated bindings never set this.
  curated?: boolean;
}

export interface VskLibrariesFile {
  version: 1;
  libraries: Record<string, VskLibRecord>;
}

// `.vsklib/` is gitignored and disposable — never a source of truth.
export const VSKLIB_DIR = '.vsklib';
export const LIBRARIES_FILE = 'libraries.json';

// The library catalog lives in committed `.vsklib` data files under
// registry/<category>/<id>.vsklib — not in framework source. Each record is
// the full typed surface (exports, signatures, markup tags, permissions) that
// `vesk add/update` resolve against; the loader below is the only place the
// CLI reads them from. Keeping the catalog as data means growing the registry
// is a data change, never a framework rebuild, and the same format doubles as
// the contract library maintainers can author natively.
export const LIBRARY_REGISTRY: VskLibRecord[] = loadRegistry();

// Library permission rules, registered by Maven group the same way device APIs
// register in API_PERMISSIONS. These cover permissions a library needs at
// runtime but cannot declare in its own AAR manifest: network clients (okhttp,
// retrofit, coil, glide, ...) need INTERNET while shipping without it (the app
// or a transitive dependency is expected to supply it). Applied at add/update
// time and persisted into the library record — users never add them by hand
// after `vesk add`. AAR-declared permissions (from AndroidManifest.xml) and
// these rules are merged by deriveLibraryPermissions.
export const LIBRARY_PERMISSION_RULES: Record<string, string[]> = {
  'io.coil-kt': ['android.permission.INTERNET'],
  'com.github.bumptech.glide': ['android.permission.INTERNET'],
  'com.squareup.okhttp': ['android.permission.INTERNET'],
  'com.squareup.okhttp3': ['android.permission.INTERNET'],
  'com.squareup.retrofit2': ['android.permission.INTERNET'],
  'com.squareup.picasso': ['android.permission.INTERNET'],
  'io.ktor': ['android.permission.INTERNET'],
};

export function deriveLibraryPermissions(rec: Pick<VskLibRecord, 'group' | 'permissions'>): string[] {
  const out = new Set(rec.permissions);
  for (const p of LIBRARY_PERMISSION_RULES[rec.group] ?? []) out.add(p);
  return [...out];
}

export function librariesFilePath(target: string): string {
  // Single committed source of truth at the project root (like package.json).
  return join(target, LIBRARIES_FILE);
}

export function loadLibraries(target: string): VskLibrariesFile {
  const p = librariesFilePath(target);
  if (!existsSync(p)) return { version: 1, libraries: {} };
  const raw = JSON.parse(readFileSync(p, 'utf8')) as Partial<VskLibrariesFile>;
  return { version: 1, libraries: raw.libraries ?? {} };
}

export function saveLibraries(target: string, data: VskLibrariesFile): void {
  const p = librariesFilePath(target);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, `${JSON.stringify(data, null, 2)}\n`);
}

export function installedLibraries(target: string): VskLibRecord[] {
  // The committed root manifest (libraries.json) is the single source of
  // truth: its records hold the full surface (metadata + exports + typed
  // signatures) and are exactly what the compiler consumes at build time.
  // The .vsklib/ cache is a derived, disposable mirror written by add/update/
  // remove — never consulted for resolution, so a stale or missing cache
  // cannot change what compiles.
  return Object.values(loadLibraries(target).libraries);
}

// Rewrite the disposable `.vsklib/` cache from the committed root manifest.
// Each installed library gets its own `<id>.vsklib` record file (metadata +
// exports + typed signatures) in the same format the registry catalog uses —
// so the fetched/auto-generated surface for a library always lives in data,
// never in framework source. add/remove/update keep it in sync; install
// re-verifies first.
export function writeVsklibCache(target: string, records: VskLibRecord[]): void {
  const cacheDir = join(target, VSKLIB_DIR);
  mkdirSync(cacheDir, { recursive: true });
  for (const f of existsSync(cacheDir) ? readdirSync(cacheDir).filter((n) => n.endsWith('.vsklib')) : []) {
    rmSync(join(cacheDir, f));
  }
  for (const rec of records) writeVsklibRecordFile(join(cacheDir, `${rec.id}.vsklib`), rec);
}

// `vesk verify` — explicit, read-only diagnostic: check every pinned
// coordinate in the committed manifest against the real repositories
// (androidx on Google Maven, everything else on Maven Central). It never
// mutates state: the build compiles against the manifest as-is, so a bad pin
// fails loudly at gradle time, not silently here. Offline → 'unverified'
// (warn, keep the pin).
export interface VerifySummary {
  id: string;
  coordinate: string;
  status: VerifyResult['status'];
  latest?: string;
}

export async function verifyLibraries(target: string): Promise<VerifySummary[]> {
  const data = loadLibraries(target);
  const out: VerifySummary[] = [];
  for (const rec of Object.values(data.libraries)) {
    const verify = await verifyLibrary(rec);
    out.push({
      id: rec.id,
      coordinate: `${rec.group}:${rec.artifact}@${rec.version}`,
      status: verify.status,
      latest: verify.latest,
    });
  }
  return out;
}

// Library spec forms: `id`, `id@version`, `group:artifact`, `group:artifact@version`.
export interface LibrarySpec {
  id?: string;
  group?: string;
  artifact?: string;
  version?: string;
}

export function parseLibrarySpec(input: string): LibrarySpec {
  const spec: LibrarySpec = {};
  let rest = input.trim();
  const at = rest.indexOf('@');
  if (at >= 0) {
    spec.version = rest.slice(at + 1);
    rest = rest.slice(0, at);
  }
  const colon = rest.indexOf(':');
  if (colon >= 0) {
    spec.group = rest.slice(0, colon);
    spec.artifact = rest.slice(colon + 1);
    if (!spec.group || !spec.artifact) throw new Error(`invalid library spec "${input}" — expected id, id@version, group:artifact or group:artifact@version`);
  } else {
    spec.id = rest;
    if (!spec.id) throw new Error(`invalid library spec "${input}" — expected id, id@version, group:artifact or group:artifact@version`);
  }
  return spec;
}

export function withVersion(rec: VskLibRecord, version: string): VskLibRecord {
  return {
    ...rec,
    version,
    gradle: rec.gradle.map((g) => g.replace(/:[^:]+$/, `:${version}`)),
  };
}

export function resolveLibrary(spec: LibrarySpec, registry: VskLibRecord[] = LIBRARY_REGISTRY): VskLibRecord {
  let rec: VskLibRecord | undefined;
  if (spec.group && spec.artifact) {
    rec = registry.find((r) => r.group === spec.group && r.artifact === spec.artifact);
    if (!rec) throw new Error(`unknown library "${spec.group}:${spec.artifact}" — not in the builtin .vsklib registry`);
  } else if (spec.id) {
    rec = registry.find((r) => r.id === spec.id);
    if (!rec) {
      const known = registry.map((r) => r.id).join(', ');
      throw new Error(`unknown library "${spec.id}" — not in the builtin .vsklib registry (known: ${known})`);
    }
  } else {
    throw new Error('empty library spec — expected id, id@version, group:artifact or group:artifact@version');
  }
  return spec.version ? withVersion(rec, spec.version) : rec;
}

export interface VerifyResult {
  status: 'verified' | 'unverified' | 'not-found' | 'version-missing';
  latest?: string;
}

function tagContent(xml: string, tag: string): string | null {
  const open = `<${tag}>`;
  const close = `</${tag}>`;
  const s = xml.indexOf(open);
  if (s < 0) return null;
  const e = xml.indexOf(close, s + open.length);
  if (e < 0) return null;
  return xml.slice(s + open.length, e);
}

function parseVersions(xml: string): string[] {
  const out: string[] = [];
  const open = '<version>';
  const close = '</version>';
  let s = 0;
  for (;;) {
    const a = xml.indexOf(open, s);
    if (a < 0) break;
    const b = xml.indexOf(close, a + open.length);
    if (b < 0) break;
    out.push(xml.slice(a + open.length, b));
    s = b + close.length;
  }
  return out;
}

export async function mavenMetadata(rec: VskLibRecord): Promise<{ reachable: boolean; notFound: boolean; latest?: string; versions: string[] }> {
  // androidx artifacts publish to Google Maven, everything else to Maven
  // Central; a coordinate is only 'not-found' when it 404s on both.
  const urls = [
    `https://repo1.maven.org/maven2/${rec.group.replaceAll('.', '/')}/${rec.artifact}/maven-metadata.xml`,
    `https://dl.google.com/android/maven2/${rec.group.replaceAll('.', '/')}/${rec.artifact}/maven-metadata.xml`,
  ];
  for (const url of urls) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(10_000), redirect: 'follow' });
      if (res.status === 404) continue;
      if (!res.ok) return { reachable: true, notFound: false, versions: [] };
      const text = await res.text();
      return {
        reachable: true,
        notFound: false,
        latest: tagContent(text, 'latest') ?? undefined,
        versions: parseVersions(text),
      };
    } catch {
      return { reachable: false, notFound: false, versions: [] };
    }
  }
  return { reachable: true, notFound: true, versions: [] };
}

// Best-effort check against Maven Central so a typo'd coordinate fails loudly
// at install time instead of at gradle time. Offline/refused → 'unverified'
// (warn, keep the registry pin); 404 or missing version → hard error.
export async function verifyLibrary(rec: VskLibRecord): Promise<VerifyResult> {
  const meta = await mavenMetadata(rec);
  if (!meta.reachable) return { status: 'unverified' };
  if (meta.notFound) return { status: 'not-found' };
  if (meta.versions.length === 0) return { status: 'unverified' };
  if (!meta.versions.includes(rec.version)) return { status: 'version-missing', latest: meta.latest };
  return { status: 'verified', latest: meta.latest };
}
