// Generated by vesk-native from activity-compose.vsklib — do not edit by hand.
// Type surface for the `@vesk/activity-compose` virtual module (AndroidX Activity Compose 1.9.2).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <BackHandler>, <PredictiveBackHandler>, <ReportDrawn>, <ReportDrawnAfter>, <ReportDrawnWhen>.

export declare interface ManagedActivityResultLauncher {}

export declare function ManagedActivityResultLauncher(props: {
    launcher: any;
    currentContract: any;
  }): ManagedActivityResultLauncher;

export declare const BackHandler: any;

export declare const PredictiveBackHandler: any;

export declare const ReportDrawn: any;

export declare const ReportDrawnAfter: any;

export declare const ReportDrawnWhen: any;
