// Generated by vesk-native from animation.vsklib — do not edit by hand.
// Type surface for the `@vesk/animation` virtual module (Compose Animation 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <AnimatedVisibility>.

export declare interface ContentTransform {}

export declare function ContentTransform(props: {
    targetContentEnter: any;
    initialContentExit: any;
    targetContentZIndex?: number;
    sizeTransform?: any;
  }): ContentTransform;

export declare const EnterExitState: {
    readonly PreEnter: 'PreEnter';
    readonly Visible: 'Visible';
    readonly PostExit: 'PostExit';
  };

export declare type EnterExitState = (typeof EnterExitState)[keyof typeof EnterExitState];

export declare interface SplineBasedFloatDecayAnimationSpec {}

export declare function SplineBasedFloatDecayAnimationSpec(props: {
    density: any;
  }): SplineBasedFloatDecayAnimationSpec;

export declare const AnimatedVisibility: any;
