// Generated by vesk-native from animation-graphics.vsklib — do not edit by hand.
// Type surface for the `@vesk/animation-graphics` virtual module (Compose Animation Graphics 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface AnimatedImageVector {}

/**

 * AnimatedImageVector — public constructor in animation-graphics 1.6.8: AnimatedImageVector(imageVector, targets). AnimatedVectorTarget is a sealed interface; instances also come from XML vector resources via loadAnimatedVectorResource(theme, resources, id) + rememberAnimatedVectorPainter.

 */

export declare function AnimatedImageVector(props: {
    imageVector: any;
    targets: Array<any>;
  }): AnimatedImageVector;
