// Generated by vesk-native from animation-core.vsklib — do not edit by hand.
// Type surface for the `@vesk/animation-core` virtual module (Compose Animation Core 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface Animatable {}

export declare function Animatable(props: {
    initialValue: any;
    typeConverter: any;
    visibilityThreshold?: any;
    label?: string;
  }): Animatable;

export declare const AnimationEndReason: {
    readonly BoundReached: 'BoundReached';
    readonly Finished: 'Finished';
  };

export declare type AnimationEndReason = (typeof AnimationEndReason)[keyof typeof AnimationEndReason];

export declare interface AnimationResult {}

export declare function AnimationResult(props: {
    endState: any;
    endReason: 'BoundReached' | 'Finished';
  }): AnimationResult;

export declare interface AnimationScope {}

export declare function AnimationScope(props: {
    initialValue: any;
    typeConverter: any;
    initialVelocityVector: any;
    lastFrameTimeNanos: number;
    targetValue: any;
    startTimeNanos: number;
    isRunning: boolean;
    onCancel: (...args: any[]) => any;
  }): AnimationScope;

export declare interface AnimationState {}

export declare function AnimationState(props: {
    typeConverter: any;
    initialValue: any;
    initialVelocityVector?: any;
    lastFrameTimeNanos?: number;
    finishedTimeNanos?: number;
    isRunning?: boolean;
  }): AnimationState;

export declare interface AnimationVector1D {}

export declare function AnimationVector1D(props: {
    initVal: number;
  }): AnimationVector1D;

export declare interface AnimationVector2D {}

export declare function AnimationVector2D(props: {
    v1: number;
    v2: number;
  }): AnimationVector2D;

export declare interface AnimationVector3D {}

export declare function AnimationVector3D(props: {
    v1: number;
    v2: number;
    v3: number;
  }): AnimationVector3D;

export declare interface AnimationVector4D {}

export declare function AnimationVector4D(props: {
    v1: number;
    v2: number;
    v3: number;
    v4: number;
  }): AnimationVector4D;

export declare interface CubicBezierEasing {}

export declare function CubicBezierEasing(props: {
    a: number;
    b: number;
    c: number;
    d: number;
  }): CubicBezierEasing;

export declare interface DecayAnimation {}

export declare function DecayAnimation(props: {
    animationSpec: any;
    typeConverter: any;
    initialValue: any;
    initialVelocityVector: any;
  }): DecayAnimation;

export declare interface FloatExponentialDecaySpec {}

export declare function FloatExponentialDecaySpec(props: {
    frictionMultiplier?: number;
    absVelocityThreshold?: number;
  }): FloatExponentialDecaySpec;

export declare interface FloatSpringSpec {}

export declare function FloatSpringSpec(props: {
    dampingRatio?: number;
    stiffness?: number;
    visibilityThreshold?: number;
  }): FloatSpringSpec;

export declare interface FloatTweenSpec {}

export declare function FloatTweenSpec(props: {
    duration?: number;
    delay?: number;
    easing?: any;
  }): FloatTweenSpec;

export declare interface InfiniteRepeatableSpec {}

export declare function InfiniteRepeatableSpec(props: {
    animation: any;
    repeatMode?: 'Restart' | 'Reverse';
    initialStartOffset?: any;
  }): InfiniteRepeatableSpec;

export declare interface InfiniteTransition {}

export declare function InfiniteTransition(props: {
    label: string;
  }): InfiniteTransition;

export declare interface KeyframesSpec {}

export declare function KeyframesSpec(props: {
    config: any;
  }): KeyframesSpec;

export declare interface KeyframesWithSplineSpec {}

export declare function KeyframesWithSplineSpec(props: {
    config: any;
  }): KeyframesWithSplineSpec;

export declare interface MutableTransitionState {}

export declare function MutableTransitionState(props: {
    initialState: any;
  }): MutableTransitionState;

export declare interface PathEasing {}

export declare function PathEasing(props: {
    path: any;
  }): PathEasing;

export declare const RepeatMode: {
    readonly Restart: 'Restart';
    readonly Reverse: 'Reverse';
  };

export declare type RepeatMode = (typeof RepeatMode)[keyof typeof RepeatMode];

export declare interface RepeatableSpec {}

export declare function RepeatableSpec(props: {
    iterations: number;
    animation: any;
    repeatMode?: 'Restart' | 'Reverse';
    initialStartOffset?: any;
  }): RepeatableSpec;

export declare interface SeekableTransitionState {}

export declare function SeekableTransitionState(props: {
    initialState: any;
    targetState: any;
  }): SeekableTransitionState;

export declare interface SpringSpec {}

export declare function SpringSpec(props: {
    dampingRatio?: number;
    stiffness?: number;
    visibilityThreshold?: any;
  }): SpringSpec;

export declare interface TargetBasedAnimation {}

export declare function TargetBasedAnimation(props: {
    animationSpec: any;
    typeConverter: any;
    initialValue: any;
    targetValue: any;
    initialVelocityVector?: any;
  }): TargetBasedAnimation;

export declare interface Transition {}

export declare function Transition(props: {
    transitionState: any;
    label?: string;
  }): Transition;

export declare interface TweenSpec {}

export declare function TweenSpec(props: {
    durationMillis?: number;
    delay?: number;
    easing?: any;
  }): TweenSpec;

export declare interface VectorizedFloatAnimationSpec {}

export declare function VectorizedFloatAnimationSpec(props: {
    anims: any;
  }): VectorizedFloatAnimationSpec;

export declare interface VectorizedInfiniteRepeatableSpec {}

export declare function VectorizedInfiniteRepeatableSpec(props: {
    animation: any;
    repeatMode?: 'Restart' | 'Reverse';
    initialStartOffset?: any;
  }): VectorizedInfiniteRepeatableSpec;

export declare interface VectorizedKeyframesSpec {}

export declare function VectorizedKeyframesSpec(props: {
    keyframes: any;
    durationMillis: number;
    delayMillis?: number;
  }): VectorizedKeyframesSpec;

export declare interface VectorizedRepeatableSpec {}

export declare function VectorizedRepeatableSpec(props: {
    iterations: number;
    animation: any;
    repeatMode?: 'Restart' | 'Reverse';
    initialStartOffset?: any;
  }): VectorizedRepeatableSpec;

export declare interface VectorizedSnapSpec {}

export declare function VectorizedSnapSpec(props: {
    delayMillis?: number;
  }): VectorizedSnapSpec;

export declare interface VectorizedTweenSpec {}

export declare function VectorizedTweenSpec(props: {
    durationMillis?: number;
    delayMillis?: number;
    easing?: any;
  }): VectorizedTweenSpec;
