// Generated by vesk-native from apollo.vsklib — do not edit by hand.
// Type surface for the `@vesk/apollo` virtual module (Apollo GraphQL 3.8.3).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const ApolloClient: any;
