// Generated by vesk-native from billing.vsklib — do not edit by hand.
// Type surface for the `@vesk/billing` virtual module (Google Play Billing 6.2.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


