// Generated by vesk-native from biometric.vsklib — do not edit by hand.
// Type surface for the `@vesk/biometric` virtual module (AndroidX Biometric 1.1.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


