// Generated by vesk-native from browser.vsklib — do not edit by hand.
// Type surface for the `@vesk/browser` virtual module (AndroidX Browser 1.8.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


