// Generated by vesk-native from camera-lifecycle.vsklib — do not edit by hand.
// Type surface for the `@vesk/camera-lifecycle` virtual module (CameraX Lifecycle 1.3.4).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


