// Generated by vesk-native from chucker.vsklib — do not edit by hand.
// Type surface for the `@vesk/chucker` virtual module (Chucker 4.0.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const ChuckerInterceptor: any;
