// Generated by vesk-native from coil.vsklib — do not edit by hand.
// Type surface for the `@vesk/coil` virtual module (Coil 2.7.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <CoilImage>.

export declare const AsyncImage: any;

export declare const rememberAsyncImagePainter: any;

export declare const ImageLoader: any;

export declare const ImageRequest: any;

export declare const CoilImage: any;
