// Generated by vesk-native from coil-gif.vsklib — do not edit by hand.
// Type surface for the `@vesk/coil-gif` virtual module (Coil GIF 2.7.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const ImageDecoderDecoder: any;

export declare const PixelOpacity: any;
