// Generated by vesk-native from coil3.vsklib — do not edit by hand.
// Type surface for the `@vesk/coil3` virtual module (Coil 3 3.0.4).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <Coil3Image>.

export declare const AsyncImage: any;

export declare const rememberAsyncImagePainter: any;

export declare const Coil3Image: any;
