// Generated by vesk-native from constraintlayout-compose.vsklib — do not edit by hand.
// Type surface for the `@vesk/constraintlayout-compose` virtual module (ConstraintLayout Compose 1.1.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <ConstraintLayout>, <ItemHolder>, <MotionCarousel>, <MotionLayout>.

export declare interface Arc {}

export declare function Arc(props: {
    name: string;
  }): Arc;

export declare interface ChainStyle {}

export declare function ChainStyle(props: {
    name: string;
    bias?: number;
  }): ChainStyle;

export declare interface ConstrainScope {}

export declare function ConstrainScope(props: {
    id: any;
    containerObject: any;
  }): ConstrainScope;

export declare interface ConstrainedLayoutReference {}

export declare function ConstrainedLayoutReference(props: {
    id: any;
  }): ConstrainedLayoutReference;

export declare interface ConstraintLayoutScope {}

export declare function ConstraintLayoutScope(): ConstraintLayoutScope;

export declare interface ConstraintSetRef {}

export declare function ConstraintSetRef(props: {
    name: string;
  }): ConstraintSetRef;

export declare interface ConstraintSetScope {}

export declare function ConstraintSetScope(props: {
    extendFrom: any;
  }): ConstraintSetScope;

export declare interface CurveFit {}

export declare function CurveFit(props: {
    name: string;
  }): CurveFit;

export declare interface DebugFlags {}

export declare function DebugFlags(props: {
    flags: number;
  }): DebugFlags;

export declare interface Easing {}

export declare function Easing(props: {
    name: string;
  }): Easing;

export declare interface FlowStyle {}

export declare function FlowStyle(props: {
    name: string;
  }): FlowStyle;

export declare interface HorizontalAlign {}

export declare function HorizontalAlign(props: {
    name: string;
  }): HorizontalAlign;

export declare interface HorizontalChainReference {}

export declare function HorizontalChainReference(props: {
    id: any;
  }): HorizontalChainReference;

export declare interface HorizontalChainScope {}

export declare function HorizontalChainScope(props: {
    id: any;
    containerObject: any;
  }): HorizontalChainScope;

export declare interface InvalidationStrategy {}

export declare function InvalidationStrategy(props: {
    onIncomingConstraints?: (...args: any[]) => any;
    onObservedStateChange?: (...args: any[]) => any;
  }): InvalidationStrategy;

export declare interface InvalidationStrategySpecification {}

export declare function InvalidationStrategySpecification(): InvalidationStrategySpecification;

export declare interface KeyAttributeScope {}

export declare function KeyAttributeScope(): KeyAttributeScope;

export declare interface KeyAttributesScope {}

export declare function KeyAttributesScope(props: {
    targets: Array<any>;
  }): KeyAttributesScope;

export declare interface KeyCycleScope {}

export declare function KeyCycleScope(): KeyCycleScope;

export declare interface KeyCyclesScope {}

export declare function KeyCyclesScope(props: {
    targets: Array<any>;
  }): KeyCyclesScope;

export declare interface KeyPositionScope {}

export declare function KeyPositionScope(): KeyPositionScope;

export declare interface KeyPositionsScope {}

export declare function KeyPositionsScope(props: {
    targets: Array<any>;
  }): KeyPositionsScope;

export declare const LayoutInfoFlags: {
    readonly NONE: 'NONE';
    readonly BOUNDS: 'BOUNDS';
  };

export declare type LayoutInfoFlags = (typeof LayoutInfoFlags)[keyof typeof LayoutInfoFlags];

export declare const MotionLayoutDebugFlags: {
    readonly NONE: 'NONE';
    readonly SHOW_ALL: 'SHOW_ALL';
    readonly UNKNOWN: 'UNKNOWN';
  };

export declare type MotionLayoutDebugFlags = (typeof MotionLayoutDebugFlags)[keyof typeof MotionLayoutDebugFlags];

export declare const MotionLayoutFlag: {
    readonly Default: 'Default';
    readonly FullMeasure: 'FullMeasure';
  };

export declare type MotionLayoutFlag = (typeof MotionLayoutFlag)[keyof typeof MotionLayoutFlag];

export declare interface MotionLayoutScope {}

export declare function MotionLayoutScope(props: {
    measurer: any;
    motionProgress: any;
  }): MotionLayoutScope;

export declare interface MotionSceneScope {}

export declare function MotionSceneScope(): MotionSceneScope;

export declare interface OnSwipe {}

export declare function OnSwipe(props: {
    anchor: any;
    side: any;
    direction: any;
    dragScale?: number;
    dragThreshold?: number;
    dragAround?: any;
    limitBoundsTo?: any;
    onTouchUp?: any;
    mode?: any;
  }): OnSwipe;

export declare interface RelativePosition {}

export declare function RelativePosition(props: {
    name: string;
  }): RelativePosition;

export declare interface Span {}

export declare function Span(props: {
    description: string;
  }): Span;

export declare interface SpringBoundary {}

export declare function SpringBoundary(props: {
    name: string;
  }): SpringBoundary;

export declare interface State {}

export declare function State(props: {
    density: any;
  }): State;

export declare interface SwipeDirection {}

export declare function SwipeDirection(props: {
    name: string;
  }): SwipeDirection;

export declare interface SwipeMode {}

export declare function SwipeMode(props: {
    name: string;
    springMass?: number;
    springStiffness?: number;
    springDamping?: number;
    springThreshold?: number;
    springBoundary?: any;
    maxVelocity?: number;
    maxAcceleration?: number;
  }): SwipeMode;

export declare interface SwipeSide {}

export declare function SwipeSide(props: {
    name: string;
  }): SwipeSide;

export declare interface SwipeTouchUp {}

export declare function SwipeTouchUp(props: {
    name: string;
  }): SwipeTouchUp;

export declare interface TransitionScope {}

export declare function TransitionScope(props: {
    from: string;
    to: string;
  }): TransitionScope;

export declare interface VerticalAlign {}

export declare function VerticalAlign(props: {
    name: string;
  }): VerticalAlign;

export declare interface VerticalChainReference {}

export declare function VerticalChainReference(props: {
    id: any;
  }): VerticalChainReference;

export declare interface VerticalChainScope {}

export declare function VerticalChainScope(props: {
    id: any;
    containerObject: any;
  }): VerticalChainScope;

export declare interface Visibility {}

export declare function Visibility(props: {
    name: string;
  }): Visibility;

export declare interface Wrap {}

export declare function Wrap(props: {
    name: string;
  }): Wrap;

export declare const ConstraintLayout: any;

export declare const ItemHolder: any;

export declare const MotionCarousel: any;

export declare const MotionLayout: any;
