// Generated by vesk-native from core-ktx.vsklib — do not edit by hand.
// Type surface for the `@vesk/core-ktx` virtual module (AndroidX Core KTX 1.13.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


