// Generated by vesk-native from coroutines.vsklib — do not edit by hand.
// Type surface for the `@vesk/coroutines` virtual module (kotlinx.coroutines 1.7.3).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


