// Generated by vesk-native from datastore.vsklib — do not edit by hand.
// Type surface for the `@vesk/datastore` virtual module (DataStore 1.1.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const preferencesDataStore: any;
