// Generated by vesk-native from datetime.vsklib — do not edit by hand.
// Type surface for the `@vesk/datetime` virtual module (kotlinx-datetime 0.6.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface DatePeriod {}

export declare function DatePeriod(props: {
    totalMonths: number;
    days: number;
  }): DatePeriod;

export declare interface FixedOffsetTimeZone {}

export declare function FixedOffsetTimeZone(props: {
    offset: any;
    zoneId: any;
  }): FixedOffsetTimeZone;

export declare interface Instant {}

export declare function Instant(props: {
    value: any;
  }): Instant;

export declare interface LocalDate {}

export declare function LocalDate(props: {
    value: any;
  }): LocalDate;

export declare interface LocalDateTime {}

export declare function LocalDateTime(props: {
    value: any;
  }): LocalDateTime;

export declare interface LocalTime {}

export declare function LocalTime(props: {
    value: any;
  }): LocalTime;

export declare interface TimeZone {}

export declare function TimeZone(props: {
    zoneId: any;
  }): TimeZone;

export declare interface UtcOffset {}

export declare function UtcOffset(props: {
    zoneOffset: any;
  }): UtcOffset;

export declare const AmPmMarker: {
    readonly AM: 'AM';
    readonly PM: 'PM';
  };

export declare type AmPmMarker = (typeof AmPmMarker)[keyof typeof AmPmMarker];

export declare const Padding: {
    readonly NONE: 'NONE';
    readonly ZERO: 'ZERO';
    readonly SPACE: 'SPACE';
  };

export declare type Padding = (typeof Padding)[keyof typeof Padding];
