// Generated by vesk-native from exifinterface.vsklib — do not edit by hand.
// Type surface for the `@vesk/exifinterface` virtual module (ExifInterface 1.3.7).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const ExifInterface: any;
