// Generated by vesk-native from firebase-messaging.vsklib — do not edit by hand.
// Type surface for the `@vesk/firebase-messaging` virtual module (Firebase Cloud Messaging 23.4.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface FirebaseMessagingKtxRegistrar {}

export declare function FirebaseMessagingKtxRegistrar(): FirebaseMessagingKtxRegistrar;
