// Generated by vesk-native from foundation-layout.vsklib — do not edit by hand.
// Type surface for the `@vesk/foundation-layout` virtual module (Compose Foundation Layout 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <Box>, <BoxWithConstraints>, <Column>, <FlowColumn>, <FlowRow>, <Row>, <Spacer>.

export declare const IntrinsicSize: {
    readonly Min: 'Min';
    readonly Max: 'Max';
  };

export declare type IntrinsicSize = (typeof IntrinsicSize)[keyof typeof IntrinsicSize];

export declare interface MutableWindowInsets {}

export declare function MutableWindowInsets(props: {
    initialInsets?: any;
  }): MutableWindowInsets;

export declare const Box: any;

export declare const BoxWithConstraints: any;

export declare const Column: any;

export declare const FlowColumn: any;

export declare const FlowRow: any;

export declare const Row: any;

export declare const Spacer: any;
