// Generated by vesk-native from foundation.vsklib — do not edit by hand.
// Type surface for the `@vesk/foundation` virtual module (Compose Foundation 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <AndroidEmbeddedExternalSurface>, <AndroidExternalSurface>, <BasicTooltipBox>, <Canvas>, <Image>, <LazyColumn>, <LazyRow>, <LazyHorizontalGrid>, <LazyVerticalGrid>, <LazyLayout>, <LazyLayoutPinnableItem>, <LazyHorizontalStaggeredGrid>, <LazyVerticalStaggeredGrid>, <HorizontalPager>, <VerticalPager>, <BasicTextField>, <BasicText>, <ClickableText>, <DisableSelection>, <SelectionContainer>, <BasicSecureTextField>, <BasicTextField2>.

export declare interface BorderStroke {}

export declare function BorderStroke(props: {
    width: any;
    brush: any;
  }): BorderStroke;

export declare const MutatePriority: {
    readonly Default: 'Default';
    readonly UserInput: 'UserInput';
    readonly PreventUserInput: 'PreventUserInput';
  };

export declare type MutatePriority = (typeof MutatePriority)[keyof typeof MutatePriority];

export declare interface MutatorMutex {}

export declare function MutatorMutex(): MutatorMutex;

export declare interface OverscrollConfiguration {}

export declare function OverscrollConfiguration(props: {
    glowColor?: any;
    drawPadding?: any;
  }): OverscrollConfiguration;

export declare interface ScrollState {}

export declare function ScrollState(props: {
    initial: number;
  }): ScrollState;

export declare interface AnchoredDraggableState {}

export declare function AnchoredDraggableState(props: {
    initialValue: any;
    positionalThreshold: (...args: any[]) => any;
    velocityThreshold: (...args: any[]) => any;
    animationSpec: any;
    confirmValueChange?: (...args: any[]) => any;
  }): AnchoredDraggableState;

export declare interface DraggableAnchorsConfig {}

export declare function DraggableAnchorsConfig(): DraggableAnchorsConfig;

export declare interface GestureCancellationException {}

export declare function GestureCancellationException(props: {
    message?: string;
  }): GestureCancellationException;

export declare const Orientation: {
    readonly Vertical: 'Vertical';
    readonly Horizontal: 'Horizontal';
  };

export declare type Orientation = (typeof Orientation)[keyof typeof Orientation];

export declare interface SnapFlingBehavior {}

export declare function SnapFlingBehavior(props: {
    snapLayoutInfoProvider: any;
    lowVelocityAnimationSpec: any;
    highVelocityAnimationSpec: any;
    snapAnimationSpec: any;
  }): SnapFlingBehavior;

export declare interface LazyListState {}

export declare function LazyListState(props: {
    firstVisibleItemIndex?: number;
    firstVisibleItemScrollOffset?: number;
  }): LazyListState;

export declare interface GridItemSpan {}

export declare function GridItemSpan(props: {
    packedValue: number;
  }): GridItemSpan;

export declare interface LazyGridState {}

export declare function LazyGridState(props: {
    firstVisibleItemIndex?: number;
    firstVisibleItemScrollOffset?: number;
  }): LazyGridState;

export declare interface LazyLayoutPrefetchState {}

export declare function LazyLayoutPrefetchState(): LazyLayoutPrefetchState;

export declare interface MutableIntervalList {}

export declare function MutableIntervalList(): MutableIntervalList;

export declare interface AbsoluteCutCornerShape {}

export declare function AbsoluteCutCornerShape(props: {
    topLeft: any;
    topRight: any;
    bottomRight: any;
    bottomLeft: any;
  }): AbsoluteCutCornerShape;

export declare interface AbsoluteRoundedCornerShape {}

export declare function AbsoluteRoundedCornerShape(props: {
    topLeft: any;
    topRight: any;
    bottomRight: any;
    bottomLeft: any;
  }): AbsoluteRoundedCornerShape;

export declare interface CutCornerShape {}

export declare function CutCornerShape(props: {
    topStart: any;
    topEnd: any;
    bottomEnd: any;
    bottomStart: any;
  }): CutCornerShape;

export declare interface GenericShape {}

export declare function GenericShape(props: {
    builder: (...args: any[]) => any;
  }): GenericShape;

export declare interface RoundedCornerShape {}

export declare function RoundedCornerShape(props: {
    topStart: any;
    topEnd: any;
    bottomEnd: any;
    bottomStart: any;
  }): RoundedCornerShape;

export declare interface InlineTextContent {}

export declare function InlineTextContent(props: {
    placeholder: any;
    children: (...args: any[]) => any;
  }): InlineTextContent;

export declare interface KeyboardActions {}

export declare function KeyboardActions(props: {
    onDone?: (...args: any[]) => any;
    onGo?: (...args: any[]) => any;
    onNext?: (...args: any[]) => any;
    onPrevious?: (...args: any[]) => any;
    onSearch?: (...args: any[]) => any;
    onSend?: (...args: any[]) => any;
  }): KeyboardActions;

export declare interface KeyboardOptions {}

export declare function KeyboardOptions(props: {
    capitalization?: any;
    autoCorrect?: boolean;
    keyboardType?: any;
    imeAction?: any;
    platformImeOptions?: any;
  }): KeyboardOptions;

export declare interface TextDelegate {}

export declare function TextDelegate(props: {
    text: any;
    style: any;
    maxLines?: number;
    minLines?: number;
    softWrap?: boolean;
    overflow?: any;
    density?: any;
    fontFamilyResolver?: any;
    placeholders?: Array<any>;
  }): TextDelegate;

export declare interface TextSelectionColors {}

export declare function TextSelectionColors(props: {
    handleColor: any;
    backgroundColor: any;
  }): TextSelectionColors;

export declare interface TextFieldBuffer {}

export declare function TextFieldBuffer(props: {
    initialValue: any;
    initialChanges?: any;
    sourceValue?: any;
  }): TextFieldBuffer;

export declare interface TextFieldState {}

export declare function TextFieldState(props: {
    initialText: string;
    initialSelectionInChars: any;
    initialTextUndoManager: any;
  }): TextFieldState;

export declare interface TextObfuscationMode {}

export declare function TextObfuscationMode(props: {
    value: number;
  }): TextObfuscationMode;

export declare interface UndoState {}

export declare function UndoState(props: {
    state: any;
  }): UndoState;

export declare const getDefaultLazyLayoutKey: any;

export declare const AndroidEmbeddedExternalSurface: any;

export declare const AndroidExternalSurface: any;

export declare const BasicTooltipBox: any;

export declare const Canvas: any;

export declare const Image: any;

export declare const LazyColumn: any;

export declare const LazyRow: any;

export declare const LazyHorizontalGrid: any;

export declare const LazyVerticalGrid: any;

export declare const LazyLayout: any;

export declare const LazyLayoutPinnableItem: any;

export declare const LazyHorizontalStaggeredGrid: any;

export declare const LazyVerticalStaggeredGrid: any;

export declare const HorizontalPager: any;

export declare const VerticalPager: any;

export declare const BasicTextField: any;

export declare const BasicText: any;

export declare const ClickableText: any;

export declare const DisableSelection: any;

export declare const SelectionContainer: any;

export declare const BasicSecureTextField: any;

export declare const BasicTextField2: any;
