// Generated by vesk-native from glide-compose.vsklib — do not edit by hand.
// Type surface for the `@vesk/glide-compose` virtual module (Glide Compose 1.0.0-beta01).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <GlideImage>.

export declare const GlideImage: any;
