// Generated by vesk-native from glide.vsklib — do not edit by hand.
// Type surface for the `@vesk/glide` virtual module (Glide 4.16.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface RequestOptions {}

/**

 * Per-request options (placeholder, error, size, transform). RequestOptions() with no chained builders.

 */

export declare function RequestOptions(): RequestOptions;

export declare const Glide: any;
