// Generated by vesk-native from gson.vsklib — do not edit by hand.
// Type surface for the `@vesk/gson` virtual module (Gson 2.11.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface Gson {}

/**

 * JSON (de)serializer. Gson().toJson(obj) serializes; fromJson(json, type) parses.

 */

export declare function Gson(): Gson;

export declare interface JsonParser {}

/**

 * Parses JSON text into a JsonElement tree. JsonParser().parse(text).

 */

export declare function JsonParser(): JsonParser;

export declare interface JsonObject {}

/**

 * Mutable JSON object node. JsonObject().addProperty(key, value) / get(key).

 */

export declare function JsonObject(): JsonObject;
