// Generated by vesk-native from icons-lucide.vsklib — do not edit by hand.
// Type surface for the `@vesk/icons-lucide` virtual module (Compose Icons — Lucide 2.2.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const Lucide: any;

export declare function AArrowDown(): any;

export declare function AArrowUp(): any;

export declare function ALargeSmall(): any;

export declare function Accessibility(): any;

export declare function Activity(): any;

export declare function AirVent(): any;

export declare function Airplay(): any;

export declare function AlarmClock(): any;

export declare function AlarmClockCheck(): any;

export declare function AlarmClockMinus(): any;

export declare function AlarmClockOff(): any;

export declare function AlarmClockPlus(): any;

export declare function AlarmSmoke(): any;

export declare function Album(): any;

export declare function AlignCenterHorizontal(): any;

export declare function AlignCenterVertical(): any;

export declare function AlignEndHorizontal(): any;

export declare function AlignEndVertical(): any;

export declare function AlignHorizontalDistributeCenter(): any;

export declare function AlignHorizontalDistributeEnd(): any;

export declare function AlignHorizontalDistributeStart(): any;

export declare function AlignHorizontalJustifyCenter(): any;

export declare function AlignHorizontalJustifyEnd(): any;

export declare function AlignHorizontalJustifyStart(): any;

export declare function AlignHorizontalSpaceAround(): any;

export declare function AlignHorizontalSpaceBetween(): any;

export declare function AlignStartHorizontal(): any;

export declare function AlignStartVertical(): any;

export declare function AlignVerticalDistributeCenter(): any;

export declare function AlignVerticalDistributeEnd(): any;

export declare function AlignVerticalDistributeStart(): any;

export declare function AlignVerticalJustifyCenter(): any;

export declare function AlignVerticalJustifyEnd(): any;

export declare function AlignVerticalJustifyStart(): any;

export declare function AlignVerticalSpaceAround(): any;

export declare function AlignVerticalSpaceBetween(): any;

export declare function Ambulance(): any;

export declare function Ampersand(): any;

export declare function Ampersands(): any;

export declare function Amphora(): any;

export declare function Anchor(): any;

export declare function Angry(): any;

export declare function Annoyed(): any;

export declare function Antenna(): any;

export declare function Anvil(): any;

export declare function Aperture(): any;

export declare function AppWindow(): any;

export declare function AppWindowMac(): any;

export declare function Apple(): any;

export declare function Archive(): any;

export declare function ArchiveRestore(): any;

export declare function ArchiveX(): any;

export declare function Armchair(): any;

export declare function ArrowBigDown(): any;

export declare function ArrowBigDownDash(): any;

export declare function ArrowBigLeft(): any;

export declare function ArrowBigLeftDash(): any;

export declare function ArrowBigRight(): any;

export declare function ArrowBigRightDash(): any;

export declare function ArrowBigUp(): any;

export declare function ArrowBigUpDash(): any;

export declare function ArrowDown(): any;

export declare function ArrowDown01(): any;

export declare function ArrowDown10(): any;

export declare function ArrowDownAZ(): any;

export declare function ArrowDownFromLine(): any;

export declare function ArrowDownLeft(): any;

export declare function ArrowDownNarrowWide(): any;

export declare function ArrowDownRight(): any;

export declare function ArrowDownToDot(): any;

export declare function ArrowDownToLine(): any;

export declare function ArrowDownUp(): any;

export declare function ArrowDownWideNarrow(): any;

export declare function ArrowDownZA(): any;

export declare function ArrowLeft(): any;

export declare function ArrowLeftFromLine(): any;

export declare function ArrowLeftRight(): any;

export declare function ArrowLeftToLine(): any;

export declare function ArrowRight(): any;

export declare function ArrowRightFromLine(): any;

export declare function ArrowRightLeft(): any;

export declare function ArrowRightToLine(): any;

export declare function ArrowUp(): any;

export declare function ArrowUp01(): any;

export declare function ArrowUp10(): any;

export declare function ArrowUpAZ(): any;

export declare function ArrowUpDown(): any;

export declare function ArrowUpFromDot(): any;

export declare function ArrowUpFromLine(): any;

export declare function ArrowUpLeft(): any;

export declare function ArrowUpNarrowWide(): any;

export declare function ArrowUpRight(): any;

export declare function ArrowUpToLine(): any;

export declare function ArrowUpWideNarrow(): any;

export declare function ArrowUpZA(): any;

export declare function ArrowsUpFromLine(): any;

export declare function Asterisk(): any;

export declare function AtSign(): any;

export declare function Atom(): any;

export declare function AudioLines(): any;

export declare function AudioWaveform(): any;

export declare function Award(): any;

export declare function Axe(): any;

export declare function Axis3d(): any;

export declare function Baby(): any;

export declare function Backpack(): any;

export declare function Badge(): any;

export declare function BadgeAlert(): any;

export declare function BadgeCent(): any;

export declare function BadgeCheck(): any;

export declare function BadgeDollarSign(): any;

export declare function BadgeEuro(): any;

export declare function BadgeIndianRupee(): any;

export declare function BadgeInfo(): any;

export declare function BadgeJapaneseYen(): any;

export declare function BadgeMinus(): any;

export declare function BadgePercent(): any;

export declare function BadgePlus(): any;

export declare function BadgePoundSterling(): any;

export declare function BadgeQuestionMark(): any;

export declare function BadgeRussianRuble(): any;

export declare function BadgeSwissFranc(): any;

export declare function BadgeTurkishLira(): any;

export declare function BadgeX(): any;

export declare function BaggageClaim(): any;

export declare function Balloon(): any;

export declare function Ban(): any;

export declare function Banana(): any;

export declare function Bandage(): any;

export declare function Banknote(): any;

export declare function BanknoteArrowDown(): any;

export declare function BanknoteArrowUp(): any;

export declare function BanknoteX(): any;

export declare function Barcode(): any;

export declare function Barrel(): any;

export declare function Baseline(): any;

export declare function Bath(): any;

export declare function Battery(): any;

export declare function BatteryCharging(): any;

export declare function BatteryFull(): any;

export declare function BatteryLow(): any;

export declare function BatteryMedium(): any;

export declare function BatteryPlus(): any;

export declare function BatteryWarning(): any;

export declare function Beaker(): any;

export declare function Bean(): any;

export declare function BeanOff(): any;

export declare function Bed(): any;

export declare function BedDouble(): any;

export declare function BedSingle(): any;

export declare function Beef(): any;

export declare function Beer(): any;

export declare function BeerOff(): any;

export declare function Bell(): any;

export declare function BellDot(): any;

export declare function BellElectric(): any;

export declare function BellMinus(): any;

export declare function BellOff(): any;

export declare function BellPlus(): any;

export declare function BellRing(): any;

export declare function BetweenHorizontalEnd(): any;

export declare function BetweenHorizontalStart(): any;

export declare function BetweenVerticalEnd(): any;

export declare function BetweenVerticalStart(): any;

export declare function BicepsFlexed(): any;

export declare function Bike(): any;

export declare function Binary(): any;

export declare function Binoculars(): any;

export declare function Biohazard(): any;

export declare function Bird(): any;

export declare function Birdhouse(): any;

export declare function Bitcoin(): any;

export declare function Blend(): any;

export declare function Blinds(): any;

export declare function Blocks(): any;

export declare function Bluetooth(): any;

export declare function BluetoothConnected(): any;

export declare function BluetoothOff(): any;

export declare function BluetoothSearching(): any;

export declare function Bold(): any;

export declare function Bolt(): any;

export declare function Bomb(): any;

export declare function Bone(): any;

export declare function Book(): any;

export declare function BookA(): any;

export declare function BookAlert(): any;

export declare function BookAudio(): any;

export declare function BookCheck(): any;

export declare function BookCopy(): any;

export declare function BookDashed(): any;

export declare function BookDown(): any;

export declare function BookHeadphones(): any;

export declare function BookHeart(): any;

export declare function BookImage(): any;

export declare function BookKey(): any;

export declare function BookLock(): any;

export declare function BookMarked(): any;

export declare function BookMinus(): any;

export declare function BookOpen(): any;

export declare function BookOpenCheck(): any;

export declare function BookOpenText(): any;

export declare function BookPlus(): any;

export declare function BookSearch(): any;

export declare function BookText(): any;

export declare function BookType(): any;

export declare function BookUp(): any;

export declare function BookUp2(): any;

export declare function BookUser(): any;

export declare function BookX(): any;

export declare function Bookmark(): any;

export declare function BookmarkCheck(): any;

export declare function BookmarkMinus(): any;

export declare function BookmarkPlus(): any;

export declare function BookmarkX(): any;

export declare function BoomBox(): any;

export declare function Bot(): any;

export declare function BotMessageSquare(): any;

export declare function BotOff(): any;

export declare function BottleWine(): any;

export declare function BowArrow(): any;

export declare function Box(): any;

export declare function Boxes(): any;

export declare function Braces(): any;

export declare function Brackets(): any;

export declare function Brain(): any;

export declare function BrainCircuit(): any;

export declare function BrainCog(): any;

export declare function BrickWall(): any;

export declare function BrickWallFire(): any;

export declare function BrickWallShield(): any;

export declare function Briefcase(): any;

export declare function BriefcaseBusiness(): any;

export declare function BriefcaseConveyorBelt(): any;

export declare function BriefcaseMedical(): any;

export declare function BringToFront(): any;

export declare function Brush(): any;

export declare function BrushCleaning(): any;

export declare function Bubbles(): any;

export declare function Bug(): any;

export declare function BugOff(): any;

export declare function BugPlay(): any;

export declare function Building(): any;

export declare function Building2(): any;

export declare function Bus(): any;

export declare function BusFront(): any;

export declare function Cable(): any;

export declare function CableCar(): any;

export declare function Cake(): any;

export declare function CakeSlice(): any;

export declare function Calculator(): any;

export declare function Calendar(): any;

export declare function Calendar1(): any;

export declare function CalendarArrowDown(): any;

export declare function CalendarArrowUp(): any;

export declare function CalendarCheck(): any;

export declare function CalendarCheck2(): any;

export declare function CalendarClock(): any;

export declare function CalendarCog(): any;

export declare function CalendarDays(): any;

export declare function CalendarFold(): any;

export declare function CalendarHeart(): any;

export declare function CalendarMinus(): any;

export declare function CalendarMinus2(): any;

export declare function CalendarOff(): any;

export declare function CalendarPlus(): any;

export declare function CalendarPlus2(): any;

export declare function CalendarRange(): any;

export declare function CalendarSearch(): any;

export declare function CalendarSync(): any;

export declare function CalendarX(): any;

export declare function CalendarX2(): any;

export declare function Calendars(): any;

export declare function Camera(): any;

export declare function CameraOff(): any;

export declare function Candy(): any;

export declare function CandyCane(): any;

export declare function CandyOff(): any;

export declare function Cannabis(): any;

export declare function CannabisOff(): any;

export declare function Captions(): any;

export declare function CaptionsOff(): any;

export declare function Car(): any;

export declare function CarFront(): any;

export declare function CarTaxiFront(): any;

export declare function Caravan(): any;

export declare function CardSim(): any;

export declare function Carrot(): any;

export declare function CaseLower(): any;

export declare function CaseSensitive(): any;

export declare function CaseUpper(): any;

export declare function CassetteTape(): any;

export declare function Cast(): any;

export declare function Castle(): any;

export declare function Cat(): any;

export declare function Cctv(): any;

export declare function ChartArea(): any;

export declare function ChartBar(): any;

export declare function ChartBarBig(): any;

export declare function ChartBarDecreasing(): any;

export declare function ChartBarIncreasing(): any;

export declare function ChartBarStacked(): any;

export declare function ChartCandlestick(): any;

export declare function ChartColumn(): any;

export declare function ChartColumnBig(): any;

export declare function ChartColumnDecreasing(): any;

export declare function ChartColumnIncreasing(): any;

export declare function ChartColumnStacked(): any;

export declare function ChartGantt(): any;

export declare function ChartLine(): any;

export declare function ChartNetwork(): any;

export declare function ChartNoAxesColumn(): any;

export declare function ChartNoAxesColumnDecreasing(): any;

export declare function ChartNoAxesColumnIncreasing(): any;

export declare function ChartNoAxesCombined(): any;

export declare function ChartNoAxesGantt(): any;

export declare function ChartPie(): any;

export declare function ChartScatter(): any;

export declare function ChartSpline(): any;

export declare function Check(): any;

export declare function CheckCheck(): any;

export declare function CheckLine(): any;

export declare function ChefHat(): any;

export declare function Cherry(): any;

export declare function ChessBishop(): any;

export declare function ChessKing(): any;

export declare function ChessKnight(): any;

export declare function ChessPawn(): any;

export declare function ChessQueen(): any;

export declare function ChessRook(): any;

export declare function ChevronDown(): any;

export declare function ChevronFirst(): any;

export declare function ChevronLast(): any;

export declare function ChevronLeft(): any;

export declare function ChevronRight(): any;

export declare function ChevronUp(): any;

export declare function ChevronsDown(): any;

export declare function ChevronsDownUp(): any;

export declare function ChevronsLeft(): any;

export declare function ChevronsLeftRight(): any;

export declare function ChevronsLeftRightEllipsis(): any;

export declare function ChevronsRight(): any;

export declare function ChevronsRightLeft(): any;

export declare function ChevronsUp(): any;

export declare function ChevronsUpDown(): any;

export declare function Chromium(): any;

export declare function Church(): any;

export declare function Cigarette(): any;

export declare function CigaretteOff(): any;

export declare function Circle(): any;

export declare function CircleAlert(): any;

export declare function CircleArrowDown(): any;

export declare function CircleArrowLeft(): any;

export declare function CircleArrowOutDownLeft(): any;

export declare function CircleArrowOutDownRight(): any;

export declare function CircleArrowOutUpLeft(): any;

export declare function CircleArrowOutUpRight(): any;

export declare function CircleArrowRight(): any;

export declare function CircleArrowUp(): any;

export declare function CircleCheck(): any;

export declare function CircleCheckBig(): any;

export declare function CircleChevronDown(): any;

export declare function CircleChevronLeft(): any;

export declare function CircleChevronRight(): any;

export declare function CircleChevronUp(): any;

export declare function CircleDashed(): any;

export declare function CircleDivide(): any;

export declare function CircleDollarSign(): any;

export declare function CircleDot(): any;

export declare function CircleDotDashed(): any;

export declare function CircleEllipsis(): any;

export declare function CircleEqual(): any;

export declare function CircleFadingArrowUp(): any;

export declare function CircleFadingPlus(): any;

export declare function CircleGauge(): any;

export declare function CircleMinus(): any;

export declare function CircleOff(): any;

export declare function CircleParking(): any;

export declare function CircleParkingOff(): any;

export declare function CirclePause(): any;

export declare function CirclePercent(): any;

export declare function CirclePile(): any;

export declare function CirclePlay(): any;

export declare function CirclePlus(): any;

export declare function CirclePoundSterling(): any;

export declare function CirclePower(): any;

export declare function CircleQuestionMark(): any;

export declare function CircleSlash(): any;

export declare function CircleSlash2(): any;

export declare function CircleSmall(): any;

export declare function CircleStar(): any;

export declare function CircleStop(): any;

export declare function CircleUser(): any;

export declare function CircleUserRound(): any;

export declare function CircleX(): any;

export declare function CircuitBoard(): any;

export declare function Citrus(): any;

export declare function Clapperboard(): any;

export declare function Clipboard(): any;

export declare function ClipboardCheck(): any;

export declare function ClipboardClock(): any;

export declare function ClipboardCopy(): any;

export declare function ClipboardList(): any;

export declare function ClipboardMinus(): any;

export declare function ClipboardPaste(): any;

export declare function ClipboardPen(): any;

export declare function ClipboardPenLine(): any;

export declare function ClipboardPlus(): any;

export declare function ClipboardType(): any;

export declare function ClipboardX(): any;

export declare function Clock(): any;

export declare function Clock10(): any;

export declare function Clock11(): any;

export declare function Clock12(): any;

export declare function Clock1(): any;

export declare function Clock2(): any;

export declare function Clock3(): any;

export declare function Clock4(): any;

export declare function Clock5(): any;

export declare function Clock6(): any;

export declare function Clock7(): any;

export declare function Clock8(): any;

export declare function Clock9(): any;

export declare function ClockAlert(): any;

export declare function ClockArrowDown(): any;

export declare function ClockArrowUp(): any;

export declare function ClockCheck(): any;

export declare function ClockFading(): any;

export declare function ClockPlus(): any;

export declare function ClosedCaption(): any;

export declare function Cloud(): any;

export declare function CloudAlert(): any;

export declare function CloudBackup(): any;

export declare function CloudCheck(): any;

export declare function CloudCog(): any;

export declare function CloudDownload(): any;

export declare function CloudDrizzle(): any;

export declare function CloudFog(): any;

export declare function CloudHail(): any;

export declare function CloudLightning(): any;

export declare function CloudMoon(): any;

export declare function CloudMoonRain(): any;

export declare function CloudOff(): any;

export declare function CloudRain(): any;

export declare function CloudRainWind(): any;

export declare function CloudSnow(): any;

export declare function CloudSun(): any;

export declare function CloudSunRain(): any;

export declare function CloudSync(): any;

export declare function CloudUpload(): any;

export declare function Cloudy(): any;

export declare function Clover(): any;

export declare function Club(): any;

export declare function Code(): any;

export declare function CodeXml(): any;

export declare function Codepen(): any;

export declare function Codesandbox(): any;

export declare function Coffee(): any;

export declare function Cog(): any;

export declare function Coins(): any;

export declare function Columns2(): any;

export declare function Columns3(): any;

export declare function Columns3Cog(): any;

export declare function Columns4(): any;

export declare function Combine(): any;

export declare function Command(): any;

export declare function Compass(): any;

export declare function Component(): any;

export declare function Computer(): any;

export declare function ConciergeBell(): any;

export declare function Cone(): any;

export declare function Construction(): any;

export declare function Contact(): any;

export declare function ContactRound(): any;

export declare function Container(): any;

export declare function Contrast(): any;

export declare function Cookie(): any;

export declare function CookingPot(): any;

export declare function Copy(): any;

export declare function CopyCheck(): any;

export declare function CopyMinus(): any;

export declare function CopyPlus(): any;

export declare function CopySlash(): any;

export declare function CopyX(): any;

export declare function Copyleft(): any;

export declare function Copyright(): any;

export declare function CornerDownLeft(): any;

export declare function CornerDownRight(): any;

export declare function CornerLeftDown(): any;

export declare function CornerLeftUp(): any;

export declare function CornerRightDown(): any;

export declare function CornerRightUp(): any;

export declare function CornerUpLeft(): any;

export declare function CornerUpRight(): any;

export declare function Cpu(): any;

export declare function CreativeCommons(): any;

export declare function CreditCard(): any;

export declare function Croissant(): any;

export declare function Crop(): any;

export declare function Cross(): any;

export declare function Crosshair(): any;

export declare function Crown(): any;

export declare function Cuboid(): any;

export declare function CupSoda(): any;

export declare function Currency(): any;

export declare function Cylinder(): any;

export declare function Dam(): any;

export declare function Database(): any;

export declare function DatabaseBackup(): any;

export declare function DatabaseZap(): any;

export declare function DecimalsArrowLeft(): any;

export declare function DecimalsArrowRight(): any;

export declare function Delete(): any;

export declare function Dessert(): any;

export declare function Diameter(): any;

export declare function Diamond(): any;

export declare function DiamondMinus(): any;

export declare function DiamondPercent(): any;

export declare function DiamondPlus(): any;

export declare function Dice1(): any;

export declare function Dice2(): any;

export declare function Dice3(): any;

export declare function Dice4(): any;

export declare function Dice5(): any;

export declare function Dice6(): any;

export declare function Dices(): any;

export declare function Diff(): any;

export declare function Disc(): any;

export declare function Disc2(): any;

export declare function Disc3(): any;

export declare function DiscAlbum(): any;

export declare function Divide(): any;

export declare function Dna(): any;

export declare function DnaOff(): any;

export declare function Dock(): any;

export declare function Dog(): any;

export declare function DollarSign(): any;

export declare function Donut(): any;

export declare function DoorClosed(): any;

export declare function DoorClosedLocked(): any;

export declare function DoorOpen(): any;

export declare function Dot(): any;

export declare function Download(): any;

export declare function DraftingCompass(): any;

export declare function Drama(): any;

export declare function Dribbble(): any;

export declare function Drill(): any;

export declare function Drone(): any;

export declare function Droplet(): any;

export declare function DropletOff(): any;

export declare function Droplets(): any;

export declare function Drum(): any;

export declare function Drumstick(): any;

export declare function Dumbbell(): any;

export declare function Ear(): any;

export declare function EarOff(): any;

export declare function Earth(): any;

export declare function EarthLock(): any;

export declare function Eclipse(): any;

export declare function Egg(): any;

export declare function EggFried(): any;

export declare function EggOff(): any;

export declare function Ellipsis(): any;

export declare function EllipsisVertical(): any;

export declare function Equal(): any;

export declare function EqualApproximately(): any;

export declare function EqualNot(): any;

export declare function Eraser(): any;

export declare function EthernetPort(): any;

export declare function Euro(): any;

export declare function EvCharger(): any;

export declare function Expand(): any;

export declare function ExternalLink(): any;

export declare function Eye(): any;

export declare function EyeClosed(): any;

export declare function EyeOff(): any;

export declare function Facebook(): any;

export declare function Factory(): any;

export declare function Fan(): any;

export declare function FastForward(): any;

export declare function Feather(): any;

export declare function Fence(): any;

export declare function FerrisWheel(): any;

export declare function Figma(): any;

export declare function File(): any;

export declare function FileArchive(): any;

export declare function FileAxis3d(): any;

export declare function FileBadge(): any;

export declare function FileBox(): any;

export declare function FileBraces(): any;

export declare function FileBracesCorner(): any;

export declare function FileChartColumn(): any;

export declare function FileChartColumnIncreasing(): any;

export declare function FileChartLine(): any;

export declare function FileChartPie(): any;

export declare function FileCheck(): any;

export declare function FileCheckCorner(): any;

export declare function FileClock(): any;

export declare function FileCode(): any;

export declare function FileCodeCorner(): any;

export declare function FileCog(): any;

export declare function FileDiff(): any;

export declare function FileDigit(): any;

export declare function FileDown(): any;

export declare function FileExclamationPoint(): any;

export declare function FileHeadphone(): any;

export declare function FileHeart(): any;

export declare function FileImage(): any;

export declare function FileInput(): any;

export declare function FileKey(): any;

export declare function FileLock(): any;

export declare function FileMinus(): any;

export declare function FileMinusCorner(): any;

export declare function FileMusic(): any;

export declare function FileOutput(): any;

export declare function FilePen(): any;

export declare function FilePenLine(): any;

export declare function FilePlay(): any;

export declare function FilePlus(): any;

export declare function FilePlusCorner(): any;

export declare function FileQuestionMark(): any;

export declare function FileScan(): any;

export declare function FileSearch(): any;

export declare function FileSearchCorner(): any;

export declare function FileSignal(): any;

export declare function FileSliders(): any;

export declare function FileSpreadsheet(): any;

export declare function FileStack(): any;

export declare function FileSymlink(): any;

export declare function FileTerminal(): any;

export declare function FileText(): any;

export declare function FileType(): any;

export declare function FileTypeCorner(): any;

export declare function FileUp(): any;

export declare function FileUser(): any;

export declare function FileVideoCamera(): any;

export declare function FileVolume(): any;

export declare function FileX(): any;

export declare function FileXCorner(): any;

export declare function Files(): any;

export declare function Film(): any;

export declare function FingerprintPattern(): any;

export declare function FireExtinguisher(): any;

export declare function Fish(): any;

export declare function FishOff(): any;

export declare function FishSymbol(): any;

export declare function FishingHook(): any;

export declare function Flag(): any;

export declare function FlagOff(): any;

export declare function FlagTriangleLeft(): any;

export declare function FlagTriangleRight(): any;

export declare function Flame(): any;

export declare function FlameKindling(): any;

export declare function Flashlight(): any;

export declare function FlashlightOff(): any;

export declare function FlaskConical(): any;

export declare function FlaskConicalOff(): any;

export declare function FlaskRound(): any;

export declare function FlipHorizontal(): any;

export declare function FlipHorizontal2(): any;

export declare function FlipVertical(): any;

export declare function FlipVertical2(): any;

export declare function Flower(): any;

export declare function Flower2(): any;

export declare function Focus(): any;

export declare function FoldHorizontal(): any;

export declare function FoldVertical(): any;

export declare function Folder(): any;

export declare function FolderArchive(): any;

export declare function FolderCheck(): any;

export declare function FolderClock(): any;

export declare function FolderClosed(): any;

export declare function FolderCode(): any;

export declare function FolderCog(): any;

export declare function FolderDot(): any;

export declare function FolderDown(): any;

export declare function FolderGit(): any;

export declare function FolderGit2(): any;

export declare function FolderHeart(): any;

export declare function FolderInput(): any;

export declare function FolderKanban(): any;

export declare function FolderKey(): any;

export declare function FolderLock(): any;

export declare function FolderMinus(): any;

export declare function FolderOpen(): any;

export declare function FolderOpenDot(): any;

export declare function FolderOutput(): any;

export declare function FolderPen(): any;

export declare function FolderPlus(): any;

export declare function FolderRoot(): any;

export declare function FolderSearch(): any;

export declare function FolderSearch2(): any;

export declare function FolderSymlink(): any;

export declare function FolderSync(): any;

export declare function FolderTree(): any;

export declare function FolderUp(): any;

export declare function FolderX(): any;

export declare function Folders(): any;

export declare function Footprints(): any;

export declare function Forklift(): any;

export declare function Form(): any;

export declare function Forward(): any;

export declare function Frame(): any;

export declare function Framer(): any;

export declare function Frown(): any;

export declare function Fuel(): any;

export declare function Fullscreen(): any;

export declare function Funnel(): any;

export declare function FunnelPlus(): any;

export declare function FunnelX(): any;

export declare function GalleryHorizontal(): any;

export declare function GalleryHorizontalEnd(): any;

export declare function GalleryThumbnails(): any;

export declare function GalleryVertical(): any;

export declare function GalleryVerticalEnd(): any;

export declare function Gamepad(): any;

export declare function Gamepad2(): any;

export declare function GamepadDirectional(): any;

export declare function Gauge(): any;

export declare function Gavel(): any;

export declare function Gem(): any;

export declare function GeorgianLari(): any;

export declare function Ghost(): any;

export declare function Gift(): any;

export declare function GitBranch(): any;

export declare function GitBranchMinus(): any;

export declare function GitBranchPlus(): any;

export declare function GitCommitHorizontal(): any;

export declare function GitCommitVertical(): any;

export declare function GitCompare(): any;

export declare function GitCompareArrows(): any;

export declare function GitFork(): any;

export declare function GitGraph(): any;

export declare function GitMerge(): any;

export declare function GitPullRequest(): any;

export declare function GitPullRequestArrow(): any;

export declare function GitPullRequestClosed(): any;

export declare function GitPullRequestCreate(): any;

export declare function GitPullRequestCreateArrow(): any;

export declare function GitPullRequestDraft(): any;

export declare function Github(): any;

export declare function Gitlab(): any;

export declare function GlassWater(): any;

export declare function Glasses(): any;

export declare function Globe(): any;

export declare function GlobeLock(): any;

export declare function Goal(): any;

export declare function Gpu(): any;

export declare function GraduationCap(): any;

export declare function Grape(): any;

export declare function Grid2x2(): any;

export declare function Grid2x2Check(): any;

export declare function Grid2x2Plus(): any;

export declare function Grid2x2X(): any;

export declare function Grid3x2(): any;

export declare function Grid3x3(): any;

export declare function Grip(): any;

export declare function GripHorizontal(): any;

export declare function GripVertical(): any;

export declare function Group(): any;

export declare function Guitar(): any;

export declare function Ham(): any;

export declare function Hamburger(): any;

export declare function Hammer(): any;

export declare function Hand(): any;

export declare function HandCoins(): any;

export declare function HandFist(): any;

export declare function HandGrab(): any;

export declare function HandHeart(): any;

export declare function HandHelping(): any;

export declare function HandMetal(): any;

export declare function HandPlatter(): any;

export declare function Handbag(): any;

export declare function Handshake(): any;

export declare function HardDrive(): any;

export declare function HardDriveDownload(): any;

export declare function HardDriveUpload(): any;

export declare function HardHat(): any;

export declare function Hash(): any;

export declare function HatGlasses(): any;

export declare function Haze(): any;

export declare function Hd(): any;

export declare function HdmiPort(): any;

export declare function Heading(): any;

export declare function Heading1(): any;

export declare function Heading2(): any;

export declare function Heading3(): any;

export declare function Heading4(): any;

export declare function Heading5(): any;

export declare function Heading6(): any;

export declare function HeadphoneOff(): any;

export declare function Headphones(): any;

export declare function Headset(): any;

export declare function Heart(): any;

export declare function HeartCrack(): any;

export declare function HeartHandshake(): any;

export declare function HeartMinus(): any;

export declare function HeartOff(): any;

export declare function HeartPlus(): any;

export declare function HeartPulse(): any;

export declare function Heater(): any;

export declare function Helicopter(): any;

export declare function Hexagon(): any;

export declare function Highlighter(): any;

export declare function History(): any;

export declare function Hop(): any;

export declare function HopOff(): any;

export declare function Hospital(): any;

export declare function Hotel(): any;

export declare function Hourglass(): any;

export declare function House(): any;

export declare function HouseHeart(): any;

export declare function HousePlug(): any;

export declare function HousePlus(): any;

export declare function HouseWifi(): any;

export declare function IceCreamBowl(): any;

export declare function IceCreamCone(): any;

export declare function IdCard(): any;

export declare function IdCardLanyard(): any;

export declare function Image(): any;

export declare function ImageDown(): any;

export declare function ImageMinus(): any;

export declare function ImageOff(): any;

export declare function ImagePlay(): any;

export declare function ImagePlus(): any;

export declare function ImageUp(): any;

export declare function ImageUpscale(): any;

export declare function Images(): any;

export declare function Import(): any;

export declare function Inbox(): any;

export declare function IndianRupee(): any;

export declare function Infinity(): any;

export declare function Info(): any;

export declare function InspectionPanel(): any;

export declare function Instagram(): any;

export declare function Italic(): any;

export declare function IterationCcw(): any;

export declare function IterationCw(): any;

export declare function JapaneseYen(): any;

export declare function Joystick(): any;

export declare function Kanban(): any;

export declare function Kayak(): any;

export declare function Key(): any;

export declare function KeyRound(): any;

export declare function KeySquare(): any;

export declare function Keyboard(): any;

export declare function KeyboardMusic(): any;

export declare function KeyboardOff(): any;

export declare function Lamp(): any;

export declare function LampCeiling(): any;

export declare function LampDesk(): any;

export declare function LampFloor(): any;

export declare function LampWallDown(): any;

export declare function LampWallUp(): any;

export declare function LandPlot(): any;

export declare function Landmark(): any;

export declare function Languages(): any;

export declare function Laptop(): any;

export declare function LaptopMinimal(): any;

export declare function LaptopMinimalCheck(): any;

export declare function Lasso(): any;

export declare function LassoSelect(): any;

export declare function Laugh(): any;

export declare function Layers(): any;

export declare function Layers2(): any;

export declare function LayersPlus(): any;

export declare function LayoutDashboard(): any;

export declare function LayoutGrid(): any;

export declare function LayoutList(): any;

export declare function LayoutPanelLeft(): any;

export declare function LayoutPanelTop(): any;

export declare function LayoutTemplate(): any;

export declare function Leaf(): any;

export declare function LeafyGreen(): any;

export declare function Lectern(): any;

export declare function Library(): any;

export declare function LibraryBig(): any;

export declare function LifeBuoy(): any;

export declare function Ligature(): any;

export declare function Lightbulb(): any;

export declare function LightbulbOff(): any;

export declare function LineSquiggle(): any;

export declare function Link(): any;

export declare function Link2(): any;

export declare function Link2Off(): any;

export declare function Linkedin(): any;

export declare function List(): any;

export declare function ListCheck(): any;

export declare function ListChecks(): any;

export declare function ListChevronsDownUp(): any;

export declare function ListChevronsUpDown(): any;

export declare function ListCollapse(): any;

export declare function ListEnd(): any;

export declare function ListFilter(): any;

export declare function ListFilterPlus(): any;

export declare function ListIndentDecrease(): any;

export declare function ListIndentIncrease(): any;

export declare function ListMinus(): any;

export declare function ListMusic(): any;

export declare function ListOrdered(): any;

export declare function ListPlus(): any;

export declare function ListRestart(): any;

export declare function ListStart(): any;

export declare function ListTodo(): any;

export declare function ListTree(): any;

export declare function ListVideo(): any;

export declare function ListX(): any;

export declare function Loader(): any;

export declare function LoaderCircle(): any;

export declare function LoaderPinwheel(): any;

export declare function Locate(): any;

export declare function LocateFixed(): any;

export declare function LocateOff(): any;

export declare function Lock(): any;

export declare function LockKeyhole(): any;

export declare function LockKeyholeOpen(): any;

export declare function LockOpen(): any;

export declare function LogIn(): any;

export declare function LogOut(): any;

export declare function Logs(): any;

export declare function Lollipop(): any;

export declare function Luggage(): any;

export declare function Magnet(): any;

export declare function Mail(): any;

export declare function MailCheck(): any;

export declare function MailMinus(): any;

export declare function MailOpen(): any;

export declare function MailPlus(): any;

export declare function MailQuestionMark(): any;

export declare function MailSearch(): any;

export declare function MailWarning(): any;

export declare function MailX(): any;

export declare function Mailbox(): any;

export declare function Mails(): any;

export declare function Map(): any;

export declare function MapMinus(): any;

export declare function MapPin(): any;

export declare function MapPinCheck(): any;

export declare function MapPinCheckInside(): any;

export declare function MapPinHouse(): any;

export declare function MapPinMinus(): any;

export declare function MapPinMinusInside(): any;

export declare function MapPinOff(): any;

export declare function MapPinPen(): any;

export declare function MapPinPlus(): any;

export declare function MapPinPlusInside(): any;

export declare function MapPinX(): any;

export declare function MapPinXInside(): any;

export declare function MapPinned(): any;

export declare function MapPlus(): any;

export declare function Mars(): any;

export declare function MarsStroke(): any;

export declare function Martini(): any;

export declare function Maximize(): any;

export declare function Maximize2(): any;

export declare function Medal(): any;

export declare function Megaphone(): any;

export declare function MegaphoneOff(): any;

export declare function Meh(): any;

export declare function MemoryStick(): any;

export declare function Menu(): any;

export declare function Merge(): any;

export declare function MessageCircle(): any;

export declare function MessageCircleCode(): any;

export declare function MessageCircleDashed(): any;

export declare function MessageCircleHeart(): any;

export declare function MessageCircleMore(): any;

export declare function MessageCircleOff(): any;

export declare function MessageCirclePlus(): any;

export declare function MessageCircleQuestionMark(): any;

export declare function MessageCircleReply(): any;

export declare function MessageCircleWarning(): any;

export declare function MessageCircleX(): any;

export declare function MessageSquare(): any;

export declare function MessageSquareCode(): any;

export declare function MessageSquareDashed(): any;

export declare function MessageSquareDiff(): any;

export declare function MessageSquareDot(): any;

export declare function MessageSquareHeart(): any;

export declare function MessageSquareLock(): any;

export declare function MessageSquareMore(): any;

export declare function MessageSquareOff(): any;

export declare function MessageSquarePlus(): any;

export declare function MessageSquareQuote(): any;

export declare function MessageSquareReply(): any;

export declare function MessageSquareShare(): any;

export declare function MessageSquareText(): any;

export declare function MessageSquareWarning(): any;

export declare function MessageSquareX(): any;

export declare function MessagesSquare(): any;

export declare function Mic(): any;

export declare function MicOff(): any;

export declare function MicVocal(): any;

export declare function Microchip(): any;

export declare function Microscope(): any;

export declare function Microwave(): any;

export declare function Milestone(): any;

export declare function Milk(): any;

export declare function MilkOff(): any;

export declare function Minimize(): any;

export declare function Minimize2(): any;

export declare function Minus(): any;

export declare function Monitor(): any;

export declare function MonitorCheck(): any;

export declare function MonitorCloud(): any;

export declare function MonitorCog(): any;

export declare function MonitorDot(): any;

export declare function MonitorDown(): any;

export declare function MonitorOff(): any;

export declare function MonitorPause(): any;

export declare function MonitorPlay(): any;

export declare function MonitorSmartphone(): any;

export declare function MonitorSpeaker(): any;

export declare function MonitorStop(): any;

export declare function MonitorUp(): any;

export declare function MonitorX(): any;

export declare function Moon(): any;

export declare function MoonStar(): any;

export declare function Motorbike(): any;

export declare function Mountain(): any;

export declare function MountainSnow(): any;

export declare function Mouse(): any;

export declare function MouseOff(): any;

export declare function MousePointer(): any;

export declare function MousePointer2(): any;

export declare function MousePointer2Off(): any;

export declare function MousePointerBan(): any;

export declare function MousePointerClick(): any;

export declare function Move(): any;

export declare function Move3d(): any;

export declare function MoveDiagonal(): any;

export declare function MoveDiagonal2(): any;

export declare function MoveDown(): any;

export declare function MoveDownLeft(): any;

export declare function MoveDownRight(): any;

export declare function MoveHorizontal(): any;

export declare function MoveLeft(): any;

export declare function MoveRight(): any;

export declare function MoveUp(): any;

export declare function MoveUpLeft(): any;

export declare function MoveUpRight(): any;

export declare function MoveVertical(): any;

export declare function Music(): any;

export declare function Music2(): any;

export declare function Music3(): any;

export declare function Music4(): any;

export declare function Navigation(): any;

export declare function Navigation2(): any;

export declare function Navigation2Off(): any;

export declare function NavigationOff(): any;

export declare function Network(): any;

export declare function Newspaper(): any;

export declare function Nfc(): any;

export declare function NonBinary(): any;

export declare function Notebook(): any;

export declare function NotebookPen(): any;

export declare function NotebookTabs(): any;

export declare function NotebookText(): any;

export declare function NotepadText(): any;

export declare function NotepadTextDashed(): any;

export declare function Nut(): any;

export declare function NutOff(): any;

export declare function Octagon(): any;

export declare function OctagonAlert(): any;

export declare function OctagonMinus(): any;

export declare function OctagonPause(): any;

export declare function OctagonX(): any;

export declare function Omega(): any;

export declare function Option(): any;

export declare function Orbit(): any;

export declare function Origami(): any;

export declare function Package(): any;

export declare function Package2(): any;

export declare function PackageCheck(): any;

export declare function PackageMinus(): any;

export declare function PackageOpen(): any;

export declare function PackagePlus(): any;

export declare function PackageSearch(): any;

export declare function PackageX(): any;

export declare function PaintBucket(): any;

export declare function PaintRoller(): any;

export declare function Paintbrush(): any;

export declare function PaintbrushVertical(): any;

export declare function Palette(): any;

export declare function Panda(): any;

export declare function PanelBottom(): any;

export declare function PanelBottomClose(): any;

export declare function PanelBottomDashed(): any;

export declare function PanelBottomOpen(): any;

export declare function PanelLeft(): any;

export declare function PanelLeftClose(): any;

export declare function PanelLeftDashed(): any;

export declare function PanelLeftOpen(): any;

export declare function PanelLeftRightDashed(): any;

export declare function PanelRight(): any;

export declare function PanelRightClose(): any;

export declare function PanelRightDashed(): any;

export declare function PanelRightOpen(): any;

export declare function PanelTop(): any;

export declare function PanelTopBottomDashed(): any;

export declare function PanelTopClose(): any;

export declare function PanelTopDashed(): any;

export declare function PanelTopOpen(): any;

export declare function PanelsLeftBottom(): any;

export declare function PanelsRightBottom(): any;

export declare function PanelsTopLeft(): any;

export declare function Paperclip(): any;

export declare function Parentheses(): any;

export declare function ParkingMeter(): any;

export declare function PartyPopper(): any;

export declare function Pause(): any;

export declare function PawPrint(): any;

export declare function PcCase(): any;

export declare function Pen(): any;

export declare function PenLine(): any;

export declare function PenOff(): any;

export declare function PenTool(): any;

export declare function Pencil(): any;

export declare function PencilLine(): any;

export declare function PencilOff(): any;

export declare function PencilRuler(): any;

export declare function Pentagon(): any;

export declare function Percent(): any;

export declare function PersonStanding(): any;

export declare function PhilippinePeso(): any;

export declare function Phone(): any;

export declare function PhoneCall(): any;

export declare function PhoneForwarded(): any;

export declare function PhoneIncoming(): any;

export declare function PhoneMissed(): any;

export declare function PhoneOff(): any;

export declare function PhoneOutgoing(): any;

export declare function Pi(): any;

export declare function Piano(): any;

export declare function Pickaxe(): any;

export declare function PictureInPicture(): any;

export declare function PictureInPicture2(): any;

export declare function PiggyBank(): any;

export declare function Pilcrow(): any;

export declare function PilcrowLeft(): any;

export declare function PilcrowRight(): any;

export declare function Pill(): any;

export declare function PillBottle(): any;

export declare function Pin(): any;

export declare function PinOff(): any;

export declare function Pipette(): any;

export declare function Pizza(): any;

export declare function Plane(): any;

export declare function PlaneLanding(): any;

export declare function PlaneTakeoff(): any;

export declare function Play(): any;

export declare function Plug(): any;

export declare function Plug2(): any;

export declare function PlugZap(): any;

export declare function Plus(): any;

export declare function Pocket(): any;

export declare function PocketKnife(): any;

export declare function Podcast(): any;

export declare function Pointer(): any;

export declare function PointerOff(): any;

export declare function Popcorn(): any;

export declare function Popsicle(): any;

export declare function PoundSterling(): any;

export declare function Power(): any;

export declare function PowerOff(): any;

export declare function Presentation(): any;

export declare function Printer(): any;

export declare function PrinterCheck(): any;

export declare function Projector(): any;

export declare function Proportions(): any;

export declare function Puzzle(): any;

export declare function Pyramid(): any;

export declare function QrCode(): any;

export declare function Quote(): any;

export declare function Rabbit(): any;

export declare function Radar(): any;

export declare function Radiation(): any;

export declare function Radical(): any;

export declare function Radio(): any;

export declare function RadioReceiver(): any;

export declare function RadioTower(): any;

export declare function Radius(): any;

export declare function RailSymbol(): any;

export declare function Rainbow(): any;

export declare function Rat(): any;

export declare function Ratio(): any;

export declare function Receipt(): any;

export declare function ReceiptCent(): any;

export declare function ReceiptEuro(): any;

export declare function ReceiptIndianRupee(): any;

export declare function ReceiptJapaneseYen(): any;

export declare function ReceiptPoundSterling(): any;

export declare function ReceiptRussianRuble(): any;

export declare function ReceiptSwissFranc(): any;

export declare function ReceiptText(): any;

export declare function ReceiptTurkishLira(): any;

export declare function RectangleCircle(): any;

export declare function RectangleEllipsis(): any;

export declare function RectangleGoggles(): any;

export declare function RectangleHorizontal(): any;

export declare function RectangleVertical(): any;

export declare function Recycle(): any;

export declare function Redo(): any;

export declare function Redo2(): any;

export declare function RedoDot(): any;

export declare function RefreshCcw(): any;

export declare function RefreshCcwDot(): any;

export declare function RefreshCw(): any;

export declare function RefreshCwOff(): any;

export declare function Refrigerator(): any;

export declare function Regex(): any;

export declare function RemoveFormatting(): any;

export declare function Repeat(): any;

export declare function Repeat1(): any;

export declare function Repeat2(): any;

export declare function Replace(): any;

export declare function ReplaceAll(): any;

export declare function Reply(): any;

export declare function ReplyAll(): any;

export declare function Rewind(): any;

export declare function Ribbon(): any;

export declare function Rocket(): any;

export declare function RockingChair(): any;

export declare function RollerCoaster(): any;

export declare function Rose(): any;

export declare function Rotate3d(): any;

export declare function RotateCcw(): any;

export declare function RotateCcwKey(): any;

export declare function RotateCcwSquare(): any;

export declare function RotateCw(): any;

export declare function RotateCwSquare(): any;

export declare function Route(): any;

export declare function RouteOff(): any;

export declare function Router(): any;

export declare function Rows2(): any;

export declare function Rows3(): any;

export declare function Rows4(): any;

export declare function Rss(): any;

export declare function Ruler(): any;

export declare function RulerDimensionLine(): any;

export declare function RussianRuble(): any;

export declare function Sailboat(): any;

export declare function Salad(): any;

export declare function Sandwich(): any;

export declare function Satellite(): any;

export declare function SatelliteDish(): any;

export declare function SaudiRiyal(): any;

export declare function Save(): any;

export declare function SaveAll(): any;

export declare function SaveOff(): any;

export declare function Scale(): any;

export declare function Scale3d(): any;

export declare function Scaling(): any;

export declare function Scan(): any;

export declare function ScanBarcode(): any;

export declare function ScanEye(): any;

export declare function ScanFace(): any;

export declare function ScanHeart(): any;

export declare function ScanLine(): any;

export declare function ScanQrCode(): any;

export declare function ScanSearch(): any;

export declare function ScanText(): any;

export declare function School(): any;

export declare function Scissors(): any;

export declare function ScissorsLineDashed(): any;

export declare function Scooter(): any;

export declare function ScreenShare(): any;

export declare function ScreenShareOff(): any;

export declare function Scroll(): any;

export declare function ScrollText(): any;

export declare function Search(): any;

export declare function SearchAlert(): any;

export declare function SearchCheck(): any;

export declare function SearchCode(): any;

export declare function SearchSlash(): any;

export declare function SearchX(): any;

export declare function Section(): any;

export declare function Send(): any;

export declare function SendHorizontal(): any;

export declare function SendToBack(): any;

export declare function SeparatorHorizontal(): any;

export declare function SeparatorVertical(): any;

export declare function Server(): any;

export declare function ServerCog(): any;

export declare function ServerCrash(): any;

export declare function ServerOff(): any;

export declare function Settings(): any;

export declare function Settings2(): any;

export declare function Shapes(): any;

export declare function Share(): any;

export declare function Share2(): any;

export declare function Sheet(): any;

export declare function Shell(): any;

export declare function Shield(): any;

export declare function ShieldAlert(): any;

export declare function ShieldBan(): any;

export declare function ShieldCheck(): any;

export declare function ShieldEllipsis(): any;

export declare function ShieldHalf(): any;

export declare function ShieldMinus(): any;

export declare function ShieldOff(): any;

export declare function ShieldPlus(): any;

export declare function ShieldQuestionMark(): any;

export declare function ShieldUser(): any;

export declare function ShieldX(): any;

export declare function Ship(): any;

export declare function ShipWheel(): any;

export declare function Shirt(): any;

export declare function ShoppingBag(): any;

export declare function ShoppingBasket(): any;

export declare function ShoppingCart(): any;

export declare function Shovel(): any;

export declare function ShowerHead(): any;

export declare function Shredder(): any;

export declare function Shrimp(): any;

export declare function Shrink(): any;

export declare function Shrub(): any;

export declare function Shuffle(): any;

export declare function Sigma(): any;

export declare function Signal(): any;

export declare function SignalHigh(): any;

export declare function SignalLow(): any;

export declare function SignalMedium(): any;

export declare function SignalZero(): any;

export declare function Signature(): any;

export declare function Signpost(): any;

export declare function SignpostBig(): any;

export declare function Siren(): any;

export declare function SkipBack(): any;

export declare function SkipForward(): any;

export declare function Skull(): any;

export declare function Slack(): any;

export declare function Slash(): any;

export declare function Slice(): any;

export declare function SlidersHorizontal(): any;

export declare function SlidersVertical(): any;

export declare function Smartphone(): any;

export declare function SmartphoneCharging(): any;

export declare function SmartphoneNfc(): any;

export declare function Smile(): any;

export declare function SmilePlus(): any;

export declare function Snail(): any;

export declare function Snowflake(): any;

export declare function SoapDispenserDroplet(): any;

export declare function Sofa(): any;

export declare function SolarPanel(): any;

export declare function Soup(): any;

export declare function Space(): any;

export declare function Spade(): any;

export declare function Sparkle(): any;

export declare function Sparkles(): any;

export declare function Speaker(): any;

export declare function Speech(): any;

export declare function SpellCheck(): any;

export declare function SpellCheck2(): any;

export declare function Spline(): any;

export declare function SplinePointer(): any;

export declare function Split(): any;

export declare function Spool(): any;

export declare function Spotlight(): any;

export declare function SprayCan(): any;

export declare function Sprout(): any;

export declare function Square(): any;

export declare function SquareActivity(): any;

export declare function SquareArrowDown(): any;

export declare function SquareArrowDownLeft(): any;

export declare function SquareArrowDownRight(): any;

export declare function SquareArrowLeft(): any;

export declare function SquareArrowOutDownLeft(): any;

export declare function SquareArrowOutDownRight(): any;

export declare function SquareArrowOutUpLeft(): any;

export declare function SquareArrowOutUpRight(): any;

export declare function SquareArrowRight(): any;

export declare function SquareArrowUp(): any;

export declare function SquareArrowUpLeft(): any;

export declare function SquareArrowUpRight(): any;

export declare function SquareAsterisk(): any;

export declare function SquareBottomDashedScissors(): any;

export declare function SquareChartGantt(): any;

export declare function SquareCheck(): any;

export declare function SquareCheckBig(): any;

export declare function SquareChevronDown(): any;

export declare function SquareChevronLeft(): any;

export declare function SquareChevronRight(): any;

export declare function SquareChevronUp(): any;

export declare function SquareCode(): any;

export declare function SquareDashed(): any;

export declare function SquareDashedBottom(): any;

export declare function SquareDashedBottomCode(): any;

export declare function SquareDashedKanban(): any;

export declare function SquareDashedMousePointer(): any;

export declare function SquareDashedTopSolid(): any;

export declare function SquareDivide(): any;

export declare function SquareDot(): any;

export declare function SquareEqual(): any;

export declare function SquareFunction(): any;

export declare function SquareKanban(): any;

export declare function SquareLibrary(): any;

export declare function SquareM(): any;

export declare function SquareMenu(): any;

export declare function SquareMinus(): any;

export declare function SquareMousePointer(): any;

export declare function SquareParking(): any;

export declare function SquareParkingOff(): any;

export declare function SquarePause(): any;

export declare function SquarePen(): any;

export declare function SquarePercent(): any;

export declare function SquarePi(): any;

export declare function SquarePilcrow(): any;

export declare function SquarePlay(): any;

export declare function SquarePlus(): any;

export declare function SquarePower(): any;

export declare function SquareRadical(): any;

export declare function SquareRoundCorner(): any;

export declare function SquareScissors(): any;

export declare function SquareSigma(): any;

export declare function SquareSlash(): any;

export declare function SquareSplitHorizontal(): any;

export declare function SquareSplitVertical(): any;

export declare function SquareSquare(): any;

export declare function SquareStack(): any;

export declare function SquareStar(): any;

export declare function SquareStop(): any;

export declare function SquareTerminal(): any;

export declare function SquareUser(): any;

export declare function SquareUserRound(): any;

export declare function SquareX(): any;

export declare function SquaresExclude(): any;

export declare function SquaresIntersect(): any;

export declare function SquaresSubtract(): any;

export declare function SquaresUnite(): any;

export declare function Squircle(): any;

export declare function SquircleDashed(): any;

export declare function Squirrel(): any;

export declare function Stamp(): any;

export declare function Star(): any;

export declare function StarHalf(): any;

export declare function StarOff(): any;

export declare function StepBack(): any;

export declare function StepForward(): any;

export declare function Stethoscope(): any;

export declare function Sticker(): any;

export declare function StickyNote(): any;

export declare function Stone(): any;

export declare function Store(): any;

export declare function StretchHorizontal(): any;

export declare function StretchVertical(): any;

export declare function Strikethrough(): any;

export declare function Subscript(): any;

export declare function Sun(): any;

export declare function SunDim(): any;

export declare function SunMedium(): any;

export declare function SunMoon(): any;

export declare function SunSnow(): any;

export declare function Sunrise(): any;

export declare function Sunset(): any;

export declare function Superscript(): any;

export declare function SwatchBook(): any;

export declare function SwissFranc(): any;

export declare function SwitchCamera(): any;

export declare function Sword(): any;

export declare function Swords(): any;

export declare function Syringe(): any;

export declare function Table(): any;

export declare function Table2(): any;

export declare function TableCellsMerge(): any;

export declare function TableCellsSplit(): any;

export declare function TableColumnsSplit(): any;

export declare function TableOfContents(): any;

export declare function TableProperties(): any;

export declare function TableRowsSplit(): any;

export declare function Tablet(): any;

export declare function TabletSmartphone(): any;

export declare function Tablets(): any;

export declare function Tag(): any;

export declare function Tags(): any;

export declare function Tally1(): any;

export declare function Tally2(): any;

export declare function Tally3(): any;

export declare function Tally4(): any;

export declare function Tally5(): any;

export declare function Tangent(): any;

export declare function Target(): any;

export declare function Telescope(): any;

export declare function Tent(): any;

export declare function TentTree(): any;

export declare function Terminal(): any;

export declare function TestTube(): any;

export declare function TestTubeDiagonal(): any;

export declare function TestTubes(): any;

export declare function TextAlignCenter(): any;

export declare function TextAlignEnd(): any;

export declare function TextAlignJustify(): any;

export declare function TextAlignStart(): any;

export declare function TextCursor(): any;

export declare function TextCursorInput(): any;

export declare function TextInitial(): any;

export declare function TextQuote(): any;

export declare function TextSearch(): any;

export declare function TextSelect(): any;

export declare function TextWrap(): any;

export declare function Theater(): any;

export declare function Thermometer(): any;

export declare function ThermometerSnowflake(): any;

export declare function ThermometerSun(): any;

export declare function ThumbsDown(): any;

export declare function ThumbsUp(): any;

export declare function Ticket(): any;

export declare function TicketCheck(): any;

export declare function TicketMinus(): any;

export declare function TicketPercent(): any;

export declare function TicketPlus(): any;

export declare function TicketSlash(): any;

export declare function TicketX(): any;

export declare function Tickets(): any;

export declare function TicketsPlane(): any;

export declare function Timer(): any;

export declare function TimerOff(): any;

export declare function TimerReset(): any;

export declare function ToggleLeft(): any;

export declare function ToggleRight(): any;

export declare function Toilet(): any;

export declare function ToolCase(): any;

export declare function Tornado(): any;

export declare function Torus(): any;

export declare function Touchpad(): any;

export declare function TouchpadOff(): any;

export declare function TowerControl(): any;

export declare function ToyBrick(): any;

export declare function Tractor(): any;

export declare function TrafficCone(): any;

export declare function TrainFront(): any;

export declare function TrainFrontTunnel(): any;

export declare function TrainTrack(): any;

export declare function TramFront(): any;

export declare function Transgender(): any;

export declare function Trash(): any;

export declare function Trash2(): any;

export declare function TreeDeciduous(): any;

export declare function TreePalm(): any;

export declare function TreePine(): any;

export declare function Trees(): any;

export declare function Trello(): any;

export declare function TrendingDown(): any;

export declare function TrendingUp(): any;

export declare function TrendingUpDown(): any;

export declare function Triangle(): any;

export declare function TriangleAlert(): any;

export declare function TriangleDashed(): any;

export declare function TriangleRight(): any;

export declare function Trophy(): any;

export declare function Truck(): any;

export declare function TruckElectric(): any;

export declare function TurkishLira(): any;

export declare function Turntable(): any;

export declare function Turtle(): any;

export declare function Tv(): any;

export declare function TvMinimal(): any;

export declare function TvMinimalPlay(): any;

export declare function Twitch(): any;

export declare function Twitter(): any;

export declare function Type(): any;

export declare function TypeOutline(): any;

export declare function Umbrella(): any;

export declare function UmbrellaOff(): any;

export declare function Underline(): any;

export declare function Undo(): any;

export declare function Undo2(): any;

export declare function UndoDot(): any;

export declare function UnfoldHorizontal(): any;

export declare function UnfoldVertical(): any;

export declare function Ungroup(): any;

export declare function University(): any;

export declare function Unlink(): any;

export declare function Unlink2(): any;

export declare function Unplug(): any;

export declare function Upload(): any;

export declare function Usb(): any;

export declare function User(): any;

export declare function UserCheck(): any;

export declare function UserCog(): any;

export declare function UserLock(): any;

export declare function UserMinus(): any;

export declare function UserPen(): any;

export declare function UserPlus(): any;

export declare function UserRound(): any;

export declare function UserRoundCheck(): any;

export declare function UserRoundCog(): any;

export declare function UserRoundMinus(): any;

export declare function UserRoundPen(): any;

export declare function UserRoundPlus(): any;

export declare function UserRoundSearch(): any;

export declare function UserRoundX(): any;

export declare function UserSearch(): any;

export declare function UserStar(): any;

export declare function UserX(): any;

export declare function Users(): any;

export declare function UsersRound(): any;

export declare function Utensils(): any;

export declare function UtensilsCrossed(): any;

export declare function UtilityPole(): any;

export declare function Van(): any;

export declare function Variable(): any;

export declare function Vault(): any;

export declare function VectorSquare(): any;

export declare function Vegan(): any;

export declare function VenetianMask(): any;

export declare function Venus(): any;

export declare function VenusAndMars(): any;

export declare function Vibrate(): any;

export declare function VibrateOff(): any;

export declare function Video(): any;

export declare function VideoOff(): any;

export declare function Videotape(): any;

export declare function View(): any;

export declare function Voicemail(): any;

export declare function Volleyball(): any;

export declare function Volume(): any;

export declare function Volume1(): any;

export declare function Volume2(): any;

export declare function VolumeOff(): any;

export declare function VolumeX(): any;

export declare function Vote(): any;

export declare function Wallet(): any;

export declare function WalletCards(): any;

export declare function WalletMinimal(): any;

export declare function Wallpaper(): any;

export declare function Wand(): any;

export declare function WandSparkles(): any;

export declare function Warehouse(): any;

export declare function WashingMachine(): any;

export declare function Watch(): any;

export declare function Waves(): any;

export declare function WavesArrowDown(): any;

export declare function WavesArrowUp(): any;

export declare function WavesLadder(): any;

export declare function Waypoints(): any;

export declare function Webcam(): any;

export declare function Webhook(): any;

export declare function WebhookOff(): any;

export declare function Weight(): any;

export declare function WeightTilde(): any;

export declare function Wheat(): any;

export declare function WheatOff(): any;

export declare function WholeWord(): any;

export declare function Wifi(): any;

export declare function WifiCog(): any;

export declare function WifiHigh(): any;

export declare function WifiLow(): any;

export declare function WifiOff(): any;

export declare function WifiPen(): any;

export declare function WifiSync(): any;

export declare function WifiZero(): any;

export declare function Wind(): any;

export declare function WindArrowDown(): any;

export declare function Wine(): any;

export declare function WineOff(): any;

export declare function Workflow(): any;

export declare function Worm(): any;

export declare function Wrench(): any;

export declare function X(): any;

export declare function Youtube(): any;

export declare function Zap(): any;

export declare function ZapOff(): any;

export declare function ZoomIn(): any;

export declare function ZoomOut(): any;
