// Generated by vesk-native from immutable-collections.vsklib — do not edit by hand.
// Type surface for the `@vesk/immutable-collections` virtual module (kotlinx.collections.immutable 0.3.7).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface ImmutableCollectionAdapter {}

export declare function ImmutableCollectionAdapter(props: {
    impl: Array<any>;
  }): ImmutableCollectionAdapter;
