// Generated by vesk-native from in-app-review.vsklib — do not edit by hand.
// Type surface for the `@vesk/in-app-review` virtual module (Play In-App Review 2.0.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


