// Generated by vesk-native from jackson.vsklib — do not edit by hand.
// Type surface for the `@vesk/jackson` virtual module (Jackson Kotlin 2.17.2).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const jacksonObjectMapper: any;
