// Generated by vesk-native from kotlinx-serialization.vsklib — do not edit by hand.
// Type surface for the `@vesk/kotlinx-serialization` virtual module (kotlinx.serialization 1.7.3).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface JsonObject {}

/**

 * Immutable JSON object. JsonObject({ key: value, ... }) builds from entries (values are JsonElement).

 */

export declare function JsonObject(props: {
    content: any;
  }): JsonObject;

export declare interface JsonArray {}

/**

 * Immutable JSON array. JsonArray([ element, ... ]) builds from JsonElement values.

 */

export declare function JsonArray(props: {
    content: Array<any>;
  }): JsonArray;

export declare const Json: any;

export declare const JsonPrimitive: any;

export declare const buildJsonObject: any;

export declare const buildJsonArray: any;
