// Generated by vesk-native from ktor-client.vsklib — do not edit by hand.
// Type surface for the `@vesk/ktor-client` virtual module (Ktor Client OkHttp 2.3.12).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const HttpClient: any;
