// Generated by vesk-native from leakcanary.vsklib — do not edit by hand.
// Type surface for the `@vesk/leakcanary` virtual module (LeakCanary 2.14).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const LeakCanary: any;
