// Generated by vesk-native from lottie.vsklib — do not edit by hand.
// Type surface for the `@vesk/lottie` virtual module (Lottie 6.5.2).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const LottieComposition: any;
