// Generated by vesk-native from material.vsklib — do not edit by hand.
// Type surface for the `@vesk/material` virtual module (Material (M2) 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <AlertDialog>, <DropdownMenu>, <DropdownMenuItem>, <BottomAppBar>, <TopAppBar>, <BackdropScaffold>, <Badge>, <BadgedBox>, <BottomNavigation>, <BottomSheetScaffold>, <Button>, <OutlinedButton>, <TextButton>, <Card>, <Checkbox>, <TriStateCheckbox>, <Chip>, <FilterChip>, <Divider>, <BottomDrawer>, <ModalDrawer>, <ExposedDropdownMenuBox>, <ExtendedFloatingActionButton>, <FloatingActionButton>, <IconButton>, <IconToggleButton>, <Icon>, <ListItem>, <MaterialTheme>, <ModalBottomSheetLayout>, <NavigationRail>, <NavigationRailItem>, <OutlinedTextField>, <CircularProgressIndicator>, <LinearProgressIndicator>, <RadioButton>, <Scaffold>, <RangeSlider>, <Slider>, <SnackbarHost>, <Snackbar>, <Surface>, <SwipeToDismiss>, <Switch>, <LeadingIconTab>, <Tab>, <ScrollableTabRow>, <TabRow>, <TextField>, <ProvideTextStyle>, <Text>, <PullRefreshIndicator>.

export declare interface BackdropScaffoldState {}

export declare function BackdropScaffoldState(props: {
    initialValue: 'Concealed' | 'Revealed';
    animationSpec?: any;
    confirmStateChange?: (...args: any[]) => any;
    snackbarHostState?: any;
  }): BackdropScaffoldState;

export declare const BackdropValue: {
    readonly Concealed: 'Concealed';
    readonly Revealed: 'Revealed';
  };

export declare type BackdropValue = (typeof BackdropValue)[keyof typeof BackdropValue];

export declare interface BottomDrawerState {}

export declare function BottomDrawerState(props: {
    initialValue: 'Closed' | 'Open' | 'Expanded';
    confirmStateChange?: (...args: any[]) => any;
  }): BottomDrawerState;

export declare const BottomDrawerValue: {
    readonly Closed: 'Closed';
    readonly Open: 'Open';
    readonly Expanded: 'Expanded';
  };

export declare type BottomDrawerValue = (typeof BottomDrawerValue)[keyof typeof BottomDrawerValue];

export declare interface BottomSheetScaffoldState {}

export declare function BottomSheetScaffoldState(props: {
    bottomSheetState: any;
    snackbarHostState: any;
  }): BottomSheetScaffoldState;

export declare interface BottomSheetState {}

export declare function BottomSheetState(props: {
    initialValue: 'Collapsed' | 'Expanded';
    animationSpec?: any;
    confirmValueChange?: (...args: any[]) => any;
  }): BottomSheetState;

export declare const BottomSheetValue: {
    readonly Collapsed: 'Collapsed';
    readonly Expanded: 'Expanded';
  };

export declare type BottomSheetValue = (typeof BottomSheetValue)[keyof typeof BottomSheetValue];

export declare interface Colors {}

export declare function Colors(props: {
    primary: any;
    primaryVariant: any;
    secondary: any;
    secondaryVariant: any;
    background: any;
    surface: any;
    error: any;
    onPrimary: any;
    onSecondary: any;
    onBackground: any;
    onSurface: any;
    onError: any;
    isLight: boolean;
  }): Colors;

export declare const DismissDirection: {
    readonly StartToEnd: 'StartToEnd';
    readonly EndToStart: 'EndToStart';
  };

export declare type DismissDirection = (typeof DismissDirection)[keyof typeof DismissDirection];

export declare interface DismissState {}

export declare function DismissState(props: {
    initialValue: 'Default' | 'DismissedToEnd' | 'DismissedToStart';
    confirmStateChange?: (...args: any[]) => any;
  }): DismissState;

export declare const DismissValue: {
    readonly Default: 'Default';
    readonly DismissedToEnd: 'DismissedToEnd';
    readonly DismissedToStart: 'DismissedToStart';
  };

export declare type DismissValue = (typeof DismissValue)[keyof typeof DismissValue];

export declare interface DrawerState {}

export declare function DrawerState(props: {
    initialValue: 'Closed' | 'Open';
    confirmStateChange?: (...args: any[]) => any;
  }): DrawerState;

export declare const DrawerValue: {
    readonly Closed: 'Closed';
    readonly Open: 'Open';
  };

export declare type DrawerValue = (typeof DrawerValue)[keyof typeof DrawerValue];

export declare interface FabPosition {}

export declare function FabPosition(props: {
    value: number;
  }): FabPosition;

export declare interface FixedThreshold {}

export declare function FixedThreshold(props: {
    offset: any;
  }): FixedThreshold;

export declare interface FractionalThreshold {}

export declare function FractionalThreshold(props: {
    fraction: number;
  }): FractionalThreshold;

export declare interface ModalBottomSheetState {}

export declare function ModalBottomSheetState(props: {
    initialValue: 'Hidden' | 'Expanded' | 'HalfExpanded';
    animationSpec?: any;
    isSkipHalfExpanded?: boolean;
    confirmStateChange?: (...args: any[]) => any;
  }): ModalBottomSheetState;

export declare const ModalBottomSheetValue: {
    readonly Hidden: 'Hidden';
    readonly Expanded: 'Expanded';
    readonly HalfExpanded: 'HalfExpanded';
  };

export declare type ModalBottomSheetValue = (typeof ModalBottomSheetValue)[keyof typeof ModalBottomSheetValue];

export declare interface ResistanceConfig {}

export declare function ResistanceConfig(props: {
    basis: number;
    factorAtMin?: number;
    factorAtMax?: number;
  }): ResistanceConfig;

export declare interface ScaffoldState {}

export declare function ScaffoldState(props: {
    drawerState: any;
    snackbarHostState: any;
  }): ScaffoldState;

export declare interface Shapes {}

export declare function Shapes(props: {
    small?: any;
    medium?: any;
    large?: any;
  }): Shapes;

export declare const SnackbarDuration: {
    readonly Short: 'Short';
    readonly Long: 'Long';
    readonly Indefinite: 'Indefinite';
  };

export declare type SnackbarDuration = (typeof SnackbarDuration)[keyof typeof SnackbarDuration];

export declare interface SnackbarHostState {}

export declare function SnackbarHostState(): SnackbarHostState;

export declare const SnackbarResult: {
    readonly Dismissed: 'Dismissed';
    readonly ActionPerformed: 'ActionPerformed';
  };

export declare type SnackbarResult = (typeof SnackbarResult)[keyof typeof SnackbarResult];

export declare interface SwipeProgress {}

export declare function SwipeProgress(props: {
    from: any;
    to: any;
    fraction: number;
  }): SwipeProgress;

export declare interface SwipeableState {}

export declare function SwipeableState(props: {
    initialValue: any;
    animationSpec?: any;
    confirmStateChange?: (...args: any[]) => any;
  }): SwipeableState;

export declare interface TabPosition {}

export declare function TabPosition(props: {
    left: any;
    width: any;
  }): TabPosition;

export declare interface Typography {}

export declare function Typography(props: {
    h1: any;
    h2: any;
    h3: any;
    h4: any;
    h5: any;
    h6: any;
    subtitle1: any;
    subtitle2: any;
    body1: any;
    body2: any;
    button: any;
    caption: any;
    overline: any;
  }): Typography;

export declare interface PullRefreshState {}

export declare function PullRefreshState(props: {
    animationScope: any;
    onRefreshState: any;
    refreshingOffset: number;
    threshold: number;
  }): PullRefreshState;

export declare const AlertDialog: any;

export declare const DropdownMenu: any;

export declare const DropdownMenuItem: any;

export declare const BottomAppBar: any;

export declare const TopAppBar: any;

export declare const BackdropScaffold: any;

export declare const Badge: any;

export declare const BadgedBox: any;

export declare const BottomNavigation: any;

export declare const BottomSheetScaffold: any;

export declare const Button: any;

export declare const OutlinedButton: any;

export declare const TextButton: any;

export declare const Card: any;

export declare const Checkbox: any;

export declare const TriStateCheckbox: any;

export declare const Chip: any;

export declare const FilterChip: any;

export declare const Divider: any;

export declare const BottomDrawer: any;

export declare const ModalDrawer: any;

export declare const ExposedDropdownMenuBox: any;

export declare const ExtendedFloatingActionButton: any;

export declare const FloatingActionButton: any;

export declare const IconButton: any;

export declare const IconToggleButton: any;

export declare const Icon: any;

export declare const ListItem: any;

export declare const MaterialTheme: any;

export declare const ModalBottomSheetLayout: any;

export declare const NavigationRail: any;

export declare const NavigationRailItem: any;

export declare const OutlinedTextField: any;

export declare const CircularProgressIndicator: any;

export declare const LinearProgressIndicator: any;

export declare const RadioButton: any;

export declare const Scaffold: any;

export declare const RangeSlider: any;

export declare const Slider: any;

export declare const SnackbarHost: any;

export declare const Snackbar: any;

export declare const Surface: any;

export declare const SwipeToDismiss: any;

export declare const Switch: any;

export declare const LeadingIconTab: any;

export declare const Tab: any;

export declare const ScrollableTabRow: any;

export declare const TabRow: any;

export declare const TextField: any;

export declare const ProvideTextStyle: any;

export declare const Text: any;

export declare const PullRefreshIndicator: any;
