// Generated by vesk-native from material-icons.vsklib — do not edit by hand.
// Type surface for the `@vesk/material-icons` virtual module (Material Icons Core 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


