// Generated by vesk-native from material-ripple.vsklib — do not edit by hand.
// Type surface for the `@vesk/material-ripple` virtual module (Compose Material Ripple 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface RippleAlpha {}

export declare function RippleAlpha(props: {
    draggedAlpha: number;
    focusedAlpha: number;
    hoveredAlpha: number;
    pressedAlpha: number;
  }): RippleAlpha;
