// Generated by vesk-native from material-icons.vsklib — do not edit by hand.
// Type surface for the `@vesk/material-icons` virtual module (Material Icons (core) 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

/**

 * Icons object — use Icons.Filled.<Name> (e.g. Icons.Filled.Home) as imageVector on the material3 <Icon> tag.

 */

export declare const Icons: any;

/**

 * Material icon 'AccountBox' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const AccountBox: any;

/**

 * Material icon 'AccountCircle' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const AccountCircle: any;

/**

 * Material icon 'Add' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Add: any;

/**

 * Material icon 'AddCircle' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const AddCircle: any;

/**

 * Material icon 'ArrowBack' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const ArrowBack: any;

/**

 * Material icon 'ArrowDropDown' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const ArrowDropDown: any;

/**

 * Material icon 'ArrowForward' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const ArrowForward: any;

/**

 * Material icon 'Build' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Build: any;

/**

 * Material icon 'Call' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Call: any;

/**

 * Material icon 'Check' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Check: any;

/**

 * Material icon 'CheckCircle' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const CheckCircle: any;

/**

 * Material icon 'Clear' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Clear: any;

/**

 * Material icon 'Close' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Close: any;

/**

 * Material icon 'Create' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Create: any;

/**

 * Material icon 'DateRange' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const DateRange: any;

/**

 * Material icon 'Delete' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Delete: any;

/**

 * Material icon 'Done' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Done: any;

/**

 * Material icon 'Edit' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Edit: any;

/**

 * Material icon 'Email' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Email: any;

/**

 * Material icon 'ExitToApp' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const ExitToApp: any;

/**

 * Material icon 'Face' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Face: any;

/**

 * Material icon 'Favorite' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Favorite: any;

/**

 * Material icon 'FavoriteBorder' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const FavoriteBorder: any;

/**

 * Material icon 'Home' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Home: any;

/**

 * Material icon 'Info' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Info: any;

/**

 * Material icon 'KeyboardArrowDown' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const KeyboardArrowDown: any;

/**

 * Material icon 'KeyboardArrowLeft' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const KeyboardArrowLeft: any;

/**

 * Material icon 'KeyboardArrowRight' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const KeyboardArrowRight: any;

/**

 * Material icon 'KeyboardArrowUp' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const KeyboardArrowUp: any;

/**

 * Material icon 'List' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const List: any;

/**

 * Material icon 'LocationOn' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const LocationOn: any;

/**

 * Material icon 'Lock' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Lock: any;

/**

 * Material icon 'MailOutline' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const MailOutline: any;

/**

 * Material icon 'Menu' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Menu: any;

/**

 * Material icon 'MoreVert' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const MoreVert: any;

/**

 * Material icon 'Notifications' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Notifications: any;

/**

 * Material icon 'Person' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Person: any;

/**

 * Material icon 'Phone' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Phone: any;

/**

 * Material icon 'Place' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Place: any;

/**

 * Material icon 'PlayArrow' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const PlayArrow: any;

/**

 * Material icon 'Refresh' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Refresh: any;

/**

 * Material icon 'Search' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Search: any;

/**

 * Material icon 'Send' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Send: any;

/**

 * Material icon 'Settings' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Settings: any;

/**

 * Material icon 'Share' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Share: any;

/**

 * Material icon 'ShoppingCart' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const ShoppingCart: any;

/**

 * Material icon 'Star' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Star: any;

/**

 * Material icon 'ThumbUp' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const ThumbUp: any;

/**

 * Material icon 'Warning' (Icons.Default). Use as imageVector on the material3 <Icon> tag.

 */

export declare const Warning: any;
