// Generated by vesk-native from material3.vsklib — do not edit by hand.
// Type surface for the `@vesk/material3` virtual module (Material 3 1.2.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <AlertDialog>, <BasicAlertDialog>, <DropdownMenu>, <DropdownMenuItem>, <BottomAppBar>, <CenterAlignedTopAppBar>, <LargeTopAppBar>, <MediumTopAppBar>, <SmallTopAppBar>, <TopAppBar>, <Badge>, <BadgedBox>, <BottomSheetScaffold>, <Button>, <ElevatedButton>, <FilledTonalButton>, <OutlinedButton>, <TextButton>, <Card>, <ElevatedCard>, <OutlinedCard>, <Checkbox>, <TriStateCheckbox>, <AssistChip>, <ElevatedAssistChip>, <ElevatedFilterChip>, <ElevatedSuggestionChip>, <FilterChip>, <InputChip>, <SuggestionChip>, <DatePickerDialog>, <DatePicker>, <DateRangePicker>, <Divider>, <HorizontalDivider>, <VerticalDivider>, <ExposedDropdownMenuBox>, <ExtendedFloatingActionButton>, <FloatingActionButton>, <LargeFloatingActionButton>, <SmallFloatingActionButton>, <FilledIconButton>, <FilledIconToggleButton>, <FilledTonalIconButton>, <FilledTonalIconToggleButton>, <IconButton>, <IconToggleButton>, <OutlinedIconButton>, <OutlinedIconToggleButton>, <Icon>, <Label>, <ListItem>, <MaterialTheme>, <ModalBottomSheet>, <NavigationBar>, <DismissibleDrawerSheet>, <DismissibleNavigationDrawer>, <ModalDrawerSheet>, <ModalNavigationDrawer>, <NavigationDrawerItem>, <PermanentDrawerSheet>, <PermanentNavigationDrawer>, <NavigationRail>, <NavigationRailItem>, <OutlinedTextField>, <CircularProgressIndicator>, <LinearProgressIndicator>, <RadioButton>, <Scaffold>, <DockedSearchBar>, <SearchBar>, <MultiChoiceSegmentedButtonRow>, <SingleChoiceSegmentedButtonRow>, <RangeSlider>, <Slider>, <SnackbarHost>, <Snackbar>, <Surface>, <SwipeToDismiss>, <SwipeToDismissBox>, <Switch>, <LeadingIconTab>, <Tab>, <PrimaryScrollableTabRow>, <PrimaryTabRow>, <ScrollableTabRow>, <SecondaryScrollableTabRow>, <SecondaryTabRow>, <TabRow>, <TextField>, <ProvideTextStyle>, <Text>, <TimeInput>, <TimePicker>, <RichTooltip>, <TooltipBox>, <PullToRefreshContainer>.

export declare interface BottomSheetScaffoldState {}

export declare function BottomSheetScaffoldState(props: {
    bottomSheetState: any;
    snackbarHostState: any;
  }): BottomSheetScaffoldState;

export declare interface ButtonColors {}

export declare function ButtonColors(props: {
    containerColor: any;
    contentColor: any;
    disabledContainerColor: any;
    disabledContentColor: any;
  }): ButtonColors;

export declare interface ButtonElevation {}

export declare function ButtonElevation(props: {
    defaultElevation: any;
    pressedElevation: any;
    focusedElevation: any;
    hoveredElevation: any;
    disabledElevation: any;
  }): ButtonElevation;

export declare interface CardColors {}

export declare function CardColors(props: {
    containerColor: any;
    contentColor: any;
    disabledContainerColor: any;
    disabledContentColor: any;
  }): CardColors;

export declare interface CardElevation {}

export declare function CardElevation(props: {
    defaultElevation: any;
    pressedElevation: any;
    focusedElevation: any;
    hoveredElevation: any;
    draggedElevation: any;
    disabledElevation: any;
  }): CardElevation;

export declare interface CaretProperties {}

export declare function CaretProperties(props: {
    caretHeight: any;
    caretWidth: any;
  }): CaretProperties;

export declare interface CheckboxColors {}

export declare function CheckboxColors(props: {
    checkedCheckmarkColor: any;
    uncheckedCheckmarkColor: any;
    checkedBoxColor: any;
    uncheckedBoxColor: any;
    disabledCheckedBoxColor: any;
    disabledUncheckedBoxColor: any;
    disabledIndeterminateBoxColor: any;
    checkedBorderColor: any;
    uncheckedBorderColor: any;
    disabledBorderColor: any;
    disabledUncheckedBorderColor: any;
    disabledIndeterminateBorderColor: any;
  }): CheckboxColors;

export declare interface ChipBorder {}

export declare function ChipBorder(props: {
    borderColor: any;
    disabledBorderColor: any;
    borderWidth: any;
  }): ChipBorder;

export declare interface ChipColors {}

export declare function ChipColors(props: {
    containerColor: any;
    labelColor: any;
    leadingIconContentColor: any;
    trailingIconContentColor: any;
    disabledContainerColor: any;
    disabledLabelColor: any;
    disabledLeadingIconContentColor: any;
    disabledTrailingIconContentColor: any;
  }): ChipColors;

export declare interface ChipElevation {}

export declare function ChipElevation(props: {
    elevation: any;
    pressedElevation: any;
    focusedElevation: any;
    hoveredElevation: any;
    draggedElevation: any;
    disabledElevation: any;
  }): ChipElevation;

export declare interface ColorScheme {}

export declare function ColorScheme(props: {
    primary: any;
    onPrimary: any;
    primaryContainer: any;
    onPrimaryContainer: any;
    inversePrimary: any;
    secondary: any;
    onSecondary: any;
    secondaryContainer: any;
    onSecondaryContainer: any;
    tertiary: any;
    onTertiary: any;
    tertiaryContainer: any;
    onTertiaryContainer: any;
    background: any;
    onBackground: any;
    surface: any;
    onSurface: any;
    surfaceVariant: any;
    onSurfaceVariant: any;
    surfaceTint: any;
    inverseSurface: any;
    inverseOnSurface: any;
    error: any;
    onError: any;
    errorContainer: any;
    onErrorContainer: any;
    outline: any;
    outlineVariant: any;
    scrim: any;
    surfaceBright: any;
    surfaceDim: any;
    surfaceContainer: any;
    surfaceContainerHigh: any;
    surfaceContainerHighest: any;
    surfaceContainerLow: any;
    surfaceContainerLowest: any;
  }): ColorScheme;

export declare interface DatePickerColors {}

export declare function DatePickerColors(props: {
    containerColor: any;
    titleContentColor: any;
    headlineContentColor: any;
    weekdayContentColor: any;
    subheadContentColor: any;
    navigationContentColor: any;
    yearContentColor: any;
    disabledYearContentColor: any;
    currentYearContentColor: any;
    selectedYearContentColor: any;
    disabledSelectedYearContentColor: any;
    selectedYearContainerColor: any;
    disabledSelectedYearContainerColor: any;
    dayContentColor: any;
    disabledDayContentColor: any;
    selectedDayContentColor: any;
    disabledSelectedDayContentColor: any;
    selectedDayContainerColor: any;
    disabledSelectedDayContainerColor: any;
    todayContentColor: any;
    todayDateBorderColor: any;
    dayInSelectionRangeContainerColor: any;
    dayInSelectionRangeContentColor: any;
    dividerColor: any;
    dateTextFieldColors: any;
  }): DatePickerColors;

export declare const DismissDirection: {
    readonly StartToEnd: 'StartToEnd';
    readonly EndToStart: 'EndToStart';
  };

export declare type DismissDirection = (typeof DismissDirection)[keyof typeof DismissDirection];

export declare const DismissValue: {
    readonly Default: 'Default';
    readonly DismissedToEnd: 'DismissedToEnd';
    readonly DismissedToStart: 'DismissedToStart';
  };

export declare type DismissValue = (typeof DismissValue)[keyof typeof DismissValue];

export declare interface DisplayMode {}

export declare function DisplayMode(props: {
    value: number;
  }): DisplayMode;

export declare interface DrawerState {}

export declare function DrawerState(props: {
    initialValue: 'Closed' | 'Open';
    confirmStateChange?: (...args: any[]) => any;
  }): DrawerState;

export declare const DrawerValue: {
    readonly Closed: 'Closed';
    readonly Open: 'Open';
  };

export declare type DrawerValue = (typeof DrawerValue)[keyof typeof DrawerValue];

export declare interface FabPosition {}

export declare function FabPosition(props: {
    value: number;
  }): FabPosition;

export declare interface FloatingActionButtonElevation {}

export declare function FloatingActionButtonElevation(props: {
    defaultElevation: any;
    pressedElevation: any;
    focusedElevation: any;
    hoveredElevation: any;
  }): FloatingActionButtonElevation;

export declare interface IconButtonColors {}

export declare function IconButtonColors(props: {
    containerColor: any;
    contentColor: any;
    disabledContainerColor: any;
    disabledContentColor: any;
  }): IconButtonColors;

export declare interface IconToggleButtonColors {}

export declare function IconToggleButtonColors(props: {
    containerColor: any;
    contentColor: any;
    disabledContainerColor: any;
    disabledContentColor: any;
    checkedContainerColor: any;
    checkedContentColor: any;
  }): IconToggleButtonColors;

export declare interface ListItemColors {}

export declare function ListItemColors(props: {
    containerColor: any;
    headlineColor: any;
    leadingIconColor: any;
    overlineColor: any;
    supportingTextColor: any;
    trailingIconColor: any;
    disabledHeadlineColor: any;
    disabledLeadingIconColor: any;
    disabledTrailingIconColor: any;
  }): ListItemColors;

export declare interface MenuItemColors {}

export declare function MenuItemColors(props: {
    textColor: any;
    leadingIconColor: any;
    trailingIconColor: any;
    disabledTextColor: any;
    disabledLeadingIconColor: any;
    disabledTrailingIconColor: any;
  }): MenuItemColors;

export declare interface ModalBottomSheetProperties {}

export declare function ModalBottomSheetProperties(props: {
    securePolicy: any;
    isFocusable: boolean;
    shouldDismissOnBackPress: boolean;
  }): ModalBottomSheetProperties;

export declare interface NavigationBarItemColors {}

export declare function NavigationBarItemColors(props: {
    selectedIconColor: any;
    selectedTextColor: any;
    selectedIndicatorColor: any;
    unselectedIconColor: any;
    unselectedTextColor: any;
    disabledIconColor: any;
    disabledTextColor: any;
  }): NavigationBarItemColors;

export declare interface NavigationRailItemColors {}

export declare function NavigationRailItemColors(props: {
    selectedIconColor: any;
    selectedTextColor: any;
    selectedIndicatorColor: any;
    unselectedIconColor: any;
    unselectedTextColor: any;
    disabledIconColor: any;
    disabledTextColor: any;
  }): NavigationRailItemColors;

export declare interface RadioButtonColors {}

export declare function RadioButtonColors(props: {
    selectedColor: any;
    unselectedColor: any;
    disabledSelectedColor: any;
    disabledUnselectedColor: any;
  }): RadioButtonColors;

export declare interface RangeSliderState {}

export declare function RangeSliderState(props: {
    activeRangeStart?: number;
    activeRangeEnd?: number;
    steps?: number;
    onValueChangeFinished?: (...args: any[]) => any;
    valueRange?: any;
  }): RangeSliderState;

export declare interface RichTooltipColors {}

export declare function RichTooltipColors(props: {
    containerColor: any;
    contentColor: any;
    titleContentColor: any;
    actionContentColor: any;
  }): RichTooltipColors;

export declare interface SearchBarColors {}

export declare function SearchBarColors(props: {
    containerColor: any;
    dividerColor: any;
    inputFieldColors: any;
  }): SearchBarColors;

export declare interface SegmentedButtonColors {}

export declare function SegmentedButtonColors(props: {
    activeContainerColor: any;
    activeContentColor: any;
    activeBorderColor: any;
    inactiveContainerColor: any;
    inactiveContentColor: any;
    inactiveBorderColor: any;
    disabledActiveContainerColor: any;
    disabledActiveContentColor: any;
    disabledActiveBorderColor: any;
    disabledInactiveContainerColor: any;
    disabledInactiveContentColor: any;
    disabledInactiveBorderColor: any;
  }): SegmentedButtonColors;

export declare interface SelectableChipColors {}

export declare function SelectableChipColors(props: {
    containerColor: any;
    labelColor: any;
    leadingIconColor: any;
    trailingIconColor: any;
    disabledContainerColor: any;
    disabledLabelColor: any;
    disabledLeadingIconColor: any;
    disabledTrailingIconColor: any;
    selectedContainerColor: any;
    disabledSelectedContainerColor: any;
    selectedLabelColor: any;
    selectedLeadingIconColor: any;
    selectedTrailingIconColor: any;
  }): SelectableChipColors;

export declare interface SelectableChipElevation {}

export declare function SelectableChipElevation(props: {
    elevation: any;
    pressedElevation: any;
    focusedElevation: any;
    hoveredElevation: any;
    draggedElevation: any;
    disabledElevation: any;
  }): SelectableChipElevation;

export declare interface Shapes {}

export declare function Shapes(props: {
    extraSmall?: any;
    small?: any;
    medium?: any;
    large?: any;
    extraLarge?: any;
  }): Shapes;

export declare interface SheetState {}

export declare function SheetState(props: {
    skipPartiallyExpanded: boolean;
    initialValue?: 'Hidden' | 'Expanded' | 'PartiallyExpanded';
    confirmValueChange?: (...args: any[]) => any;
    skipHiddenState?: boolean;
  }): SheetState;

export declare const SheetValue: {
    readonly Hidden: 'Hidden';
    readonly Expanded: 'Expanded';
    readonly PartiallyExpanded: 'PartiallyExpanded';
  };

export declare type SheetValue = (typeof SheetValue)[keyof typeof SheetValue];

export declare interface SliderColors {}

export declare function SliderColors(props: {
    thumbColor: any;
    activeTrackColor: any;
    activeTickColor: any;
    inactiveTrackColor: any;
    inactiveTickColor: any;
    disabledThumbColor: any;
    disabledActiveTrackColor: any;
    disabledActiveTickColor: any;
    disabledInactiveTrackColor: any;
    disabledInactiveTickColor: any;
  }): SliderColors;

export declare interface SliderPositions {}

export declare function SliderPositions(props: {
    initialActiveRange?: any;
    initialTickFractions?: Array<any>;
  }): SliderPositions;

export declare interface SliderState {}

export declare function SliderState(props: {
    value?: number;
    steps?: number;
    onValueChangeFinished?: (...args: any[]) => any;
    valueRange?: any;
  }): SliderState;

export declare const SnackbarDuration: {
    readonly Short: 'Short';
    readonly Long: 'Long';
    readonly Indefinite: 'Indefinite';
  };

export declare type SnackbarDuration = (typeof SnackbarDuration)[keyof typeof SnackbarDuration];

export declare interface SnackbarHostState {}

export declare function SnackbarHostState(): SnackbarHostState;

export declare const SnackbarResult: {
    readonly Dismissed: 'Dismissed';
    readonly ActionPerformed: 'ActionPerformed';
  };

export declare type SnackbarResult = (typeof SnackbarResult)[keyof typeof SnackbarResult];

export declare interface SwipeToDismissBoxState {}

export declare function SwipeToDismissBoxState(props: {
    initialValue: 'StartToEnd' | 'EndToStart' | 'Settled';
    density: any;
    confirmValueChange?: (...args: any[]) => any;
    positionalThreshold?: (...args: any[]) => any;
  }): SwipeToDismissBoxState;

export declare const SwipeToDismissBoxValue: {
    readonly StartToEnd: 'StartToEnd';
    readonly EndToStart: 'EndToStart';
    readonly Settled: 'Settled';
  };

export declare type SwipeToDismissBoxValue = (typeof SwipeToDismissBoxValue)[keyof typeof SwipeToDismissBoxValue];

export declare interface SwitchColors {}

export declare function SwitchColors(props: {
    checkedThumbColor: any;
    checkedTrackColor: any;
    checkedBorderColor: any;
    checkedIconColor: any;
    uncheckedThumbColor: any;
    uncheckedTrackColor: any;
    uncheckedBorderColor: any;
    uncheckedIconColor: any;
    disabledCheckedThumbColor: any;
    disabledCheckedTrackColor: any;
    disabledCheckedBorderColor: any;
    disabledCheckedIconColor: any;
    disabledUncheckedThumbColor: any;
    disabledUncheckedTrackColor: any;
    disabledUncheckedBorderColor: any;
    disabledUncheckedIconColor: any;
  }): SwitchColors;

export declare interface TabPosition {}

export declare function TabPosition(props: {
    left: any;
    width: any;
    contentWidth: any;
  }): TabPosition;

export declare interface TextFieldColors {}

export declare function TextFieldColors(props: {
    focusedTextColor: any;
    unfocusedTextColor: any;
    disabledTextColor: any;
    errorTextColor: any;
    focusedContainerColor: any;
    unfocusedContainerColor: any;
    disabledContainerColor: any;
    errorContainerColor: any;
    cursorColor: any;
    errorCursorColor: any;
    textSelectionColors: any;
    focusedIndicatorColor: any;
    unfocusedIndicatorColor: any;
    disabledIndicatorColor: any;
    errorIndicatorColor: any;
    focusedLeadingIconColor: any;
    unfocusedLeadingIconColor: any;
    disabledLeadingIconColor: any;
    errorLeadingIconColor: any;
    focusedTrailingIconColor: any;
    unfocusedTrailingIconColor: any;
    disabledTrailingIconColor: any;
    errorTrailingIconColor: any;
    focusedLabelColor: any;
    unfocusedLabelColor: any;
    disabledLabelColor: any;
    errorLabelColor: any;
    focusedPlaceholderColor: any;
    unfocusedPlaceholderColor: any;
    disabledPlaceholderColor: any;
    errorPlaceholderColor: any;
    focusedSupportingTextColor: any;
    unfocusedSupportingTextColor: any;
    disabledSupportingTextColor: any;
    errorSupportingTextColor: any;
    focusedPrefixColor: any;
    unfocusedPrefixColor: any;
    disabledPrefixColor: any;
    errorPrefixColor: any;
    focusedSuffixColor: any;
    unfocusedSuffixColor: any;
    disabledSuffixColor: any;
    errorSuffixColor: any;
  }): TextFieldColors;

export declare interface TimePickerColors {}

export declare function TimePickerColors(props: {
    clockDialColor: any;
    selectorColor: any;
    containerColor: any;
    periodSelectorBorderColor: any;
    clockDialSelectedContentColor: any;
    clockDialUnselectedContentColor: any;
    periodSelectorSelectedContainerColor: any;
    periodSelectorUnselectedContainerColor: any;
    periodSelectorSelectedContentColor: any;
    periodSelectorUnselectedContentColor: any;
    timeSelectorSelectedContainerColor: any;
    timeSelectorUnselectedContainerColor: any;
    timeSelectorSelectedContentColor: any;
    timeSelectorUnselectedContentColor: any;
  }): TimePickerColors;

export declare interface TimePickerLayoutType {}

export declare function TimePickerLayoutType(props: {
    value: number;
  }): TimePickerLayoutType;

export declare interface TimePickerState {}

export declare function TimePickerState(props: {
    initialHour: number;
    initialMinute: number;
    is24Hour: boolean;
  }): TimePickerState;

export declare interface TopAppBarColors {}

export declare function TopAppBarColors(props: {
    containerColor: any;
    scrolledContainerColor: any;
    navigationIconContentColor: any;
    titleContentColor: any;
    actionIconContentColor: any;
  }): TopAppBarColors;

export declare interface TopAppBarState {}

export declare function TopAppBarState(props: {
    initialHeightOffsetLimit: number;
    initialHeightOffset: number;
    initialContentOffset: number;
  }): TopAppBarState;

export declare interface Typography {}

export declare function Typography(props: {
    displayLarge?: any;
    displayMedium?: any;
    displaySmall?: any;
    headlineLarge?: any;
    headlineMedium?: any;
    headlineSmall?: any;
    titleLarge?: any;
    titleMedium?: any;
    titleSmall?: any;
    bodyLarge?: any;
    bodyMedium?: any;
    bodySmall?: any;
    labelLarge?: any;
    labelMedium?: any;
    labelSmall?: any;
  }): Typography;

export declare const AlertDialog: any;

export declare const BasicAlertDialog: any;

export declare const DropdownMenu: any;

export declare const DropdownMenuItem: any;

export declare const BottomAppBar: any;

export declare const CenterAlignedTopAppBar: any;

export declare const LargeTopAppBar: any;

export declare const MediumTopAppBar: any;

export declare const SmallTopAppBar: any;

export declare const TopAppBar: any;

export declare const Badge: any;

export declare const BadgedBox: any;

export declare const BottomSheetScaffold: any;

export declare const Button: any;

export declare const ElevatedButton: any;

export declare const FilledTonalButton: any;

export declare const OutlinedButton: any;

export declare const TextButton: any;

export declare const Card: any;

export declare const ElevatedCard: any;

export declare const OutlinedCard: any;

export declare const Checkbox: any;

export declare const TriStateCheckbox: any;

export declare const AssistChip: any;

export declare const ElevatedAssistChip: any;

export declare const ElevatedFilterChip: any;

export declare const ElevatedSuggestionChip: any;

export declare const FilterChip: any;

export declare const InputChip: any;

export declare const SuggestionChip: any;

export declare const DatePickerDialog: any;

export declare const DatePicker: any;

export declare const DateRangePicker: any;

export declare const Divider: any;

export declare const HorizontalDivider: any;

export declare const VerticalDivider: any;

export declare const ExposedDropdownMenuBox: any;

export declare const ExtendedFloatingActionButton: any;

export declare const FloatingActionButton: any;

export declare const LargeFloatingActionButton: any;

export declare const SmallFloatingActionButton: any;

export declare const FilledIconButton: any;

export declare const FilledIconToggleButton: any;

export declare const FilledTonalIconButton: any;

export declare const FilledTonalIconToggleButton: any;

export declare const IconButton: any;

export declare const IconToggleButton: any;

export declare const OutlinedIconButton: any;

export declare const OutlinedIconToggleButton: any;

export declare const Icon: any;

export declare const Label: any;

export declare const ListItem: any;

export declare const MaterialTheme: any;

export declare const ModalBottomSheet: any;

export declare const NavigationBar: any;

export declare const DismissibleDrawerSheet: any;

export declare const DismissibleNavigationDrawer: any;

export declare const ModalDrawerSheet: any;

export declare const ModalNavigationDrawer: any;

export declare const NavigationDrawerItem: any;

export declare const PermanentDrawerSheet: any;

export declare const PermanentNavigationDrawer: any;

export declare const NavigationRail: any;

export declare const NavigationRailItem: any;

export declare const OutlinedTextField: any;

export declare const CircularProgressIndicator: any;

export declare const LinearProgressIndicator: any;

export declare const RadioButton: any;

export declare const Scaffold: any;

export declare const DockedSearchBar: any;

export declare const SearchBar: any;

export declare const MultiChoiceSegmentedButtonRow: any;

export declare const SingleChoiceSegmentedButtonRow: any;

export declare const RangeSlider: any;

export declare const Slider: any;

export declare const SnackbarHost: any;

export declare const Snackbar: any;

export declare const Surface: any;

export declare const SwipeToDismiss: any;

export declare const SwipeToDismissBox: any;

export declare const Switch: any;

export declare const LeadingIconTab: any;

export declare const Tab: any;

export declare const PrimaryScrollableTabRow: any;

export declare const PrimaryTabRow: any;

export declare const ScrollableTabRow: any;

export declare const SecondaryScrollableTabRow: any;

export declare const SecondaryTabRow: any;

export declare const TabRow: any;

export declare const TextField: any;

export declare const ProvideTextStyle: any;

export declare const Text: any;

export declare const TimeInput: any;

export declare const TimePicker: any;

export declare const RichTooltip: any;

export declare const TooltipBox: any;

export declare const PullToRefreshContainer: any;
