// Generated by vesk-native from media3-exoplayer.vsklib — do not edit by hand.
// Type surface for the `@vesk/media3-exoplayer` virtual module (Media3 ExoPlayer 1.3.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


