// Generated by vesk-native from mlkit-barcode.vsklib — do not edit by hand.
// Type surface for the `@vesk/mlkit-barcode` virtual module (ML Kit Barcode Scanning 17.3.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


