// Generated by vesk-native from moshi.vsklib — do not edit by hand.
// Type surface for the `@vesk/moshi` virtual module (Moshi 1.15.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface JsonAdapter {}

/**

 * Typed JSON adapter. JsonAdapter() is the abstract base; Moshi.adapter(type) returns a concrete instance.

 */

export declare function JsonAdapter(): JsonAdapter;

export declare const Moshi: any;
