// Generated by vesk-native from moshi.vsklib — do not edit by hand.
// Type surface for the `@vesk/moshi` virtual module (Moshi 1.15.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

/**

 * Moshi JSON library. The Moshi constructor is package-private — obtain the engine via new Moshi.Builder().build(); Moshi.adapter(String) returns a JsonAdapter<String> (other adapters need class literals).

 */

export declare const Moshi: any;

export declare interface Builder {}

/**

 * Moshi.Builder() — builder for a Moshi instance (public constructor, build() returns Moshi).

 */

export declare function Builder(): Builder;

/**

 * Typed JSON adapter base — abstract (subclasses generated by Moshi codegen); obtain via Moshi.adapter(type), never constructed directly.

 */

export declare const JsonAdapter: any;
