// Generated by vesk-native from navigation.vsklib — do not edit by hand.
// Type surface for the `@vesk/navigation` virtual module (AndroidX Navigation Compose 2.7.7).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <DialogHost>, <NavHost>.

export declare interface ComposeNavigator {}

export declare function ComposeNavigator(): ComposeNavigator;

export declare interface DialogNavigator {}

export declare function DialogNavigator(): DialogNavigator;

export declare const DialogHost: any;

export declare const NavHost: any;
