// Generated by vesk-native from okhttp-logging.vsklib — do not edit by hand.
// Type surface for the `@vesk/okhttp-logging` virtual module (OkHttp Logging Interceptor 4.12.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const HttpLoggingInterceptor: any;
