// Generated by vesk-native from okhttp.vsklib — do not edit by hand.
// Type surface for the `@vesk/okhttp` virtual module (OkHttp 4.12.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface OkHttpClient {}

/**

 * HTTP client. Construct with OkHttpClient(); configure via OkHttpClient().newBuilder() before building requests.

 */

export declare function OkHttpClient(): OkHttpClient;

export declare const Request: any;

export declare const Response: any;

export declare const RequestBody: any;
