// Generated by vesk-native from okio.vsklib — do not edit by hand.
// Type surface for the `@vesk/okio` virtual module (Okio 3.9.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const Buffer: any;

export declare const ByteString: any;
