// Generated by vesk-native from palette.vsklib — do not edit by hand.
// Type surface for the `@vesk/palette` virtual module (Palette 1.0.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const Palette: any;
