// Generated by vesk-native from picasso.vsklib — do not edit by hand.
// Type surface for the `@vesk/picasso` virtual module (Picasso 2.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const Picasso: any;
