// Generated by vesk-native from play-services-location.vsklib — do not edit by hand.
// Type surface for the `@vesk/play-services-location` virtual module (Play Services Location 21.3.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


