// Generated by vesk-native from play-services-auth.vsklib — do not edit by hand.
// Type surface for the `@vesk/play-services-auth` virtual module (Play Services Auth 20.7.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


