// Generated by vesk-native from play-services-maps.vsklib — do not edit by hand.
// Type surface for the `@vesk/play-services-maps` virtual module (Play Services Maps 18.2.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


