// Generated by vesk-native from preference-ktx.vsklib — do not edit by hand.
// Type surface for the `@vesk/preference-ktx` virtual module (AndroidX Preference KTX 1.2.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


