// Generated by vesk-native from retrofit-moshi.vsklib — do not edit by hand.
// Type surface for the `@vesk/retrofit-moshi` virtual module (Retrofit Moshi Converter 2.11.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const MoshiConverterFactory: any;
