// Generated by vesk-native from room.vsklib — do not edit by hand.
// Type surface for the `@vesk/room` virtual module (Room 2.6.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const Room: any;

export declare const RoomDatabase: any;
