// Generated by vesk-native from security-crypto.vsklib — do not edit by hand.
// Type surface for the `@vesk/security-crypto` virtual module (AndroidX Security Crypto 1.0.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


