// Generated by vesk-native from shimmer.vsklib — do not edit by hand.
// Type surface for the `@vesk/shimmer` virtual module (Compose Shimmer 1.3.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <Shimmer>.

export declare interface Shimmer {}

export declare function Shimmer(props: {
    theme: any;
    effect: any;
    bounds: any;
  }): Shimmer;

export declare const ShimmerBounds: {
    readonly Custom: 'Custom';
    readonly View: 'View';
    readonly Window: 'Window';
  };

export declare type ShimmerBounds = (typeof ShimmerBounds)[keyof typeof ShimmerBounds];

export declare interface ShimmerTheme {}

export declare function ShimmerTheme(props: {
    animationSpec: any;
    blendMode: any;
    rotation: number;
    shaderColors: Array<any>;
    shaderColorStops: Array<number>;
    shimmerWidth: any;
  }): ShimmerTheme;
