// Generated by vesk-native from timber.vsklib — do not edit by hand.
// Type surface for the `@vesk/timber` virtual module (Timber 5.0.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const Timber: any;
