// Generated by vesk-native from ui.vsklib — do not edit by hand.
// Type surface for the `@vesk/ui` virtual module (Compose UI 1.6.8).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <Group>, <Path>, <RenderVectorGroup>, <Layout>, <MultiMeasureLayout>, <LookaheadScope>, <SubcomposeLayout>, <TestModifierUpdaterLayout>, <Dialog>, <Popup>.

export declare interface BiasAbsoluteAlignment {}

export declare function BiasAbsoluteAlignment(props: {
    horizontalBias: number;
    verticalBias: number;
  }): BiasAbsoluteAlignment;

export declare interface BiasAlignment {}

export declare function BiasAlignment(props: {
    horizontalBias: number;
    verticalBias: number;
  }): BiasAlignment;

export declare interface CombinedModifier {}

export declare function CombinedModifier(props: {
    outer: any;
    inner: any;
  }): CombinedModifier;

export declare interface AutofillNode {}

export declare function AutofillNode(props: {
    autofillTypes?: Array<'EmailAddress' | 'Username' | 'Password' | 'NewUsername' | 'NewPassword' | 'PostalAddress' | 'PostalCode' | 'CreditCardNumber' | 'CreditCardSecurityCode' | 'CreditCardExpirationDate' | 'CreditCardExpirationMonth' | 'CreditCardExpirationYear' | 'CreditCardExpirationDay' | 'AddressCountry' | 'AddressRegion' | 'AddressLocality' | 'AddressStreet' | 'AddressAuxiliaryDetails' | 'PostalCodeExtended' | 'PersonFullName' | 'PersonFirstName' | 'PersonLastName' | 'PersonMiddleName' | 'PersonMiddleInitial' | 'PersonNamePrefix' | 'PersonNameSuffix' | 'PhoneNumber' | 'PhoneNumberDevice' | 'PhoneCountryCode' | 'PhoneNumberNational' | 'Gender' | 'BirthDateFull' | 'BirthDateDay' | 'BirthDateMonth' | 'BirthDateYear' | 'SmsOtpCode'>;
    boundingBox?: any;
    onFill?: (...args: any[]) => any;
  }): AutofillNode;

export declare interface AutofillTree {}

export declare function AutofillTree(): AutofillTree;

export declare const AutofillType: {
    readonly EmailAddress: 'EmailAddress';
    readonly Username: 'Username';
    readonly Password: 'Password';
    readonly NewUsername: 'NewUsername';
    readonly NewPassword: 'NewPassword';
    readonly PostalAddress: 'PostalAddress';
    readonly PostalCode: 'PostalCode';
    readonly CreditCardNumber: 'CreditCardNumber';
    readonly CreditCardSecurityCode: 'CreditCardSecurityCode';
    readonly CreditCardExpirationDate: 'CreditCardExpirationDate';
    readonly CreditCardExpirationMonth: 'CreditCardExpirationMonth';
    readonly CreditCardExpirationYear: 'CreditCardExpirationYear';
    readonly CreditCardExpirationDay: 'CreditCardExpirationDay';
    readonly AddressCountry: 'AddressCountry';
    readonly AddressRegion: 'AddressRegion';
    readonly AddressLocality: 'AddressLocality';
    readonly AddressStreet: 'AddressStreet';
    readonly AddressAuxiliaryDetails: 'AddressAuxiliaryDetails';
    readonly PostalCodeExtended: 'PostalCodeExtended';
    readonly PersonFullName: 'PersonFullName';
    readonly PersonFirstName: 'PersonFirstName';
    readonly PersonLastName: 'PersonLastName';
    readonly PersonMiddleName: 'PersonMiddleName';
    readonly PersonMiddleInitial: 'PersonMiddleInitial';
    readonly PersonNamePrefix: 'PersonNamePrefix';
    readonly PersonNameSuffix: 'PersonNameSuffix';
    readonly PhoneNumber: 'PhoneNumber';
    readonly PhoneNumberDevice: 'PhoneNumberDevice';
    readonly PhoneCountryCode: 'PhoneCountryCode';
    readonly PhoneNumberNational: 'PhoneNumberNational';
    readonly Gender: 'Gender';
    readonly BirthDateFull: 'BirthDateFull';
    readonly BirthDateDay: 'BirthDateDay';
    readonly BirthDateMonth: 'BirthDateMonth';
    readonly BirthDateYear: 'BirthDateYear';
    readonly SmsOtpCode: 'SmsOtpCode';
  };

export declare type AutofillType = (typeof AutofillType)[keyof typeof AutofillType];

export declare interface DragAndDropEvent {}

export declare function DragAndDropEvent(props: {
    dragEvent: any;
  }): DragAndDropEvent;

export declare interface DragAndDropTransferData {}

export declare function DragAndDropTransferData(props: {
    clipData: any;
    localState?: any;
    flags?: number;
  }): DragAndDropTransferData;

export declare interface BlurredEdgeTreatment {}

export declare function BlurredEdgeTreatment(props: {
    shape: any;
  }): BlurredEdgeTreatment;

export declare interface CacheDrawScope {}

export declare function CacheDrawScope(): CacheDrawScope;

export declare interface DrawResult {}

export declare function DrawResult(props: {
    block: (...args: any[]) => any;
  }): DrawResult;

export declare interface FocusDirection {}

export declare function FocusDirection(props: {
    value: number;
  }): FocusDirection;

export declare interface FocusOrder {}

export declare function FocusOrder(props: {
    focusProperties: any;
  }): FocusOrder;

export declare interface FocusRequester {}

export declare function FocusRequester(): FocusRequester;

export declare interface CompositingStrategy {}

export declare function CompositingStrategy(props: {
    value: number;
  }): CompositingStrategy;

export declare interface TransformOrigin {}

export declare function TransformOrigin(props: {
    packedValue: number;
  }): TransformOrigin;

export declare interface ImageVector {}

export declare function ImageVector(props: {
    name: string;
    defaultWidth: any;
    defaultHeight: any;
    viewportWidth: number;
    viewportHeight: number;
    root: any;
    tintColor: any;
    tintBlendMode: any;
    autoMirror: boolean;
    genId?: number;
  }): ImageVector;

export declare interface VectorApplier {}

export declare function VectorApplier(props: {
    root: any;
  }): VectorApplier;

export declare interface VectorGroup {}

export declare function VectorGroup(props: {
    name?: string;
    rotation?: number;
    pivotX?: number;
    pivotY?: number;
    scaleX?: number;
    scaleY?: number;
    translationX?: number;
    translationY?: number;
    clipPathData?: Array<any>;
    children?: Array<any>;
  }): VectorGroup;

export declare interface VectorPainter {}

export declare function VectorPainter(props: {
    root?: any;
  }): VectorPainter;

export declare interface VectorPath {}

export declare function VectorPath(props: {
    name?: string;
    pathData?: Array<any>;
    pathFillType?: any;
    fill?: any;
    fillAlpha?: number;
    stroke?: any;
    strokeAlpha?: number;
    strokeLineWidth?: number;
    strokeLineCap?: any;
    strokeLineJoin?: any;
    strokeLineMiter?: number;
    trimPathStart?: number;
    trimPathEnd?: number;
    trimPathOffset?: number;
  }): VectorPath;

export declare const VectorProperty: {
    readonly Fill: 'Fill';
    readonly FillAlpha: 'FillAlpha';
    readonly PathData: 'PathData';
    readonly PivotX: 'PivotX';
    readonly PivotY: 'PivotY';
    readonly Rotation: 'Rotation';
    readonly ScaleX: 'ScaleX';
    readonly ScaleY: 'ScaleY';
    readonly Stroke: 'Stroke';
    readonly StrokeAlpha: 'StrokeAlpha';
    readonly StrokeLineWidth: 'StrokeLineWidth';
    readonly TranslateX: 'TranslateX';
    readonly TranslateY: 'TranslateY';
    readonly TrimPathEnd: 'TrimPathEnd';
    readonly TrimPathOffset: 'TrimPathOffset';
    readonly TrimPathStart: 'TrimPathStart';
  };

export declare type VectorProperty = (typeof VectorProperty)[keyof typeof VectorProperty];

export declare interface HapticFeedbackType {}

export declare function HapticFeedbackType(props: {
    value: number;
  }): HapticFeedbackType;

export declare interface InputMode {}

export declare function InputMode(props: {
    value: number;
  }): InputMode;

export declare interface Key {}

export declare function Key(props: {
    keyCode: number;
  }): Key;

export declare interface KeyEvent {}

export declare function KeyEvent(props: {
    nativeKeyEvent: any;
  }): KeyEvent;

export declare interface KeyEventType {}

export declare function KeyEventType(props: {
    value: number;
  }): KeyEventType;

export declare interface NestedScrollDispatcher {}

export declare function NestedScrollDispatcher(): NestedScrollDispatcher;

export declare interface NestedScrollSource {}

export declare function NestedScrollSource(props: {
    value: number;
  }): NestedScrollSource;

export declare interface ConsumedData {}

export declare function ConsumedData(props: {
    positionChange?: boolean;
    downChange?: boolean;
  }): ConsumedData;

export declare interface HistoricalChange {}

export declare function HistoricalChange(props: {
    uptimeMillis: number;
    position: any;
  }): HistoricalChange;

export declare interface PointerButtons {}

export declare function PointerButtons(props: {
    packedValue: number;
  }): PointerButtons;

export declare interface PointerEvent {}

export declare function PointerEvent(props: {
    changes: Array<any>;
    internalPointerEvent: any;
  }): PointerEvent;

export declare const PointerEventPass: {
    readonly Initial: 'Initial';
    readonly Main: 'Main';
    readonly Final: 'Final';
  };

export declare type PointerEventPass = (typeof PointerEventPass)[keyof typeof PointerEventPass];

export declare interface PointerEventTimeoutCancellationException {}

export declare function PointerEventTimeoutCancellationException(props: {
    time: number;
  }): PointerEventTimeoutCancellationException;

export declare interface PointerId {}

export declare function PointerId(props: {
    value: number;
  }): PointerId;

export declare interface PointerInputChange {}

export declare function PointerInputChange(props: {
    id: any;
    uptimeMillis: number;
    position: any;
    pressed: boolean;
    pressure: number;
    previousUptimeMillis: number;
    previousPosition: any;
    previousPressed: boolean;
    isInitiallyConsumed: boolean;
    type?: any;
    scrollDelta?: any;
  }): PointerInputChange;

export declare interface PointerKeyboardModifiers {}

export declare function PointerKeyboardModifiers(props: {
    packedValue: number;
  }): PointerKeyboardModifiers;

export declare interface RequestDisallowInterceptTouchEvent {}

export declare function RequestDisallowInterceptTouchEvent(): RequestDisallowInterceptTouchEvent;

export declare interface VelocityTracker {}

export declare function VelocityTracker(): VelocityTracker;

export declare interface VelocityTracker1D {}

export declare function VelocityTracker1D(props: {
    isDataDifferential?: boolean;
    strategy?: any;
  }): VelocityTracker1D;

export declare interface RotaryScrollEvent {}

export declare function RotaryScrollEvent(props: {
    verticalScrollPixels: number;
    horizontalScrollPixels: number;
    uptimeMillis: number;
    inputDeviceId: number;
  }): RotaryScrollEvent;

export declare interface FixedScale {}

export declare function FixedScale(props: {
    value: number;
  }): FixedScale;

export declare interface HorizontalAlignmentLine {}

export declare function HorizontalAlignmentLine(props: {
    merger: (...args: any[]) => any;
  }): HorizontalAlignmentLine;

export declare interface ModifierInfo {}

export declare function ModifierInfo(props: {
    modifier: any;
    coordinates: any;
    extra?: any;
  }): ModifierInfo;

export declare interface ScaleFactor {}

export declare function ScaleFactor(props: {
    packedValue: number;
  }): ScaleFactor;

export declare interface SubcomposeLayoutState {}

export declare function SubcomposeLayoutState(props: {
    slotReusePolicy: any;
  }): SubcomposeLayoutState;

export declare interface TestModifierUpdater {}

export declare function TestModifierUpdater(props: {
    node: any;
  }): TestModifierUpdater;

export declare interface VerticalAlignmentLine {}

export declare function VerticalAlignmentLine(props: {
    merger: (...args: any[]) => any;
  }): VerticalAlignmentLine;

export declare interface ProvidableModifierLocal {}

export declare function ProvidableModifierLocal(props: {
    defaultFactory: (...args: any[]) => any;
  }): ProvidableModifierLocal;

export declare interface Ref {}

export declare function Ref(): Ref;

export declare interface AndroidUiFrameClock {}

export declare function AndroidUiFrameClock(props: {
    choreographer: any;
    dispatcher: any;
  }): AndroidUiFrameClock;

export declare interface AndroidUriHandler {}

export declare function AndroidUriHandler(props: {
    context: any;
  }): AndroidUriHandler;

export declare interface AndroidViewConfiguration {}

export declare function AndroidViewConfiguration(props: {
    viewConfiguration: any;
  }): AndroidViewConfiguration;

export declare interface ComposeView {}

export declare function ComposeView(props: {
    context: any;
    attrs?: any;
    defStyleAttr?: number;
  }): ComposeView;

export declare interface InspectableModifier {}

export declare function InspectableModifier(props: {
    inspectorInfo: (...args: any[]) => any;
  }): InspectableModifier;

export declare interface InspectorInfo {}

export declare function InspectorInfo(): InspectorInfo;

export declare const TextToolbarStatus: {
    readonly Shown: 'Shown';
    readonly Hidden: 'Hidden';
  };

export declare type TextToolbarStatus = (typeof TextToolbarStatus)[keyof typeof TextToolbarStatus];

export declare interface ValueElement {}

export declare function ValueElement(props: {
    name: string;
    value: any;
  }): ValueElement;

export declare interface ValueElementSequence {}

export declare function ValueElementSequence(): ValueElementSequence;

export declare interface ResourceResolutionException {}

export declare function ResourceResolutionException(props: {
    message: string;
    cause: any;
  }): ResourceResolutionException;

export declare interface AccessibilityAction {}

export declare function AccessibilityAction(props: {
    label: string;
    action: any;
  }): AccessibilityAction;

export declare interface CollectionInfo {}

export declare function CollectionInfo(props: {
    rowCount: number;
    columnCount: number;
  }): CollectionInfo;

export declare interface CollectionItemInfo {}

export declare function CollectionItemInfo(props: {
    rowIndex: number;
    rowSpan: number;
    columnIndex: number;
    columnSpan: number;
  }): CollectionItemInfo;

export declare interface CustomAccessibilityAction {}

export declare function CustomAccessibilityAction(props: {
    label: string;
    action: (...args: any[]) => any;
  }): CustomAccessibilityAction;

export declare interface ProgressBarRangeInfo {}

export declare function ProgressBarRangeInfo(props: {
    current: number;
    range: any;
    steps?: number;
  }): ProgressBarRangeInfo;

export declare interface ScrollAxisRange {}

export declare function ScrollAxisRange(props: {
    value: (...args: any[]) => any;
    maxValue: (...args: any[]) => any;
    reverseScrolling?: boolean;
  }): ScrollAxisRange;

export declare interface SemanticsConfiguration {}

export declare function SemanticsConfiguration(): SemanticsConfiguration;

export declare interface SemanticsNode {}

export declare function SemanticsNode(props: {
    outerSemanticsNode: any;
    mergingEnabled: boolean;
    layoutNode: any;
    unmergedConfig: any;
  }): SemanticsNode;

export declare interface SemanticsOwner {}

export declare function SemanticsOwner(props: {
    rootNode: any;
  }): SemanticsOwner;

export declare interface SemanticsPropertyKey {}

export declare function SemanticsPropertyKey(props: {
    name: string;
    mergePolicy?: (...args: any[]) => any;
  }): SemanticsPropertyKey;

export declare const ToggleableState: {
    readonly On: 'On';
    readonly Off: 'Off';
    readonly Indeterminate: 'Indeterminate';
  };

export declare type ToggleableState = (typeof ToggleableState)[keyof typeof ToggleableState];

export declare interface DialogProperties {}

export declare function DialogProperties(props: {
    dismissOnBackPress?: boolean;
    dismissOnClickOutside?: boolean;
    securePolicy?: 'Inherit' | 'SecureOn' | 'SecureOff';
    usePlatformDefaultWidth?: boolean;
    decorFitsSystemWindows?: boolean;
  }): DialogProperties;

export declare interface PopupProperties {}

export declare function PopupProperties(props: {
    focusable?: boolean;
    dismissOnBackPress?: boolean;
    dismissOnClickOutside?: boolean;
    securePolicy?: 'Inherit' | 'SecureOn' | 'SecureOff';
    excludeFromSystemGesture?: boolean;
    clippingEnabled?: boolean;
    usePlatformDefaultWidth?: boolean;
  }): PopupProperties;

export declare const SecureFlagPolicy: {
    readonly Inherit: 'Inherit';
    readonly SecureOn: 'SecureOn';
    readonly SecureOff: 'SecureOff';
  };

export declare type SecureFlagPolicy = (typeof SecureFlagPolicy)[keyof typeof SecureFlagPolicy];

export declare const Group: any;

export declare const Path: any;

export declare const RenderVectorGroup: any;

export declare const Layout: any;

export declare const MultiMeasureLayout: any;

export declare const LookaheadScope: any;

export declare const SubcomposeLayout: any;

export declare const TestModifierUpdaterLayout: any;

export declare const Dialog: any;

export declare const Popup: any;
