// Generated by vesk-native from vico.vsklib — do not edit by hand.
// Type surface for the `@vesk/vico` virtual module (Vico 1.14.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const Chart: any;

export declare const lineChart: any;

export declare const columnChart: any;
