// Generated by vesk-native from viewmodel-compose.vsklib — do not edit by hand.
// Type surface for the `@vesk/viewmodel-compose` virtual module (AndroidX Lifecycle ViewModel Compose 2.8.2).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.


