// Generated by vesk-native from workmanager.vsklib — do not edit by hand.
// Type surface for the `@vesk/workmanager` virtual module (WorkManager 2.9.1).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare const WorkManager: any;

export declare const OneTimeWorkRequest: any;
