// Generated by vesk-native from ycharts.vsklib — do not edit by hand.
// Type surface for the `@vesk/ycharts` virtual module (YCharts 2.1.0).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.
// Markup tags: <YLineChart>.

export declare interface AxisConfig {}

export declare function AxisConfig(props: {
    isAxisLineRequired?: boolean;
    shouldEllipsizeAxisLabel?: boolean;
    minTextWidthToEllipsize?: any;
    ellipsizeAt?: any;
  }): AxisConfig;

export declare interface AxisData {}

export declare function AxisData(props: {
    steps: number;
    labelData: (...args: any[]) => any;
    axisPos: 'TOP' | 'LEFT' | 'RIGHT' | 'BOTTOM';
    labelAndAxisLinePadding: any;
    axisOffset: any;
    axisTopPadding: any;
    axisBottomPadding: any;
    axisStartPadding: any;
    axisEndPadding: any;
    axisStepSize: any;
    axisLabelAngle: number;
    axisLineColor: any;
    axisLabelColor: any;
    axisLabelFontSize: any;
    axisLineThickness: any;
    indicatorLineWidth: any;
    backgroundColor: any;
    typeface: any;
    axisConfig: any;
    startDrawPadding: any;
    shouldDrawAxisLineTillEnd: boolean;
    axisLabelDescription: (...args: any[]) => any;
    dataCategoryOptions: any;
  }): AxisData;

export declare interface DataCategoryOptions {}

export declare function DataCategoryOptions(props: {
    isDataCategoryInYAxis?: boolean;
    isDataCategoryStartFromBottom?: boolean;
  }): DataCategoryOptions;

export declare const Gravity: {
    readonly TOP: 'TOP';
    readonly LEFT: 'LEFT';
    readonly RIGHT: 'RIGHT';
    readonly BOTTOM: 'BOTTOM';
  };

export declare type Gravity = (typeof Gravity)[keyof typeof Gravity];

export declare interface AccessibilityConfig {}

export declare function AccessibilityConfig(props: {
    chartDescription?: string;
    shouldHandleBackWhenTalkBackPopUpShown?: boolean;
    popUpTopRightButtonTitle?: string;
    popUpTopRightButtonDescription?: string;
    dividerColor?: any;
    dividerThickness?: any;
    titleTextSize?: any;
    descriptionTextSize?: any;
  }): AccessibilityConfig;

export declare interface LegendLabel {}

export declare function LegendLabel(props: {
    color?: any;
    name?: string;
    brush?: any;
  }): LegendLabel;

export declare interface LegendsConfig {}

export declare function LegendsConfig(props: {
    legendLabelList: Array<any>;
    textSize?: any;
    gridColumnCount?: number;
    gridPaddingHorizontal?: any;
    gridPaddingVertical?: any;
    colorBoxSize?: any;
    textStyle?: any;
    spaceBWLabelAndColorBox?: any;
    legendsArrangement?: any;
  }): LegendsConfig;

export declare const PlotType: {
    readonly Bar: 'Bar';
    readonly Donut: 'Donut';
    readonly Line: 'Line';
    readonly Pie: 'Pie';
    readonly Wave: 'Wave';
  };

export declare type PlotType = (typeof PlotType)[keyof typeof PlotType];

export declare interface Point {}

export declare function Point(props: {
    x: number;
    y: number;
    description?: string;
  }): Point;

export declare interface BarChartData {}

export declare function BarChartData(props: {
    chartData: Array<any>;
    xAxisData?: any;
    yAxisData?: any;
    backgroundColor?: any;
    horizontalExtraSpace?: any;
    barStyle?: any;
    paddingEnd?: any;
    paddingTop?: any;
    tapPadding?: any;
    showYAxis?: boolean;
    showXAxis?: boolean;
    accessibilityConfig?: any;
    barChartType?: 'VERTICAL' | 'HORIZONTAL';
    drawBar?: (...args: any[]) => any;
  }): BarChartData;

export declare const BarChartType: {
    readonly VERTICAL: 'VERTICAL';
    readonly HORIZONTAL: 'HORIZONTAL';
  };

export declare type BarChartType = (typeof BarChartType)[keyof typeof BarChartType];

export declare interface BarData {}

export declare function BarData(props: {
    point: any;
    color?: any;
    label?: string;
    gradientColorList?: Array<any>;
    dataCategoryOptions?: any;
    description?: string;
  }): BarData;

export declare interface BarPlotData {}

export declare function BarPlotData(props: {
    plotType?: 'Bar' | 'Donut' | 'Line' | 'Pie' | 'Wave';
    groupBarList?: Array<any>;
    groupingSize?: number;
    barColorPaletteList?: Array<any>;
    barStyle?: any;
  }): BarPlotData;

export declare interface BarStyle {}

export declare function BarStyle(props: {
    barWidth?: any;
    cornerRadius?: any;
    paddingBetweenBars?: any;
    isGradientEnabled?: boolean;
    barBlendMode?: any;
    barDrawStyle?: any;
    selectionHighlightData?: any;
  }): BarStyle;

export declare interface GroupBar {}

export declare function GroupBar(props: {
    label: string;
    barList: Array<any>;
  }): GroupBar;

export declare interface GroupBarChartData {}

export declare function GroupBarChartData(props: {
    barPlotData: any;
    xAxisData?: any;
    yAxisData?: any;
    backgroundColor?: any;
    horizontalExtraSpace?: any;
    paddingEnd?: any;
    paddingTop?: any;
    showYAxis?: boolean;
    showXAxis?: boolean;
    tapPadding?: any;
    groupSeparatorConfig?: any;
    accessibilityConfig?: any;
    paddingBetweenStackedBars?: any;
    drawBar?: (...args: any[]) => any;
  }): GroupBarChartData;

export declare interface GroupSeparatorConfig {}

export declare function GroupSeparatorConfig(props: {
    separatorWidth?: any;
    separatorColor?: any;
    showSeparator?: boolean;
    separatorBlendMode?: any;
  }): GroupSeparatorConfig;

export declare interface SelectionHighlightData {}

export declare function SelectionHighlightData(props: {
    highlightTextOffset?: any;
    highlightTextSize?: any;
    highlightTextColor?: any;
    highlightTextBackgroundColor?: any;
    highlightTextBackgroundAlpha?: number;
    highlightTextTypeface?: any;
    highlightBarCornerRadius?: any;
    highlightBarColor?: any;
    highlightBarStrokeWidth?: any;
    highlightPopUpCornerRadius?: any;
    backgroundColorFilter?: any;
    backgroundBlendMode?: any;
    backgroundStyle?: any;
    highlightLabelAlignment?: any;
    isHighlightBarRequired?: boolean;
    isHighlightFullBar?: boolean;
    popUpLabel?: (...args: any[]) => any;
    drawPopUp?: (...args: any[]) => any;
    drawHighlightBar?: (...args: any[]) => any;
    groupBarPopUpLabel?: (...args: any[]) => any;
    drawGroupBarPopUp?: (...args: any[]) => any;
    barChartType?: 'VERTICAL' | 'HORIZONTAL';
  }): SelectionHighlightData;

export declare interface Bubble {}

export declare function Bubble(props: {
    center: any;
    density: number;
    bubbleStyle?: any;
    intersectionPoint?: any;
    selectionHighlightPoint?: any;
    selectionHighlightPopUp?: any;
    draw?: (...args: any[]) => any;
  }): Bubble;

export declare interface BubbleChartData {}

export declare function BubbleChartData(props: {
    bubbles: Array<any>;
    maximumBubbleRadius?: number;
    xAxisData?: any;
    yAxisData?: any;
    isZoomAllowed?: boolean;
    paddingTop?: any;
    bottomPadding?: any;
    paddingRight?: any;
    containerPaddingEnd?: any;
    backgroundColor?: any;
    gridLines?: any;
    accessibilityConfig?: any;
  }): BubbleChartData;

export declare const BubbleGradientType: {
    readonly HorizontalGradient: 'HorizontalGradient';
    readonly LinearGradient: 'LinearGradient';
    readonly RadialGradient: 'RadialGradient';
    readonly VerticalGradient: 'VerticalGradient';
  };

export declare type BubbleGradientType = (typeof BubbleGradientType)[keyof typeof BubbleGradientType];

export declare interface BubbleStyle {}

export declare function BubbleStyle(props: {
    gradientColors?: Array<any>;
    gradientType?: 'HorizontalGradient' | 'LinearGradient' | 'RadialGradient' | 'VerticalGradient';
    tileMode?: any;
    useGradience?: boolean;
    solidColor?: any;
    width?: number;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
  }): BubbleStyle;

export declare interface CombinedChartData {}

export declare function CombinedChartData(props: {
    combinedPlotDataList: Array<any>;
    xAxisData?: any;
    yAxisData?: any;
    paddingTop?: any;
    bottomPadding?: any;
    paddingEnd?: any;
    horizontalExtraSpace?: any;
    containerPaddingEnd?: any;
    backgroundColor?: any;
    tapPadding?: any;
    isZoomAllowed?: boolean;
    accessibilityConfig?: any;
  }): CombinedChartData;

export declare interface GridLines {}

export declare function GridLines(props: {
    color?: any;
    lineWidth?: any;
    pathEffect?: any;
    alpha?: number;
    colorFilter?: any;
    blendMode?: any;
    enableHorizontalLines?: boolean;
    enableVerticalLines?: boolean;
    drawHorizontalLines?: (...args: any[]) => any;
    drawVerticalLines?: (...args: any[]) => any;
  }): GridLines;

export declare interface IntersectionPoint {}

export declare function IntersectionPoint(props: {
    color?: any;
    radius?: any;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
    draw?: (...args: any[]) => any;
  }): IntersectionPoint;

export declare interface Line {}

export declare function Line(props: {
    dataPoints: Array<any>;
    lineStyle?: any;
    intersectionPoint?: any;
    selectionHighlightPoint?: any;
    shadowUnderLine?: any;
    selectionHighlightPopUp?: any;
  }): Line;

export declare interface LineChartData {}

export declare function LineChartData(props: {
    linePlotData: any;
    xAxisData?: any;
    yAxisData?: any;
    isZoomAllowed?: boolean;
    paddingTop?: any;
    bottomPadding?: any;
    paddingRight?: any;
    containerPaddingEnd?: any;
    backgroundColor?: any;
    gridLines?: any;
    accessibilityConfig?: any;
  }): LineChartData;

export declare interface LinePlotData {}

export declare function LinePlotData(props: {
    plotType?: 'Bar' | 'Donut' | 'Line' | 'Pie' | 'Wave';
    lines?: Array<any>;
  }): LinePlotData;

export declare interface LineStyle {}

export declare function LineStyle(props: {
    lineType?: any;
    color?: any;
    width?: number;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
  }): LineStyle;

export declare interface SelectionHighlightPoint {}

export declare function SelectionHighlightPoint(props: {
    color?: any;
    radius?: any;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
    draw?: (...args: any[]) => any;
    isHighlightLineRequired?: boolean;
    drawHighlightLine?: (...args: any[]) => any;
  }): SelectionHighlightPoint;

export declare interface SelectionHighlightPopUp {}

export declare function SelectionHighlightPopUp(props: {
    backgroundColor?: any;
    backgroundAlpha?: number;
    backgroundCornerRadius?: any;
    backgroundColorFilter?: any;
    backgroundBlendMode?: any;
    backgroundStyle?: any;
    paddingBetweenPopUpAndPoint?: any;
    labelSize?: any;
    labelColor?: any;
    labelAlignment?: any;
    labelTypeface?: any;
    popUpLabel?: (...args: any[]) => any;
    draw?: (...args: any[]) => any;
  }): SelectionHighlightPopUp;

export declare interface ShadowUnderLine {}

export declare function ShadowUnderLine(props: {
    color?: any;
    brush?: any;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
    draw?: (...args: any[]) => any;
    drawMultiColor?: (...args: any[]) => any;
  }): ShadowUnderLine;

export declare interface PieChartConfig {}

export declare function PieChartConfig(props: {
    startAngle?: number;
    showSliceLabels?: boolean;
    sliceLabelTextSize?: any;
    sliceLabelTextColor?: any;
    sliceLabelTypeface?: any;
    isAnimationEnable?: boolean;
    animationDuration?: number;
    strokeWidth?: number;
    labelFontSize?: any;
    labelTypeface?: any;
    labelVisible?: boolean;
    labelType?: any;
    labelColor?: any;
    labelColorType?: any;
    backgroundColor?: any;
    activeSliceAlpha?: number;
    inActiveSliceAlpha?: number;
    isEllipsizeEnabled?: boolean;
    sliceMinTextWidthToEllipsize?: any;
    sliceLabelEllipsizeAt?: any;
    chartPadding?: number;
    accessibilityConfig?: any;
    isSumVisible?: boolean;
    sumUnit?: string;
    isClickOnSliceEnabled?: boolean;
  }): PieChartConfig;

export declare interface PieChartData {}

export declare function PieChartData(props: {
    slices: Array<any>;
    plotType: 'Bar' | 'Donut' | 'Line' | 'Pie' | 'Wave';
  }): PieChartData;

export declare const AxisPosition: {
    readonly TOP: 'TOP';
    readonly BOTTOM: 'BOTTOM';
    readonly INTERSECT: 'INTERSECT';
  };

export declare type AxisPosition = (typeof AxisPosition)[keyof typeof AxisPosition];

export declare interface Wave {}

export declare function Wave(props: {
    dataPoints: Array<any>;
    waveStyle?: any;
    intersectionPoint?: any;
    selectionHighlightPoint?: any;
    shadowUnderLine?: any;
    selectionHighlightPopUp?: any;
    waveFillColor?: any;
  }): Wave;

export declare interface WaveChartData {}

export declare function WaveChartData(props: {
    wavePlotData: any;
    xAxisData?: any;
    yAxisData?: any;
    isZoomAllowed?: boolean;
    paddingTop?: any;
    bottomPadding?: any;
    paddingRight?: any;
    containerPaddingEnd?: any;
    backgroundColor?: any;
    gridLines?: any;
    accessibilityConfig?: any;
  }): WaveChartData;

export declare interface WaveFillColor {}

export declare function WaveFillColor(props: {
    topColor?: any;
    bottomColor?: any;
    topBrush?: any;
    bottomBrush?: any;
  }): WaveFillColor;

export declare interface WavePlotData {}

export declare function WavePlotData(props: {
    plotType?: 'Bar' | 'Donut' | 'Line' | 'Pie' | 'Wave';
    lines?: Array<any>;
  }): WavePlotData;

export declare const YLineChart: any;
