// Generated by vesk-native from zxing.vsklib — do not edit by hand.
// Type surface for the `@vesk/zxing` virtual module (ZXing Core 3.5.3).
// Regenerate with packages/cli-native/src/metadata/regenerate-typings.ts.
// The compiler resolves these names from the .vsklib record, not this file.

export declare interface QRCodeWriter {}

/**

 * Encodes QR codes. QRCodeWriter().encode(content, format, width, height) returns a BitMatrix.

 */

export declare function QRCodeWriter(): QRCodeWriter;

export declare interface QRCodeReader {}

/**

 * Decodes QR codes. QRCodeReader().decode(binaryBitmap) returns a Result.

 */

export declare function QRCodeReader(): QRCodeReader;

export declare const BarcodeFormat: any;
