export {
  defineConfig,
  type VeskColors,
  type VeskTypography,
  type VeskThemeMode,
  type VeskBack,
  type VeskRoute,
  type VeskConfig,
  type VeskSigning,
  type VeskAndroidSigning,
  type VeskIosSigning,
  type VeskIosBundle,
  type VeskBundle,
  type VeskIcon,
  type VeskSplash,
} from './config.ts';