package app

import app.data_flights_airports as airports
import app.data_flights_trendingFlights as trendingFlights
import app.data_flights_nearFlights as nearFlights
import app.data_flights_flights as flights
import app.data_flights_flightById as flightById

val data_flights_airports = listOf(mutableMapOf<String, Any?>("code" to "CDG", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), mutableMapOf<String, Any?>("code" to "PRG", "city" to "Prague", "country" to "Czechia", "timezone" to "UTC +01:00"), mutableMapOf<String, Any?>("code" to "ORY", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), mutableMapOf<String, Any?>("code" to "DJE", "city" to "Djerba", "country" to "Tunisia", "timezone" to "UTC +01:00"), mutableMapOf<String, Any?>("code" to "BVA", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), mutableMapOf<String, Any?>("code" to "BCN", "city" to "Barcelona", "country" to "Spain", "timezone" to "UTC +02:00"), mutableMapOf<String, Any?>("code" to "JFK", "city" to "New York", "country" to "United States", "timezone" to "UTC −04:00"), mutableMapOf<String, Any?>("code" to "LIS", "city" to "Lisbon", "country" to "Portugal", "timezone" to "UTC +01:00"), mutableMapOf<String, Any?>("code" to "FCO", "city" to "Rome", "country" to "Italy", "timezone" to "UTC +02:00"), mutableMapOf<String, Any?>("code" to "RAK", "city" to "Marrakech", "country" to "Morocco", "timezone" to "UTC +01:00"), mutableMapOf<String, Any?>("code" to "LHR", "city" to "London", "country" to "United Kingdom", "timezone" to "UTC +01:00"));
val data_flights_trendingFlights = listOf(mutableMapOf<String, Any?>("id" to "tvs2dz", "flightNumber" to "TVS2DZ", "secondary" to "TO6488", "aircraft" to "B738", "airline" to "Transavia", "from" to mutableMapOf<String, Any?>("code" to "CDG", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), "to" to mutableMapOf<String, Any?>("code" to "PRG", "city" to "Prague", "country" to "Czechia", "timezone" to "UTC +01:00"), "status" to "Boarding", "scheduledDeparture" to "3:00 PM", "actualDeparture" to "3:24 PM", "scheduledArrival" to "4:45 PM", "estimatedArrival" to "4:42 PM", "progress" to 0.35), mutableMapOf<String, Any?>("id" to "tvf6474", "flightNumber" to "TVF6474", "secondary" to "TO6474", "aircraft" to "B738", "airline" to "Transavia", "from" to mutableMapOf<String, Any?>("code" to "ORY", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), "to" to mutableMapOf<String, Any?>("code" to "DJE", "city" to "Djerba", "country" to "Tunisia", "timezone" to "UTC +01:00"), "status" to "En route", "scheduledDeparture" to "2:20 PM", "actualDeparture" to "2:41 PM", "scheduledArrival" to "5:35 PM", "estimatedArrival" to "5:28 PM", "progress" to 0.4), mutableMapOf<String, Any?>("id" to "afr1821", "flightNumber" to "AFR1821", "secondary" to "AF1821", "aircraft" to "A320", "airline" to "Air France", "from" to mutableMapOf<String, Any?>("code" to "CDG", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), "to" to mutableMapOf<String, Any?>("code" to "JFK", "city" to "New York", "country" to "United States", "timezone" to "UTC −04:00"), "status" to "En route", "scheduledDeparture" to "1:10 PM", "actualDeparture" to "1:32 PM", "scheduledArrival" to "3:55 PM", "estimatedArrival" to "3:47 PM", "progress" to 0.65), mutableMapOf<String, Any?>("id" to "tui7761", "flightNumber" to "TUI7761", "secondary" to "TO7761", "aircraft" to "B38M", "airline" to "TUI", "from" to mutableMapOf<String, Any?>("code" to "ORY", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), "to" to mutableMapOf<String, Any?>("code" to "RAK", "city" to "Marrakech", "country" to "Morocco", "timezone" to "UTC +01:00"), "status" to "Landed", "scheduledDeparture" to "10:15 AM", "actualDeparture" to "10:09 AM", "scheduledArrival" to "1:05 PM", "estimatedArrival" to "12:58 PM", "progress" to 1.0));
val data_flights_nearFlights = listOf(mutableMapOf<String, Any?>("id" to "ryr642n", "flightNumber" to "RYR642N", "secondary" to "FR3122", "aircraft" to "B38M", "airline" to "Ryanair", "from" to mutableMapOf<String, Any?>("code" to "BVA", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), "to" to mutableMapOf<String, Any?>("code" to "BCN", "city" to "Barcelona", "country" to "Spain", "timezone" to "UTC +02:00"), "status" to "En route", "scheduledDeparture" to "4:05 PM", "actualDeparture" to "4:11 PM", "scheduledArrival" to "6:00 PM", "estimatedArrival" to "5:52 PM", "progress" to 0.55), mutableMapOf<String, Any?>("id" to "ryr7839", "flightNumber" to "RYR7839", "secondary" to "FR4134", "aircraft" to "B738", "airline" to "Ryanair", "from" to mutableMapOf<String, Any?>("code" to "BVA", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), "to" to mutableMapOf<String, Any?>("code" to "LIS", "city" to "Lisbon", "country" to "Portugal", "timezone" to "UTC +01:00"), "status" to "En route", "scheduledDeparture" to "2:55 PM", "actualDeparture" to "3:07 PM", "scheduledArrival" to "5:10 PM", "estimatedArrival" to "5:03 PM", "progress" to 0.2), mutableMapOf<String, Any?>("id" to "ezy4556", "flightNumber" to "EZY4556", "secondary" to "U25567", "aircraft" to "A320", "airline" to "easyJet", "from" to mutableMapOf<String, Any?>("code" to "CDG", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), "to" to mutableMapOf<String, Any?>("code" to "FCO", "city" to "Rome", "country" to "Italy", "timezone" to "UTC +02:00"), "status" to "On time", "scheduledDeparture" to "5:30 PM", "actualDeparture" to "—", "scheduledArrival" to "7:35 PM", "estimatedArrival" to "7:35 PM", "progress" to 0.05), mutableMapOf<String, Any?>("id" to "baw345", "flightNumber" to "BAW345", "secondary" to "BA334", "aircraft" to "A320", "airline" to "British Airways", "from" to mutableMapOf<String, Any?>("code" to "CDG", "city" to "Paris", "country" to "France", "timezone" to "UTC +01:00"), "to" to mutableMapOf<String, Any?>("code" to "LHR", "city" to "London", "country" to "United Kingdom", "timezone" to "UTC +01:00"), "status" to "On time", "scheduledDeparture" to "6:20 PM", "actualDeparture" to "—", "scheduledArrival" to "6:45 PM", "estimatedArrival" to "6:45 PM", "progress" to 0.0));
val data_flights_flights = listOf(*(trendingFlights as List<*>).toTypedArray(), *(nearFlights as List<*>).toTypedArray());
fun data_flights_flightById(id: String): Any? = run<Any?> __veskfn0@ {
return@__veskfn0 (flights.find { f -> jsIndex(f, "id") == id } ?: null);
}
