// Generated by vesk-native. The vesk browser-API globals (openSqlite,
// signUp/signIn/signOut/currentUser/isSignedIn + their interfaces) augment the
// global scope here so they resolve without imports; standard browser globals
// keep their DOM-lib types. Regenerated on every build. Do not edit by hand.

declare global {
  declare interface VeskResponse {
    /** The request URL, verbatim. */
    readonly url: string;
    /** HTTP status code; 0 on network failure (no response received). */
    readonly status: number;
    /** HTTP reason phrase; 'Network error' when the request failed. */
    readonly statusText: string;
    /** True when status is 200-299. */
    readonly ok: boolean;
    /** Response headers as sent by the server (runtime Map<String, String>). */
    readonly headers: Record<string, string>;
    /** The response body as text. */
    text(): string;
    /** The response body parsed as JSON (JSON.parse semantics; throws on invalid JSON). */
    json(): any;
  }
  
  /** Options for fetch(). Runtime reads these keys from a plain object via
   * jsMapGet; everything else is ignored. */
  declare interface FetchInit {
    /** HTTP method; default 'GET'. GET/HEAD never send a body. */
    method?: string;
    /** Request headers as a plain object. */
    headers?: Record<string, string>;
    /** Request body; sent as UTF-8 text (only for non-GET/HEAD). */
    body?: string;
  }
  
  /** Native SQLite handle from openSqlite(). Maps to the VeskSqliteDb class in
   * the runtime — a better-sqlite3-style surface. Handles are cached per
   * database name for the process lifetime, so repeated openSqlite(name) calls
   * return the same handle. */
  declare interface VeskSqliteDb {
    /** Run a statement with no result (CREATE TABLE, DROP, ...). */
    exec(sql: string): void;
    /** Run an INSERT/UPDATE/DELETE and report lastInsertRowid + changes (0 when the db is closed). */
    run(sql: string, params?: any[]): { lastInsertRowid: number; changes: number };
    /** First row of the query, or null when there are no rows. */
    get(sql: string, params?: any[]): Record<string, any> | null;
    /** All rows of the query as a list of plain objects. */
    all(sql: string, params?: any[]): Record<string, any>[];
    /** Close the handle; later calls return empty results (no-op). */
    close(): void;
  }
  
  /** Web Storage (localStorage / sessionStorage). Values are stored as strings
   * (null stores the literal string 'null'); getItem returns null for missing
   * keys; key(i) is the i-th key or null. localStorage persists across app
   * restarts (SharedPreferences), sessionStorage lives only for the process. */
  declare interface WebStorage {
    /** Number of keys. */
    readonly length: number;
    /** The stored string for key, or null when missing. */
    getItem(key: string): string | null;
    /** Store a value as a string (null becomes 'null'). */
    setItem(key: string, value: string): void;
    /** Remove key. */
    removeItem(key: string): void;
    /** Remove all keys. */
    clear(): void;
    /** The key at index, or null when out of range (localStorage keys are sorted). */
    key(index: number): string | null;
  }
  
  /** The mapped subset of the window global. Only these members compile to
   * native Kotlin; anything else is a hard build error. */
  /** Open (or reuse) a native SQLite database (runtime VeskSqlite).
   * Handles are cached per name for the process lifetime; version only applies
   * on first open. Rows are plain objects with integer/real/string/blob column
   * values; params bind positionally to ? placeholders (booleans bind as 1/0). */
  declare function openSqlite(name: string, version?: number): VeskSqliteDb;
  /** Create a user in the native vesk_auth database (runtime VeskAuth).
   * Returns the user row { id, username } or null when the username is taken or
   * either value is empty. Passwords are stored as a SHA-256 hash of
   * "username:password" in native sqlite — never a JS shim. */
  declare function signUp(username: string, password: string): Record<string, any> | null;
  /** Sign in and persist the session in localStorage so it survives app
   * restarts (runtime VeskAuth). Returns the user row { id, username } or null
   * on bad credentials. */
  declare function signIn(username: string, password: string): Record<string, any> | null;
  /** Clear the persisted session (runtime VeskAuth.signOut). */
  declare function signOut(): void;
  /** The signed-in user row { id, username } or null when signed out
   * (runtime VeskAuth.currentUser). */
  declare function currentUser(): Record<string, any> | null;
  /** True when a session is persisted and its user still exists
   * (runtime VeskAuth.isSignedIn). */
  declare function isSignedIn(): boolean;
}

// Makes this file a module so the declare-global surface above actually
// augments the global scope.
export {};
