// Generated by vesk-native from libraries.json. The @vesk/* imports the
// compiler resolves at build time are virtual modules with no npm package, so
// editors, LSP and tsc resolve them against these ambient declarations.
// Regenerated on every build and after 'vesk add/remove/update'.
// Do not edit by hand.

declare module '@vesk/coil' {
  export declare const AsyncImage: any;
  export declare const rememberAsyncImagePainter: any;
  export declare const CoilImage: any;
}

declare module '@vesk/ycharts' {
  export declare interface AxisConfig {}
  export declare function AxisConfig(props: {
    isAxisLineRequired?: boolean;
    shouldEllipsizeAxisLabel?: boolean;
    minTextWidthToEllipsize?: any;
    ellipsizeAt?: any;
  }): AxisConfig;
  export declare interface AxisData {}
  export declare function AxisData(props: {
    steps: number;
    labelData: (...args: any[]) => any;
    axisPos: 'TOP' | 'LEFT' | 'RIGHT' | 'BOTTOM';
    labelAndAxisLinePadding: any;
    axisOffset: any;
    axisTopPadding: any;
    axisBottomPadding: any;
    axisStartPadding: any;
    axisEndPadding: any;
    axisStepSize: any;
    axisLabelAngle: number;
    axisLineColor: any;
    axisLabelColor: any;
    axisLabelFontSize: any;
    axisLineThickness: any;
    indicatorLineWidth: any;
    backgroundColor: any;
    typeface: any;
    axisConfig: any;
    startDrawPadding: any;
    shouldDrawAxisLineTillEnd: boolean;
    axisLabelDescription: (...args: any[]) => any;
    dataCategoryOptions: any;
  }): AxisData;
  export declare interface DataCategoryOptions {}
  export declare function DataCategoryOptions(props: {
    isDataCategoryInYAxis?: boolean;
    isDataCategoryStartFromBottom?: boolean;
  }): DataCategoryOptions;
  export declare const Gravity: {
    readonly TOP: 'TOP';
    readonly LEFT: 'LEFT';
    readonly RIGHT: 'RIGHT';
    readonly BOTTOM: 'BOTTOM';
  };
  export declare type Gravity = (typeof Gravity)[keyof typeof Gravity];
  export declare interface AccessibilityConfig {}
  export declare function AccessibilityConfig(props: {
    chartDescription?: string;
    shouldHandleBackWhenTalkBackPopUpShown?: boolean;
    popUpTopRightButtonTitle?: string;
    popUpTopRightButtonDescription?: string;
    dividerColor?: any;
    dividerThickness?: any;
    titleTextSize?: any;
    descriptionTextSize?: any;
  }): AccessibilityConfig;
  export declare interface LegendLabel {}
  export declare function LegendLabel(props: {
    color?: any;
    name?: string;
    brush?: any;
  }): LegendLabel;
  export declare interface LegendsConfig {}
  export declare function LegendsConfig(props: {
    legendLabelList: Array<any>;
    textSize?: any;
    gridColumnCount?: number;
    gridPaddingHorizontal?: any;
    gridPaddingVertical?: any;
    colorBoxSize?: any;
    textStyle?: any;
    spaceBWLabelAndColorBox?: any;
    legendsArrangement?: any;
  }): LegendsConfig;
  export declare const PlotType: {
    readonly Bar: 'Bar';
    readonly Donut: 'Donut';
    readonly Line: 'Line';
    readonly Pie: 'Pie';
    readonly Wave: 'Wave';
  };
  export declare type PlotType = (typeof PlotType)[keyof typeof PlotType];
  export declare interface Point {}
  export declare function Point(props: {
    x: number;
    y: number;
    description?: string;
  }): Point;
  export declare interface BarChartData {}
  export declare function BarChartData(props: {
    chartData: Array<any>;
    xAxisData?: any;
    yAxisData?: any;
    backgroundColor?: any;
    horizontalExtraSpace?: any;
    barStyle?: any;
    paddingEnd?: any;
    paddingTop?: any;
    tapPadding?: any;
    showYAxis?: boolean;
    showXAxis?: boolean;
    accessibilityConfig?: any;
    barChartType?: 'VERTICAL' | 'HORIZONTAL';
    drawBar?: (...args: any[]) => any;
  }): BarChartData;
  export declare const BarChartType: {
    readonly VERTICAL: 'VERTICAL';
    readonly HORIZONTAL: 'HORIZONTAL';
  };
  export declare type BarChartType = (typeof BarChartType)[keyof typeof BarChartType];
  export declare interface BarData {}
  export declare function BarData(props: {
    point: any;
    color?: any;
    label?: string;
    gradientColorList?: Array<any>;
    dataCategoryOptions?: any;
    description?: string;
  }): BarData;
  export declare interface BarPlotData {}
  export declare function BarPlotData(props: {
    plotType?: 'Bar' | 'Donut' | 'Line' | 'Pie' | 'Wave';
    groupBarList?: Array<any>;
    groupingSize?: number;
    barColorPaletteList?: Array<any>;
    barStyle?: any;
  }): BarPlotData;
  export declare interface BarStyle {}
  export declare function BarStyle(props: {
    barWidth?: any;
    cornerRadius?: any;
    paddingBetweenBars?: any;
    isGradientEnabled?: boolean;
    barBlendMode?: any;
    barDrawStyle?: any;
    selectionHighlightData?: any;
  }): BarStyle;
  export declare interface GroupBar {}
  export declare function GroupBar(props: {
    label: string;
    barList: Array<any>;
  }): GroupBar;
  export declare interface GroupBarChartData {}
  export declare function GroupBarChartData(props: {
    barPlotData: any;
    xAxisData?: any;
    yAxisData?: any;
    backgroundColor?: any;
    horizontalExtraSpace?: any;
    paddingEnd?: any;
    paddingTop?: any;
    showYAxis?: boolean;
    showXAxis?: boolean;
    tapPadding?: any;
    groupSeparatorConfig?: any;
    accessibilityConfig?: any;
    paddingBetweenStackedBars?: any;
    drawBar?: (...args: any[]) => any;
  }): GroupBarChartData;
  export declare interface GroupSeparatorConfig {}
  export declare function GroupSeparatorConfig(props: {
    separatorWidth?: any;
    separatorColor?: any;
    showSeparator?: boolean;
    separatorBlendMode?: any;
  }): GroupSeparatorConfig;
  export declare interface SelectionHighlightData {}
  export declare function SelectionHighlightData(props: {
    highlightTextOffset?: any;
    highlightTextSize?: any;
    highlightTextColor?: any;
    highlightTextBackgroundColor?: any;
    highlightTextBackgroundAlpha?: number;
    highlightTextTypeface?: any;
    highlightBarCornerRadius?: any;
    highlightBarColor?: any;
    highlightBarStrokeWidth?: any;
    highlightPopUpCornerRadius?: any;
    backgroundColorFilter?: any;
    backgroundBlendMode?: any;
    backgroundStyle?: any;
    highlightLabelAlignment?: any;
    isHighlightBarRequired?: boolean;
    isHighlightFullBar?: boolean;
    popUpLabel?: (...args: any[]) => any;
    drawPopUp?: (...args: any[]) => any;
    drawHighlightBar?: (...args: any[]) => any;
    groupBarPopUpLabel?: (...args: any[]) => any;
    drawGroupBarPopUp?: (...args: any[]) => any;
    barChartType?: 'VERTICAL' | 'HORIZONTAL';
  }): SelectionHighlightData;
  export declare interface Bubble {}
  export declare function Bubble(props: {
    center: any;
    density: number;
    bubbleStyle?: any;
    intersectionPoint?: any;
    selectionHighlightPoint?: any;
    selectionHighlightPopUp?: any;
    draw?: (...args: any[]) => any;
  }): Bubble;
  export declare interface BubbleChartData {}
  export declare function BubbleChartData(props: {
    bubbles: Array<any>;
    maximumBubbleRadius?: number;
    xAxisData?: any;
    yAxisData?: any;
    isZoomAllowed?: boolean;
    paddingTop?: any;
    bottomPadding?: any;
    paddingRight?: any;
    containerPaddingEnd?: any;
    backgroundColor?: any;
    gridLines?: any;
    accessibilityConfig?: any;
  }): BubbleChartData;
  export declare const BubbleGradientType: {
    readonly HorizontalGradient: 'HorizontalGradient';
    readonly LinearGradient: 'LinearGradient';
    readonly RadialGradient: 'RadialGradient';
    readonly VerticalGradient: 'VerticalGradient';
  };
  export declare type BubbleGradientType = (typeof BubbleGradientType)[keyof typeof BubbleGradientType];
  export declare interface BubbleStyle {}
  export declare function BubbleStyle(props: {
    gradientColors?: Array<any>;
    gradientType?: 'HorizontalGradient' | 'LinearGradient' | 'RadialGradient' | 'VerticalGradient';
    tileMode?: any;
    useGradience?: boolean;
    solidColor?: any;
    width?: number;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
  }): BubbleStyle;
  export declare interface CombinedChartData {}
  export declare function CombinedChartData(props: {
    combinedPlotDataList: Array<any>;
    xAxisData?: any;
    yAxisData?: any;
    paddingTop?: any;
    bottomPadding?: any;
    paddingEnd?: any;
    horizontalExtraSpace?: any;
    containerPaddingEnd?: any;
    backgroundColor?: any;
    tapPadding?: any;
    isZoomAllowed?: boolean;
    accessibilityConfig?: any;
  }): CombinedChartData;
  export declare interface GridLines {}
  export declare function GridLines(props: {
    color?: any;
    lineWidth?: any;
    pathEffect?: any;
    alpha?: number;
    colorFilter?: any;
    blendMode?: any;
    enableHorizontalLines?: boolean;
    enableVerticalLines?: boolean;
    drawHorizontalLines?: (...args: any[]) => any;
    drawVerticalLines?: (...args: any[]) => any;
  }): GridLines;
  export declare interface IntersectionPoint {}
  export declare function IntersectionPoint(props: {
    color?: any;
    radius?: any;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
    draw?: (...args: any[]) => any;
  }): IntersectionPoint;
  export declare interface Line {}
  export declare function Line(props: {
    dataPoints: Array<any>;
    lineStyle?: any;
    intersectionPoint?: any;
    selectionHighlightPoint?: any;
    shadowUnderLine?: any;
    selectionHighlightPopUp?: any;
  }): Line;
  export declare interface LineChartData {}
  export declare function LineChartData(props: {
    linePlotData: any;
    xAxisData?: any;
    yAxisData?: any;
    isZoomAllowed?: boolean;
    paddingTop?: any;
    bottomPadding?: any;
    paddingRight?: any;
    containerPaddingEnd?: any;
    backgroundColor?: any;
    gridLines?: any;
    accessibilityConfig?: any;
  }): LineChartData;
  export declare interface LinePlotData {}
  export declare function LinePlotData(props: {
    plotType?: 'Bar' | 'Donut' | 'Line' | 'Pie' | 'Wave';
    lines?: Array<any>;
  }): LinePlotData;
  export declare interface LineStyle {}
  export declare function LineStyle(props: {
    lineType?: any;
    color?: any;
    width?: number;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
  }): LineStyle;
  export declare interface SelectionHighlightPoint {}
  export declare function SelectionHighlightPoint(props: {
    color?: any;
    radius?: any;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
    draw?: (...args: any[]) => any;
    isHighlightLineRequired?: boolean;
    drawHighlightLine?: (...args: any[]) => any;
  }): SelectionHighlightPoint;
  export declare interface SelectionHighlightPopUp {}
  export declare function SelectionHighlightPopUp(props: {
    backgroundColor?: any;
    backgroundAlpha?: number;
    backgroundCornerRadius?: any;
    backgroundColorFilter?: any;
    backgroundBlendMode?: any;
    backgroundStyle?: any;
    paddingBetweenPopUpAndPoint?: any;
    labelSize?: any;
    labelColor?: any;
    labelAlignment?: any;
    labelTypeface?: any;
    popUpLabel?: (...args: any[]) => any;
    draw?: (...args: any[]) => any;
  }): SelectionHighlightPopUp;
  export declare interface ShadowUnderLine {}
  export declare function ShadowUnderLine(props: {
    color?: any;
    brush?: any;
    alpha?: number;
    style?: any;
    colorFilter?: any;
    blendMode?: any;
    draw?: (...args: any[]) => any;
    drawMultiColor?: (...args: any[]) => any;
  }): ShadowUnderLine;
  export declare interface PieChartConfig {}
  export declare function PieChartConfig(props: {
    startAngle?: number;
    showSliceLabels?: boolean;
    sliceLabelTextSize?: any;
    sliceLabelTextColor?: any;
    sliceLabelTypeface?: any;
    isAnimationEnable?: boolean;
    animationDuration?: number;
    strokeWidth?: number;
    labelFontSize?: any;
    labelTypeface?: any;
    labelVisible?: boolean;
    labelType?: any;
    labelColor?: any;
    labelColorType?: any;
    backgroundColor?: any;
    activeSliceAlpha?: number;
    inActiveSliceAlpha?: number;
    isEllipsizeEnabled?: boolean;
    sliceMinTextWidthToEllipsize?: any;
    sliceLabelEllipsizeAt?: any;
    chartPadding?: number;
    accessibilityConfig?: any;
    isSumVisible?: boolean;
    sumUnit?: string;
    isClickOnSliceEnabled?: boolean;
  }): PieChartConfig;
  export declare interface PieChartData {}
  export declare function PieChartData(props: {
    slices: Array<any>;
    plotType: 'Bar' | 'Donut' | 'Line' | 'Pie' | 'Wave';
  }): PieChartData;
  export declare const AxisPosition: {
    readonly TOP: 'TOP';
    readonly BOTTOM: 'BOTTOM';
    readonly INTERSECT: 'INTERSECT';
  };
  export declare type AxisPosition = (typeof AxisPosition)[keyof typeof AxisPosition];
  export declare interface Wave {}
  export declare function Wave(props: {
    dataPoints: Array<any>;
    waveStyle?: any;
    intersectionPoint?: any;
    selectionHighlightPoint?: any;
    shadowUnderLine?: any;
    selectionHighlightPopUp?: any;
    waveFillColor?: any;
  }): Wave;
  export declare interface WaveChartData {}
  export declare function WaveChartData(props: {
    wavePlotData: any;
    xAxisData?: any;
    yAxisData?: any;
    isZoomAllowed?: boolean;
    paddingTop?: any;
    bottomPadding?: any;
    paddingRight?: any;
    containerPaddingEnd?: any;
    backgroundColor?: any;
    gridLines?: any;
    accessibilityConfig?: any;
  }): WaveChartData;
  export declare interface WaveFillColor {}
  export declare function WaveFillColor(props: {
    topColor?: any;
    bottomColor?: any;
    topBrush?: any;
    bottomBrush?: any;
  }): WaveFillColor;
  export declare interface WavePlotData {}
  export declare function WavePlotData(props: {
    plotType?: 'Bar' | 'Donut' | 'Line' | 'Pie' | 'Wave';
    lines?: Array<any>;
  }): WavePlotData;
  export declare const XAxis: any;
  export declare const YAxis: any;
  export declare const ScrollableCanvasContainer: any;
  export declare const ItemDivider: any;
  export declare const Legends: any;
  export declare const AccessibilityBottomSheetDialog: any;
  export declare const BarInfo: any;
  export declare const BubblePointInfo: any;
  export declare const CombinedChartInfo: any;
  export declare const GroupBarInfo: any;
  export declare const LinePointInfo: any;
  export declare const SliceInfo: any;
  export declare const BarChart: any;
  export declare const GroupBarChart: any;
  export declare const HorizontalBarChart: any;
  export declare const StackedBarChart: any;
  export declare const VerticalBarChart: any;
  export declare const BubbleChart: any;
  export declare const CombinedChart: any;
  export declare const LineChart: any;
  export declare const DonutPieChart: any;
  export declare const PieChart: any;
  export declare const WaveChart: any;
}

declare module '@vesk/compose' {
  export declare interface CrossFade {}
  export declare function CrossFade(props: {
    animationSpec: any;
  }): CrossFade;
  export declare const GlideImage: any;
  export declare const GlideSubcomposition: any;
}

declare module '@vesk/browser' {
  // vesk-native browser APIs: sqlite, web storage, auth, fetch, timers and
  // friends compile to native Kotlin runtime helpers (VeskSqlite, VeskWebStorage,
  // VeskAuth, VeskFetch, VeskTimers, jsAlert, JsConsole) — never emulated in JS.
  // These are script functions/values, unlike @vesk/<library> markup components
  // (e.g. <CoilImage>) which are tags. openSqlite, signUp, signIn, signOut,
  // currentUser and isSignedIn also work as bare globals; the standard browser
  // globals (fetch, alert, timers, localStorage, sessionStorage, console, JSON,
  // window) keep their DOM-lib types when used bare.
  /** Native HTTP response from fetch(). Maps to the VeskResponse class in the
   * runtime (VeskFetch.fetch): a synchronous HttpURLConnection request that
   * returns a browser-shaped response. */
  export declare interface VeskResponse {
    /** The request URL, verbatim. */
    readonly url: string;
    /** HTTP status code; 0 on network failure (no response received). */
    readonly status: number;
    /** HTTP reason phrase; 'Network error' when the request failed. */
    readonly statusText: string;
    /** True when status is 200-299. */
    readonly ok: boolean;
    /** Response headers as sent by the server (runtime Map<String, String>). */
    readonly headers: Record<string, string>;
    /** The response body as text. */
    text(): string;
    /** The response body parsed as JSON (JSON.parse semantics; throws on invalid JSON). */
    json(): any;
  }
  
  /** Options for fetch(). Runtime reads these keys from a plain object via
   * jsMapGet; everything else is ignored. */
  export declare interface FetchInit {
    /** HTTP method; default 'GET'. GET/HEAD never send a body. */
    method?: string;
    /** Request headers as a plain object. */
    headers?: Record<string, string>;
    /** Request body; sent as UTF-8 text (only for non-GET/HEAD). */
    body?: string;
  }
  
  /** Native SQLite handle from openSqlite(). Maps to the VeskSqliteDb class in
   * the runtime — a better-sqlite3-style surface. Handles are cached per
   * database name for the process lifetime, so repeated openSqlite(name) calls
   * return the same handle. */
  export declare interface VeskSqliteDb {
    /** Run a statement with no result (CREATE TABLE, DROP, ...). */
    exec(sql: string): void;
    /** Run an INSERT/UPDATE/DELETE and report lastInsertRowid + changes (0 when the db is closed). */
    run(sql: string, params?: any[]): { lastInsertRowid: number; changes: number };
    /** First row of the query, or null when there are no rows. */
    get(sql: string, params?: any[]): Record<string, any> | null;
    /** All rows of the query as a list of plain objects. */
    all(sql: string, params?: any[]): Record<string, any>[];
    /** Close the handle; later calls return empty results (no-op). */
    close(): void;
  }
  
  /** Web Storage (localStorage / sessionStorage). Values are stored as strings
   * (null stores the literal string 'null'); getItem returns null for missing
   * keys; key(i) is the i-th key or null. localStorage persists across app
   * restarts (SharedPreferences), sessionStorage lives only for the process. */
  export declare interface WebStorage {
    /** Number of keys. */
    readonly length: number;
    /** The stored string for key, or null when missing. */
    getItem(key: string): string | null;
    /** Store a value as a string (null becomes 'null'). */
    setItem(key: string, value: string): void;
    /** Remove key. */
    removeItem(key: string): void;
    /** Remove all keys. */
    clear(): void;
    /** The key at index, or null when out of range (localStorage keys are sorted). */
    key(index: number): string | null;
  }
  
  /** The mapped subset of the window global. Only these members compile to
   * native Kotlin; anything else is a hard build error. */
  export declare interface Window {
    /** Non-blocking native AlertDialog; returns immediately. */
    alert(message?: any): void;
    /** Same as the bare fetch() global. */
    fetch(url: string, init?: FetchInit): VeskResponse;
    /** Same as the bare setTimeout() global. */
    setTimeout(fn: () => void, ms?: number): number;
    /** Same as the bare setInterval() global. */
    setInterval(fn: () => void, ms?: number): number;
    /** Same as the bare clearTimeout() global. */
    clearTimeout(id: number): void;
    /** Same as the bare clearInterval() global. */
    clearInterval(id: number): void;
  }
  
  /** The mapped subset of console. log/warn/error/info/debug print each argument
   * on its own line; time/timeEnd/count/countReset use the JsConsole runtime. */
  export declare interface Console {
    log(...args: any[]): void;
    warn(...args: any[]): void;
    error(...args: any[]): void;
    info(...args: any[]): void;
    debug(...args: any[]): void;
    /** Print the message only when the first argument is falsy. */
    assert(condition: any, message?: any): void;
    /** Print the current stack trace. */
    trace(...args: any[]): void;
    /** Start a timer labeled 'label' (JsConsole). */
    time(label?: string): void;
    /** Print elapsed time for 'label' as "<label>: N ms". */
    timeEnd(label?: string): void;
    /** Increment and print a counter for 'label'. */
    count(label?: string): void;
    /** Reset the counter for 'label'. */
    countReset(label?: string): void;
    /** Print the first argument as a group header. */
    group(...args: any[]): void;
    /** Print the first argument as a group header. */
    groupCollapsed(...args: any[]): void;
    /** Print an empty line. */
    groupEnd(): void;
    /** Print the argument. */
    table(...args: any[]): void;
    /** Print an empty line. */
    clear(): void;
  }
  /** Synchronous native fetch via HttpURLConnection on the IO dispatcher
   * (runtime VeskFetch.fetch). Unlike browsers, it blocks until the response
   * arrives; connect/read timeouts are 8s. On network failure the response has
   * status 0, ok=false and statusText 'Network error'. Requires the INTERNET
   * permission (added automatically when used). The DOM lib's Promise-based
   * fetch type is NOT this signature — use the @vesk/browser import for the
   * exact vesk-native shape. */
  export declare function fetch(url: string, init?: FetchInit): VeskResponse;
  /** Open (or reuse) a native SQLite database (runtime VeskSqlite).
   * Handles are cached per name for the process lifetime; version only applies
   * on first open. Rows are plain objects with integer/real/string/blob column
   * values; params bind positionally to ? placeholders (booleans bind as 1/0). */
  export declare function openSqlite(name: string, version?: number): VeskSqliteDb;
  /** Create a user in the native vesk_auth database (runtime VeskAuth).
   * Returns the user row { id, username } or null when the username is taken or
   * either value is empty. Passwords are stored as a SHA-256 hash of
   * "username:password" in native sqlite — never a JS shim. */
  export declare function signUp(username: string, password: string): Record<string, any> | null;
  /** Sign in and persist the session in localStorage so it survives app
   * restarts (runtime VeskAuth). Returns the user row { id, username } or null
   * on bad credentials. */
  export declare function signIn(username: string, password: string): Record<string, any> | null;
  /** Clear the persisted session (runtime VeskAuth.signOut). */
  export declare function signOut(): void;
  /** The signed-in user row { id, username } or null when signed out
   * (runtime VeskAuth.currentUser). */
  export declare function currentUser(): Record<string, any> | null;
  /** True when a session is persisted and its user still exists
   * (runtime VeskAuth.isSignedIn). */
  export declare function isSignedIn(): boolean;
  /** Run fn after ms milliseconds on the main dispatcher (runtime
   * VeskTimers.setTimeout, default 0). Returns an id for clearTimeout(). */
  export declare function setTimeout(fn: () => void, ms?: number): number;
  /** Run fn every ms milliseconds on the main dispatcher (runtime
   * VeskTimers.setInterval). Returns an id for clearInterval(). */
  export declare function setInterval(fn: () => void, ms?: number): number;
  /** Cancel a pending setTimeout (runtime VeskTimers.clearTimeout). */
  export declare function clearTimeout(id: number): void;
  /** Stop a setInterval loop (runtime VeskTimers.clearInterval). */
  export declare function clearInterval(id: number): void;
  /** Non-blocking native AlertDialog (runtime jsAlert). Android cannot
   * block the main thread, so this returns immediately and shows the dialog
   * asynchronously; the value of message is stringified (null becomes ''). */
  export declare function alert(message?: any): void;
  /** Persistent Web Storage (SharedPreferences 'vesk_web_storage').
   * Survives app restarts. See WebStorage for semantics. */
  export declare const localStorage: WebStorage;
  /** In-memory Web Storage for the process lifetime. See WebStorage for
   * semantics. */
  export declare const sessionStorage: WebStorage;
  /** The mapped subset of the window global (see Window). */
  export declare const window: Window;
  /** Logging (see Console). */
  export declare const console: Console;
  /** JSON.parse/stringify map to the native jsParseJson/jsStringify
   * runtime helpers with JS-semantics coercion. */
  export declare const JSON: {
    /** Parse a JSON string (runtime jsParseJson). */
    parse(text: string): any;
    /** Serialize a value (runtime jsStringify). */
    stringify(value: any): string;
  };
}
